package com.rag.service;

import com.rag.model.DocumentMetadata;
import com.rag.model.TextChunk;
import com.rag.pipeline.DocumentProcessor;
import com.rag.pipeline.EmbeddingService;
import com.rag.repository.DocumentRepository;
import com.rag.repository.ChunkRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.InputStream;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Slf4j
public class RAGService {

    private final DocumentProcessor documentProcessor;
    private final EmbeddingService embeddingService;
    private final DocumentRepository documentRepository;
    private final ChunkRepository chunkRepository;

    public DocumentMetadata ingestDocument(String fileName, String contentType, InputStream inputStream) {
        log.info("Ingesting document: {}", fileName);

        DocumentMetadata doc = new DocumentMetadata();
        doc.setFileName(fileName);
        doc.setContentType(contentType);

        String text = documentProcessor.extractText(inputStream, fileName);

        List<String> chunks;
        if (contentType.contains("pdf")) {
            chunks = documentProcessor.chunkText(text);
        } else {
            chunks = documentProcessor.chunkByParagraphs(text);
        }

        doc.setChunks(chunks);
        doc.setStatus("PROCESSED");
        doc.setProcessedAt(System.currentTimeMillis());

        doc = documentRepository.save(doc);

        for (int i = 0; i < chunks.size(); i++) {
            TextChunk chunk = new TextChunk(doc.getId(), chunks.get(i), i);
            float[] embedding = embeddingService.createEmbedding(chunks.get(i));
            chunk.setEmbedding(toFloatList(embedding));
            chunkRepository.save(chunk);
        }

        List<String> texts = chunks;
        List<String> chunkIds = chunkRepository.findByDocumentId(doc.getId())
            .stream()
            .map(TextChunk::getId)
            .toList();
        embeddingService.storeEmbeddings(texts, chunkIds);

        log.info("Document ingested successfully: {} chunks", chunks.size());
        return doc;
    }

    public QueryResult query(String question, int topK) {
        log.info("Processing query: {}", question);

        List<EmbeddingService.SearchResult> results = embeddingService.search(question, topK);

        StringBuilder context = new StringBuilder();
        for (int i = 0; i < results.size(); i++) {
            context.append("[").append(i + 1).append("] ")
                   .append(results.get(i).text())
                   .append("\n\n");
        }

        String response = generateResponse(question, context.toString());

        return new QueryResult(question, response, results);
    }

    private String generateResponse(String question, String context) {
        String prompt = String.format("""
            Based on the following context, answer the question.

            Context:
            %s

            Question: %s

            Answer (cite sources like [1], [2]):
            """, context, question);

        return "Based on the retrieved context, here's the answer. " +
               "This is a demonstration of the RAG pipeline. " +
               "In production, this would be generated by an LLM.";
    }

    private List<Float> toFloatList(float[] array) {
        java.util.List<Float> list = new java.util.ArrayList<>();
        for (float f : array) list.add(f);
        return list;
    }

    public record QueryResult(
        String question,
        String answer,
        List<EmbeddingService.SearchResult> sources
    ) {}
}