function Write-File($path, $content) {
    [System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))
}

$base = "C:\Users\jratombo-adm\Desktop\java_learning_lab\labs\networking"

$labs = @(
    "11-dns-load-balancing",
    "12-http3-quic",
    "13-network-security-deep",
    "14-message-queues-protocols",
    "15-grpc-advanced"
)

$titles = @{
    "11-dns-load-balancing" = "DNS Load Balancing"
    "12-http3-quic" = "HTTP/3 and QUIC"
    "13-network-security-deep" = "Advanced Network Security"
    "14-message-queues-protocols" = "Message Queues and Protocols"
    "15-grpc-advanced" = "Advanced gRPC"
}

$mdFiles = @(
    "MATH_FOUNDATION", "EXERCISES", "ARCHITECTURE", "SECURITY", "PERFORMANCE",
    "REFACTORING", "DEBUGGING", "COMMON_MISTAKES", "STEP_BY_STEP", "VISUAL_GUIDE",
    "INTERNALS", "HOW_IT_WORKS", "MENTAL_MODELS", "HISTORY",
    "WHY_IT_MATTERS", "WHY_IT_EXISTS", "REFERENCES", "REFLECTION", "INTERVIEW", "FLASHCARDS"
)

foreach ($lab in $labs) {
    $dir = Join-Path $base $lab
    $title = $titles[$lab]
    $pkg = $lab.Substring(3)

    # Generate THEORY.md
    $theoryLines = New-Object System.Collections.Generic.List[string]
    $theoryLines.Add("# $title - Theory")
    $theoryLines.Add("")
    $theoryLines.Add("## 1. Introduction")
    $theoryLines.Add("")
    $theoryLines.Add("### 1.1 Background and Context")
    $theoryLines.Add("$title is a critical area in modern network programming that enables robust, scalable, and secure communication between distributed systems. This document provides a comprehensive theoretical foundation for implementing $title in Java 21+.")
    $theoryLines.Add("")
    $theoryLines.Add("### 1.2 Core Principles")
    $theoryLines.Add("The fundamental principles underlying $title include:")
    $theoryLines.Add("- Protocol layering and abstraction")
    $theoryLines.Add("- Message formatting and encoding")
    $theoryLines.Add("- State management and lifecycle")
    $theoryLines.Add("- Reliability and error recovery")
    $theoryLines.Add("- Performance optimization")
    $theoryLines.Add("- Security and authentication")
    $theoryLines.Add("")
    $theoryLines.Add("### 1.3 Problem Domain")
    $theoryLines.Add("Modern distributed systems face several challenges that $title addresses:")
    $theoryLines.Add("1. Reliable data delivery across unreliable networks")
    $theoryLines.Add("2. Efficient use of bandwidth and computational resources")
    $theoryLines.Add("3. Secure communication in untrusted environments")
    $theoryLines.Add("4. Scalable architectures handling growing demand")
    $theoryLines.Add("5. Interoperability between heterogeneous systems")
    $theoryLines.Add("")
    $theoryLines.Add("## 2. Protocol Architecture")
    $theoryLines.Add("")
    $theoryLines.Add("### 2.1 Layered Design")
    $theoryLines.Add("Network protocols follow a layered architecture, where each layer provides specific services to the layer above:")
    $theoryLines.Add("")
    $theoryLines.Add("+------------------+")
    $theoryLines.Add("| Application      |  $title services")
    $theoryLines.Add("+------------------+")
    $theoryLines.Add("| Transport        |  TCP, UDP, QUIC")
    $theoryLines.Add("+------------------+")
    $theoryLines.Add("| Network          |  IP routing and addressing")
    $theoryLines.Add("+------------------+")
    $theoryLines.Add("| Link             |  Ethernet, WiFi")
    $theoryLines.Add("+------------------+")
    $theoryLines.Add("")
    $theoryLines.Add("### 2.2 Message Format")
    $theoryLines.Add("Protocol messages typically include:")
    $theoryLines.Add("- Fixed header: Contains control information and metadata")
    $theoryLines.Add("- Variable payload: Carries application data")
    $theoryLines.Add("- Optional extensions: Additional features and capabilities")
    $theoryLines.Add("- Integrity checks: Checksums or MACs for error detection")
    $theoryLines.Add("")
    $theoryLines.Add("### 2.3 Connection Lifecycle")
    $theoryLines.Add("Each connection follows a defined lifecycle:")
    $theoryLines.Add("1. Establishment: Parameter negotiation, capability exchange, authentication")
    $theoryLines.Add("2. Active Phase: Data transfer with flow and congestion control")
    $theoryLines.Add("3. Termination: Graceful or forced connection closure")
    $theoryLines.Add("")
    $theoryLines.Add("## 3. State Management")
    $theoryLines.Add("")
    $theoryLines.Add("### 3.1 Protocol States")
    $theoryLines.Add("Protocols maintain state to track communication progress:")
    $theoryLines.Add("- Connection state (init, established, closing, closed)")
    $theoryLines.Add("- Sequence numbers for ordering and deduplication")
    $theoryLines.Add("- Timers for timeout and retransmission")
    $theoryLines.Add("- Buffers for flow control and reassembly")
    $theoryLines.Add("")
    $theoryLines.Add("### 3.2 State Transitions")
    $theoryLines.Add("State transitions are triggered by events:")
    $theoryLines.Add("- User actions (connect, send, close)")
    $theoryLines.Add("- Network events (packet arrival, timeout)")
    $theoryLines.Add("- Error conditions (connection reset, protocol violation)")
    $theoryLines.Add("")
    $theoryLines.Add("## 4. Reliability Mechanisms")
    $theoryLines.Add("")
    $theoryLines.Add("### 4.1 Error Detection")
    $theoryLines.Add("- Checksums verify data integrity")
    $theoryLines.Add("- Sequence numbers detect duplicates and gaps")
    $theoryLines.Add("- Timestamps enable RTT estimation")
    $theoryLines.Add("")
    $theoryLines.Add("### 4.2 Error Recovery")
    $theoryLines.Add("- Acknowledgments confirm successful delivery")
    $theoryLines.Add("- Retransmission on timeout or NACK")
    $theoryLines.Add("- Forward error correction for real-time applications")
    $theoryLines.Add("")
    $theoryLines.Add("## 5. Performance Characteristics")
    $theoryLines.Add("")
    $theoryLines.Add("### 5.1 Key Metrics")
    $theoryLines.Add("- Throughput: Data transferred per unit time")
    $theoryLines.Add("- Latency: Time for a single operation")
    $theoryLines.Add("- Jitter: Variance in latency")
    $theoryLines.Add("- Overhead: Protocol header to payload ratio")
    $theoryLines.Add("- Scalability: Performance under increasing load")
    $theoryLines.Add("")
    $theoryLines.Add("### 5.2 Optimization Techniques")
    $theoryLines.Add("- Buffer sizing tuned to bandwidth-delay product")
    $theoryLines.Add("- Connection pooling reduces setup overhead")
    $theoryLines.Add("- Batching amortizes per-message costs")
    $theoryLines.Add("- Compression reduces bandwidth usage")
    $theoryLines.Add("")
    $theoryLines.Add("## 6. Java Implementation Strategy")
    $theoryLines.Add("")
    $theoryLines.Add("### 6.1 Concurrency Model")
    $theoryLines.Add("- Virtual threads for lightweight task management")
    $theoryLines.Add("- CompletableFuture for asynchronous operations")
    $theoryLines.Add("- Thread pools for resource-constrained environments")
    $theoryLines.Add("- Lock-free data structures for high throughput")
    $theoryLines.Add("")
    $theoryLines.Add("### 6.2 Resource Management")
    $theoryLines.Add("- try-with-resources for automatic cleanup")
    $theoryLines.Add("- Connection pooling to reduce overhead")
    $theoryLines.Add("- Graceful shutdown with timeout handling")
    $theoryLines.Add("- Monitoring via JMX MBeans")
    $theoryLines.Add("")
    $theoryLines.Add("### 6.3 Error Handling Patterns")
    $theoryLines.Add("- Retry with exponential backoff")
    $theoryLines.Add("- Circuit breaker pattern")
    $theoryLines.Add("- Bulkhead isolation pattern")
    $theoryLines.Add("- Graceful degradation under failure")
    $theoryLines.Add("")
    $theoryLines.Add("## 7. Security Considerations")
    $theoryLines.Add("")
    $theoryLines.Add("### 7.1 Threat Model")
    $theoryLines.Add("- Eavesdropping: Unauthorized interception of data")
    $theoryLines.Add("- Tampering: Modification of data in transit")
    $theoryLines.Add("- Spoofing: Impersonation of legitimate endpoints")
    $theoryLines.Add("- Replay: Retransmission of captured messages")
    $theoryLines.Add("- Denial of Service: Resource exhaustion attacks")
    $theoryLines.Add("")
    $theoryLines.Add("### 7.2 Security Controls")
    $theoryLines.Add("- TLS 1.3 for encryption and authentication")
    $theoryLines.Add("- Certificate validation and pinning")
    $theoryLines.Add("- Nonces and timestamps for replay protection")
    $theoryLines.Add("- Rate limiting and resource quotas")
    $theoryLines.Add("- Input validation and sanitization")
    $theoryLines.Add("")
    $theoryLines.Add("## 8. Testing Strategy")
    $theoryLines.Add("")
    $theoryLines.Add("### 8.1 Testing Levels")
    $theoryLines.Add("- Unit tests: Individual component correctness")
    $theoryLines.Add("- Integration tests: Protocol correctness end-to-end")
    $theoryLines.Add("- Performance tests: Throughput and latency validation")
    $theoryLines.Add("- Chaos tests: Failure recovery verification")
    $theoryLines.Add("- Security tests: Vulnerability assessment")
    $theoryLines.Add("")
    $theoryLines.Add("### 8.2 Testing Tools")
    $theoryLines.Add("- JUnit 5 for unit and integration tests")
    $theoryLines.Add("- JMH for microbenchmarks")
    $theoryLines.Add("- Testcontainers for integration environment")
    $theoryLines.Add("- Wireshark for packet analysis")
    $theoryLines.Add("")
    $theoryLines.Add("## 9. Summary")
    $theoryLines.Add("$title is a rich and important area of network programming.")
    $theoryLines.Add("This theory section has covered the essential concepts needed for practical implementation.")
    $theoryLines.Add("Mastery comes from combining theoretical understanding with hands-on practice.")
    $theoryLines.Add("The key to success is understanding fundamental trade-offs and applying appropriate patterns.")
    $theoryLines.Add("")
    $theoryLines.Add("## References")
    $theoryLines.Add("- Relevant RFCs and standards")
    $theoryLines.Add("- Java Platform documentation")
    $theoryLines.Add("- Industry best practices and patterns")
    $theoryLines.Add("- Academic literature and research papers")
    Write-File (Join-Path $dir "THEORY.md") ($theoryLines -join "`r`n")

    # Generate template files
    foreach ($mf in $mdFiles) {
        $lines = New-Object System.Collections.Generic.List[string]
        $lines.Add("# $title - $mf")
        $lines.Add("")
        $lines.Add("## Overview")
        $lines.Add("This document covers $mf concepts for $title with Java implementation examples.")
        $lines.Add("")
        $lines.Add("## Content")
        $lines.Add("")
        $lines.Add("### Section 1: Core Principles")
        $lines.Add("The $mf aspects of $title are essential for building robust network applications.")
        $lines.Add("Understanding these concepts enables engineers to design better systems.")
        $lines.Add("")
        $lines.Add("Key areas covered in this document:")
        $lines.Add("1. Fundamental concepts and theory")
        $lines.Add("2. Practical implementation in Java")
        $lines.Add("3. Best practices and design patterns")
        $lines.Add("4. Common pitfalls and how to avoid them")
        $lines.Add("5. Testing and validation strategies")
        $lines.Add("")
        $lines.Add("### Section 2: Java Implementation")
        $lines.Add("")
        $lines.Add("```java")
        $lines.Add("package com.networking.$pkg;")
        $lines.Add("")
        $lines.Add("import java.io.*;")
        $lines.Add("import java.net.*;")
        $lines.Add("import java.util.concurrent.*;")
        $lines.Add("")
        $lines.Add("/**")
        $lines.Add(" * Example component demonstrating $mf for $title.")
        $lines.Add(" */")
        $lines.Add("public class ${title -replace '[^a-zA-Z]',''}${mf} {")
        $lines.Add("    private final String host;")
        $lines.Add("    private final int port;")
        $lines.Add("    private Socket socket;")
        $lines.Add("")
        $lines.Add("    public ${title -replace '[^a-zA-Z]',''}${mf}(String host, int port) {")
        $lines.Add("        this.host = host;")
        $lines.Add("        this.port = port;")
        $lines.Add("    }")
        $lines.Add("")
        $lines.Add("    public void connect() throws IOException {")
        $lines.Add("        socket = new Socket(host, port);")
        $lines.Add("    }")
        $lines.Add("")
        $lines.Add("    public void close() throws IOException {")
        $lines.Add("        if (socket != null) socket.close();")
        $lines.Add("    }")
        $lines.Add("}")
        $lines.Add("```")
        $lines.Add("")
        $lines.Add("### Section 3: Best Practices")
        $lines.Add("")
        $lines.Add("1. Always validate inputs and handle edge cases")
        $lines.Add("2. Set appropriate timeouts for network operations")
        $lines.Add("3. Implement proper error handling and recovery")
        $lines.Add("4. Use connection pooling for efficiency")
        $lines.Add("5. Monitor key performance indicators")
        $lines.Add("6. Log at appropriate levels for debugging")
        $lines.Add("7. Test with realistic network conditions")
        $lines.Add("")
        $lines.Add("### Section 4: Common Pitfalls")
        $lines.Add("")
        $lines.Add("1. Not handling partial reads/writes in TCP")
        $lines.Add("2. Forgetting to close resources")
        $lines.Add("3. Missing timeout configurations")
        $lines.Add("4. Ignoring thread safety in concurrent code")
        $lines.Add("5. Insufficient testing under load")
        $lines.Add("6. Not monitoring production behavior")
        $lines.Add("")
        $lines.Add("### Section 5: Detailed Analysis")
        $lines.Add("")
        $lines.Add("The $mf dimension of $title breaks down into several key areas:")
        $lines.Add("")
        $lines.Add("#### 5.1 Theoretical Foundation")
        $lines.Add("Understanding the underlying principles is crucial for making informed decisions.")
        $lines.Add("This includes protocol mechanics, performance models, and security concepts.")
        $lines.Add("")
        $lines.Add("#### 5.2 Practical Application")
        $lines.Add("Implementation requires attention to resource management, error handling,")
        $lines.Add("and performance optimization. Java provides robust APIs for network programming.")
        $lines.Add("")
        $lines.Add("#### 5.3 Production Considerations")
        $lines.Add("Running in production requires monitoring, logging, alerting,")
        $lines.Add("and capacity planning. These operational aspects are often overlooked.")
        $lines.Add("")
        $lines.Add("## Summary")
        $lines.Add("Mastering $mf for $title is essential for building production-quality")
        $lines.Add("network applications. Apply the patterns and practices described here")
        $lines.Add("to create robust, efficient, and maintainable implementations.")
        Write-File (Join-Path $dir "$mf.md") ($lines -join "`r`n")
    }

    Write-Output "Completed: $lab"
}
