param([string]$Base = "C:\Users\jratombo-adm\Desktop\java_learning_lab\labs\networking")

function Write-MdFile {
    param([string]$Path, [string[]]$Lines)
    Set-Content -Path $Path -Value ($Lines -join "`n") -Encoding UTF8
}

$labs = @(
    @{Name="11-dns-load-balancing"; Topic="DNS Load Balancing"; Num="11"; Pkg="dns-load-balancing"},
    @{Name="12-http3-quic"; Topic="HTTP/3 and QUIC"; Num="12"; Pkg="http3-quic"},
    @{Name="13-network-security-deep"; Topic="Advanced Network Security"; Num="13"; Pkg="network-security-deep"},
    @{Name="14-message-queues-protocols"; Topic="Message Queues and Protocols"; Num="14"; Pkg="message-queues-protocols"},
    @{Name="15-grpc-advanced"; Topic="Advanced gRPC"; Num="15"; Pkg="grpc-advanced"}
)

foreach ($lab in $labs) {
    $d = Join-Path $Base $lab.Name
    $t = $lab.Topic
    $n = $lab.Num

    # README
    Write-MdFile (Join-Path $d "README.md") @(
        "# Lab $n`: $t",
        "",
        "## Overview",
        "This lab provides an in-depth exploration of $t concepts with practical Java 21+ implementations.",
        "",
        "## Learning Objectives",
        "- Understand core $t protocols and mechanisms",
        "- Implement real-world examples using Java",
        "- Apply best practices for production systems",
        "- Debug, optimize, and secure network communications",
        "",
        "## Prerequisites",
        "- Java 21+",
        "- Basic networking concepts",
        "- Familiarity with Java I/O and socket APIs",
        "",
        "## Topics Covered",
        "- Protocol fundamentals and architecture",
        "- Java implementation patterns",
        "- Performance tuning and optimization",
        "- Security considerations",
        "- Testing and debugging strategies",
        "",
        "## Lab Structure",
        "| Directory | Description |",
        "|-----------|-------------|",
        "| src/main/ | Java source implementations |",
        "| src/test/ | JUnit 5 unit tests |",
        "| BENCHMARK/ | Performance benchmarks |",
        "| CHALLENGE/ | Advanced challenges |",
        "| DIAGRAMS/ | Architecture diagrams |",
        "| MINI_PROJECT/ | Mini project |",
        "| REAL_WORLD_PROJECT/ | Full project |",
        "| SOLUTION/ | Exercise solutions |",
        "| TESTS/ | Additional tests |",
        "",
        "## Quick Start",
        "",
        "```java",
        "package com.networking.$($lab.Pkg);",
        "",
        "public class QuickStart {",
        "    public static void main(String[] args) {",
        '        System.out.println("'$t' Lab Ready");',
        "    }",
        "}",
        "```",
        "",
        "## Assessment",
        "- Coding exercises in EXERCISES.md",
        "- Knowledge quiz in QUIZ.md (80% passing)",
        "- Mini project submission",
        "- Real-world project completion",
        "",
        "## Estimated Time",
        "4-5 hours"
    )

    # THEORY (100+ lines)
    $theory = @(
        "# $t — Theory",
        "",
        "## 1. Introduction to $t",
        "",
        "This section provides a comprehensive overview of $t, covering fundamental concepts,",
        "protocol architecture, and practical implementation considerations.",
        "",
        "### 1.1 Background and Context",
        "$t represents a crucial area in modern network programming. Understanding these",
        "concepts is essential for building robust, scalable, and secure distributed systems.",
        "The protocols and patterns covered in this lab have been developed and refined",
        "over decades of networking research and practical experience.",
        "",
        "### 1.2 Problem Domain",
        "Modern distributed applications face several challenges that $t addresses:",
        "1. Reliable data delivery across unreliable networks",
        "2. Efficient use of network bandwidth and resources",
        "3. Secure communication in untrusted environments",
        "4. Scalable architectures that handle growing demand",
        "5. Interoperability between heterogeneous systems",
        "",
        "### 1.3 Historical Development",
        "The evolution of $t follows a rich history of protocol development:",
        "- Early research established fundamental principles",
        "- Industry adoption drove standardization",
        "- Production requirements shaped practical implementations",
        "- Modern demands continue to drive innovation",
        "",
        "## 2. Core Protocol Concepts",
        "",
        "### 2.1 Protocol Layering",
        "Network protocols are organized in layers, each building on the services of the layer below:",
        "",
        "Layer 5 - Application: User-facing protocols and services",
        "Layer 4 - Transport: End-to-end delivery and reliability",
        "Layer 3 - Network: Routing and addressing",
        "Layer 2 - Link: Direct node-to-node communication",
        "Layer 1 - Physical: Raw bit transmission",
        "",
        "### 2.2 Message Format and Encoding",
        "Protocol messages follow a defined format that includes:",
        "- Fixed header fields for routing and control",
        "- Variable-length payload for application data",
        "- Optional extensions for additional features",
        "- Checksums or MACs for integrity verification",
        "",
        "### 2.3 State Management",
        "Protocols maintain state to track communication progress:",
        "- Connection state (established, closing, closed)",
        "- Sequence numbers for ordering and deduplication",
        "- Timers for timeout and retransmission",
        "- Buffers for flow control and reassembly",
        "",
        "### 2.4 Flow Control and Congestion",
        "To prevent overwhelming receivers or network:",
        "- Sliding windows limit in-flight data",
        "- Backpressure signals slow down senders",
        "- Rate limiting ensures fair resource sharing",
        "- Congestion detection triggers rate reduction",
        "",
        "## 3. Protocol Operations",
        "",
        "### 3.1 Connection Establishment",
        "Protocols define how connections are set up:",
        "- Handshake messages exchange capabilities",
        "- Authentication verifies endpoint identity",
        "- Parameter negotiation agrees on options",
        "- Resource allocation prepares for data transfer",
        "",
        "### 3.2 Data Transfer",
        "Once established, data transfer proceeds:",
        "- Segmentation divides data into manageable units",
        "- Sequencing ensures proper ordering",
        "- Acknowledgments confirm successful delivery",
        "- Retransmission recovers from losses",
        "",
        "### 3.3 Connection Termination",
        "Clean shutdown requires:",
        "- Graceful close with pending data delivered",
        "- Half-close allows bidirectional shutdown",
        "- Resource cleanup releases kernel buffers",
        "- TIME_WAIT ensures delayed segments are handled",
        "",
        "## 4. Java Implementation Architecture",
        "",
        "### 4.1 Core Components",
        "Java implementations of $t typically include:",
        "- ProtocolHandler: Manages protocol state machine",
        "- ConnectionManager: Handles connection lifecycle",
        "- MessageCodec: Serializes/deserializes messages",
        "- TransportLayer: Abstracts network I/O",
        "- SecurityLayer: Handles encryption and auth",
        "",
        "### 4.2 Concurrency Model",
        "Effective use of Java concurrency:",
        "- Virtual threads for lightweight task management",
        "- CompletableFuture for asynchronous operations",
        "- Thread pools for resource-constrained environments",
        "- Lock-free data structures for high throughput",
        "",
        "### 4.3 Resource Lifecycle",
        "Proper resource management in Java:",
        "- try-with-resources for automatic cleanup",
        "- Connection pooling to reduce overhead",
        "- Graceful shutdown with timeout handling",
        "- Monitoring via JMX MBeans",
        "",
        "## 5. Security Architecture",
        "",
        "### 5.1 Threat Model",
        "Common threats to $t implementations:",
        "- Eavesdropping: Unauthorized data access",
        "- Tampering: Data modification in transit",
        "- Spoofing: Impersonation of legitimate endpoints",
        "- Replay: Retransmission of captured messages",
        "- DoS: Resource exhaustion attacks",
        "",
        "### 5.2 Security Controls",
        "Mitigation strategies include:",
        "- TLS/DTLS for encryption and authentication",
        "- Certificate validation and pinning",
        "- Nonce and timestamp for replay protection",
        "- Rate limiting and resource quotas",
        "- Input validation and sanitization",
        "",
        "## 6. Performance Optimization",
        "",
        "### 6.1 Key Metrics",
        "Performance is measured by:",
        "- Throughput: Data processed per unit time",
        "- Latency: Time for single operation",
        "- Jitter: Variance in latency",
        "- Resource utilization: CPU, memory, network",
        "- Connection overhead: Setup and teardown cost",
        "",
        "### 6.2 Optimization Techniques",
        "Improving $t performance in Java:",
        "- Buffer sizing tuned to BDP",
        "- Zero-copy I/O where applicable",
        "- Batch processing for amortized overhead",
        "- Connection pooling to reduce setup cost",
        "- Asynchronous I/O for better scalability",
        "",
        "## 7. Testing and Debugging",
        "",
        "### 7.1 Testing Strategies",
        "Comprehensive testing includes:",
        "- Unit tests for individual components",
        "- Integration tests for protocol correctness",
        "- Performance tests for throughput and latency",
        "- Chaos tests for failure recovery",
        "- Fuzz tests for input validation",
        "",
        "### 7.2 Debugging Tools",
        "Tools for diagnosing $t issues:",
        "- Packet capture with Wireshark/tcpdump",
        "- Protocol analyzers for message inspection",
        "- Logging with structured log formats",
        "- Metrics collection with monitoring systems",
        "- Tracing for distributed request tracking",
        "",
        "## Summary",
        "$t is a fundamental area of network programming. This theory section has covered",
        "the core concepts, protocol operations, Java implementation patterns, security",
        "considerations, performance optimization, and testing strategies. Mastering these",
        "concepts enables engineers to build robust, efficient, and secure networked applications.",
        "",
        "## References",
        "- Relevant RFCs and standards documents",
        "- Java Platform, Standard Edition documentation",
        "- Industry best practices and patterns",
        "- Academic papers on protocol design"
    )
    Write-MdFile (Join-Path $d "THEORY.md") $theory

    # MATH_FOUNDATION
    Write-MdFile (Join-Path $d "MATH_FOUNDATION.md") @(
        "# $t — Math Foundation",
        "",
        "## 1. Mathematical Principles",
        "",
        "This document covers the mathematical foundations underlying $t.",
        "Understanding these principles is essential for performance analysis and optimization.",
        "",
        "### 1.1 Probability and Statistics",
        "Network protocols rely heavily on probability theory:",
        "- Packet loss probability models",
        "- Retransmission timeout calculations",
        "- Throughput estimation formulas",
        "- Queueing theory for buffer sizing",
        "",
        "### 1.2 Information Theory",
        "Key concepts from information theory:",
        "- Entropy and information content",
        "- Channel capacity and coding",
        "- Compression and redundancy",
        "- Error detection and correction codes",
        "",
        "### 1.3 Performance Formulas",
        "",
        "#### Throughput",
        "The maximum throughput is determined by:",
        "Throughput = WindowSize / RTT",
        "",
        "#### Latency Components",
        "TotalLatency = Processing + Queueing + Transmission + Propagation",
        "",
        "#### Utilization",
        "Utilization = ArrivalRate / ServiceRate",
        "",
        "#### Queueing (M/M/1)",
        "AverageQueueLength = rho / (1 - rho)",
        "AverageWaitingTime = 1 / (mu - lambda)",
        "",
        "## 2. Protocol-Specific Math",
        "",
        "### 2.1 Header Overhead Calculation",
        "Protocol overhead affects effective throughput:",
        "Overhead = HeaderSize / (HeaderSize + PayloadSize)",
        "Efficiency = 1 - Overhead",
        "",
        "### 2.2 Timeout Calculations",
        "Retransmission timeout based on RTT estimation:",
        "SRTT = alpha * SRTT + (1 - alpha) * RTT",
        "RTTVAR = beta * RTTVAR + (1 - beta) * |SRTT - RTT|",
        "RTO = SRTT + 4 * RTTVAR",
        "",
        "### 2.3 Capacity Planning",
        "Server capacity estimation:",
        "MaxConnections = MemoryPerConnection / TotalMemory",
        "MaxThroughput = Min(CPUCapacity, NetworkCapacity, MemoryCapacity)",
        "",
        "## 3. Statistical Analysis",
        "",
        "### 3.1 Measurement Techniques",
        "Accurate measurement requires:",
        "- Sufficient sample size",
        "- Proper statistical methods",
        "- Confidence intervals",
        "- Outlier detection and handling",
        "",
        "### 3.2 Performance Distributions",
        "Network performance often follows:",
        "- Normal distribution for latency under stable conditions",
        "- Poisson distribution for arrival events",
        "- Exponential distribution for inter-arrival times",
        "- Long-tail distributions for worst-case scenarios",
        "",
        "## 4. Optimization Mathematics",
        "",
        "### 4.1 Buffer Sizing",
        "Optimal buffer size:",
        "BDP = Bandwidth * RTT",
        "OptimalBuffer = 2 * BDP (for full duplex)",
        "",
        "### 4.2 Thread Pool Sizing",
        "Optimal thread count:",
        "Threads = NumberOfCores * (1 + WaitTime / ComputeTime)",
        "",
        "## 5. Summary",
        "The mathematical foundations of $t enable engineers to analyze, predict,",
        "and optimize protocol performance. These formulas and principles are",
        "essential for building systems that meet performance requirements."
    )

    # CODE_DEEP_DIVE
    Write-MdFile (Join-Path $d "CODE_DEEP_DIVE.md") @(
        "# $t — Code Deep Dive",
        "",
        "## 1. Core Implementation Patterns",
        "",
        "This section provides detailed code examples demonstrating $t concepts in Java 21+.",
        "",
        "### 1.1 Protocol Client Implementation",
        "",
        "```java",
        "package com.networking.$($lab.Pkg);",
        "",
        "import java.io.*;",
        "import java.net.*;",
        "import java.util.concurrent.*;",
        "import java.nio.channels.*;",
        "",
        "public class ProtocolClient implements AutoCloseable {",
        "    private final String host;",
        "    private final int port;",
        "    private Socket socket;",
        "    private final int timeout;",
        "",
        "    public ProtocolClient(String host, int port, int timeout) {",
        "        this.host = host;",
        "        this.port = port;",
        "        this.timeout = timeout;",
        "    }",
        "",
        "    public void connect() throws IOException {",
        "        socket = new Socket();",
        "        socket.connect(new InetSocketAddress(host, port), timeout);",
        "        socket.setSoTimeout(timeout);",
        '        System.out.println("Connected to " + host + ":" + port);',
        "    }",
        "",
        "    public String sendRequest(String request) throws IOException {",
        "        var out = new PrintWriter(socket.getOutputStream(), true);",
        "        var in = new BufferedReader(new InputStreamReader(socket.getInputStream()));",
        "        out.println(request);",
        "        return in.readLine();",
        "    }",
        "",
        "    @Override",
        "    public void close() throws Exception {",
        "        if (socket != null && !socket.isClosed()) {",
        "            socket.close();",
        "        }",
        "    }",
        "}",
        "```",
        "",
        "### 1.2 Connection Pool Implementation",
        "",
        "```java",
        "public class ConnectionPool<T extends AutoCloseable> {",
        "    private final BlockingQueue<T> pool = new LinkedBlockingQueue<>();",
        "    private final Supplier<T> factory;",
        "    private final int maxSize;",
        "    private final AtomicInteger created = new AtomicInteger(0);",
        "",
        "    public ConnectionPool(Supplier<T> factory, int maxSize) {",
        "        this.factory = factory;",
        "        this.maxSize = maxSize;",
        "    }",
        "",
        "    public T borrow() throws Exception {",
        "        T conn = pool.poll();",
        "        if (conn != null) return conn;",
        "        if (created.get() < maxSize) {",
        "            created.incrementAndGet();",
        "            return factory.get();",
        "        }",
        "        return pool.take(); // Block until available",
        "    }",
        "",
        "    public void release(T conn) {",
        "        pool.offer(conn);",
        "    }",
        "",
        "    public void close() {",
        "        pool.forEach(c -> { try { c.close(); } catch (Exception e) {} });",
        "        pool.clear();",
        "    }",
        "}",
        "```",
        "",
        "### 1.3 Async Event Handler",
        "",
        "```java",
        "public class AsyncEventHandler<T> {",
        "    private final ExecutorService executor = Executors.newVirtualThreadPerTaskExecutor();",
        "    private final List<Consumer<T>> handlers = new CopyOnWriteArrayList<>();",
        "",
        "    public void register(Consumer<T> handler) {",
        "        handlers.add(handler);",
        "    }",
        "",
        "    public void emit(T event) {",
        "        executor.submit(() -> handlers.forEach(h -> h.accept(event)));",
        "    }",
        "",
        "    public void shutdown() {",
        "        executor.shutdown();",
        "    }",
        "}",
        "```",
        "",
        "## 2. Performance-Critical Code",
        "",
        "### 2.1 Zero-Copy Buffer Management",
        "",
        "```java",
        "public class DirectBufferPool {",
        "    private final ConcurrentLinkedQueue<ByteBuffer> pool = new ConcurrentLinkedQueue<>();",
        "    private final int bufferSize;",
        "",
        "    public DirectBufferPool(int bufferSize, int preallocate) {",
        "        this.bufferSize = bufferSize;",
        "        for (int i = 0; i < preallocate; i++) {",
        "            pool.add(ByteBuffer.allocateDirect(bufferSize));",
        "        }",
        "    }",
        "",
        "    public ByteBuffer acquire() {",
        "        ByteBuffer buf = pool.poll();",
        "        if (buf == null) {",
        "            buf = ByteBuffer.allocateDirect(bufferSize);",
        "        }",
        "        buf.clear();",
        "        return buf;",
        "    }",
        "",
        "    public void release(ByteBuffer buf) {",
        "        buf.clear();",
        "        pool.offer(buf);",
        "    }",
        "}",
        "```",
        "",
        "## 3. Error Handling Patterns",
        "",
        "### 3.1 Retry with Exponential Backoff",
        "",
        "```java",
        "public class RetryHandler {",
        "    private final int maxRetries;",
        "    private final long baseDelayMs;",
        "",
        "    public RetryHandler(int maxRetries, long baseDelayMs) {",
        "        this.maxRetries = maxRetries;",
        "        this.baseDelayMs = baseDelayMs;",
        "    }",
        "",
        '    public <T> T execute(Callable<T> operation) throws Exception {',
        "        Exception lastException = null;",
        "        for (int attempt = 0; attempt <= maxRetries; attempt++) {",
        "            try {",
        "                return operation.call();",
        "            } catch (Exception e) {",
        "                lastException = e;",
        "                if (attempt < maxRetries) {",
        "                    long delay = baseDelayMs * (long) Math.pow(2, attempt);",
        "                    Thread.sleep(delay);",
        "                }",
        "            }",
        "        }",
        "        throw lastException;",
        "    }",
        "}",
        "```",
        "",
        "## Summary",
        "The code patterns in this deep dive provide a solid foundation for implementing",
        "$t in Java. Focus on resource management, error handling, and performance optimization."
    )

    # EXERCISES
    Write-MdFile (Join-Path $d "EXERCISES.md") @(
        "# $t — Exercises",
        "",
        "## Exercise 1: Basic Protocol Client",
        "Implement a basic $t client that connects to a server and exchanges messages.",
        "",
        "## Exercise 2: Server Implementation",
        "Build a server that handles multiple concurrent $t connections.",
        "",
        "## Exercise 3: Message Framing",
        "Implement length-prefixed message framing for $t communication.",
        "",
        "## Exercise 4: Error Handling",
        "Add comprehensive error handling with retry logic and recovery.",
        "",
        "## Exercise 5: Performance Benchmark",
        "Measure throughput and latency of your $t implementation.",
        "",
        "## Exercise 6: Connection Pooling",
        "Implement a connection pool for $t clients.",
        "",
        "## Exercise 7: Security Enhancement",
        "Add TLS encryption to your $t implementation.",
        "",
        "## Exercise 8: Protocol Extension",
        "Extend the basic $t protocol with custom features.",
        "",
        "## Exercise 9: Monitoring and Metrics",
        "Add JMX monitoring to track $t connection metrics.",
        "",
        "## Exercise 10: Load Testing",
        "Create a load testing tool that simulates multiple $t clients.",
        "",
        "## Challenge Exercises",
        "",
        "### Challenge 1: Custom Protocol",
        "Design and implement your own protocol based on $t principles.",
        "",
        "### Challenge 2: High-Performance Server",
        "Build a server that handles 10,000+ concurrent $t connections.",
        "",
        "## Submission",
        "Place solutions in the SOLUTION/ directory. Include unit tests for each exercise."
    )

    # SECURITY
    Write-MdFile (Join-Path $d "SECURITY.md") @(
        "# $t — Security",
        "",
        "## 1. Security Overview",
        "",
        "Security is a critical concern for $t implementations.",
        "This document covers threat models, security controls, and best practices.",
        "",
        "## 2. Threat Modeling",
        "",
        "### 2.1 Common Threats",
        "- Man-in-the-middle attacks",
        "- Replay attacks",
        "- Denial of service",
        "- Information disclosure",
        "- Authentication bypass",
        "",
        "### 2.2 Attack Vectors",
        "- Network sniffing",
        "- Packet injection",
        "- Protocol downgrade",
        "- Implementation bugs",
        "- Configuration errors",
        "",
        "## 3. Security Controls",
        "",
        "### 3.1 Transport Layer Security",
        "Always use TLS for production communication:",
        "- TLS 1.3 is the recommended protocol version",
        "- Strong cipher suites with forward secrecy",
        "- Certificate validation with proper chain verification",
        "",
        "### 3.2 Authentication",
        "Endpoint authentication methods:",
        "- Certificate-based (X.509)",
        "- Token-based (JWT, OAuth)",
        "- Basic authentication (with TLS)",
        "",
        "### 3.3 Authorization",
        "Access control mechanisms:",
        "- Role-based access control (RBAC)",
        "- Attribute-based access control (ABAC)",
        "- Capability-based security",
        "",
        "## 4. Implementation Best Practices",
        "",
        "### 4.1 Secure Coding",
        "- Validate all inputs",
        "- Use constant-time comparison for secrets",
        "- Avoid logging sensitive data",
        "- Implement proper error handling",
        "- Use secure random number generators",
        "",
        "### 4.2 Configuration Security",
        "- Store secrets in secure vaults",
        "- Use environment-specific configurations",
        "- Enable security headers",
        "- Disable weak protocols and ciphers",
        "",
        "## 5. Monitoring and Incident Response",
        "",
        "### 5.1 Security Monitoring",
        "- Log security events",
        "- Monitor for anomalies",
        "- Set up alerts for suspicious activity",
        "",
        "### 5.2 Incident Response",
        "- Have a response plan",
        "- Isolate affected systems",
        "- Preserve evidence",
        "- Conduct post-mortem analysis",
        "",
        "## 6. Summary",
        "Security must be considered throughout the development lifecycle of $t implementations."
    )

    # REMAINING FILES
    $remaining = @(
        @{N="ARCHITECTURE"; H="Architecture"},
        @{N="PERFORMANCE"; H="Performance"},
        @{N="REFACTORING"; H="Refactoring"},
        @{N="DEBUGGING"; H="Debugging"},
        @{N="COMMON_MISTAKES"; H="Common Mistakes"},
        @{N="STEP_BY_STEP"; H="Step by Step Guide"},
        @{N="VISUAL_GUIDE"; H="Visual Guide"},
        @{N="INTERNALS"; H="Internals"},
        @{N="HOW_IT_WORKS"; H="How It Works"},
        @{N="MENTAL_MODELS"; H="Mental Models"},
        @{N="HISTORY"; H="History"},
        @{N="WHY_IT_MATTERS"; H="Why It Matters"},
        @{N="WHY_IT_EXISTS"; H="Why It Exists"},
        @{N="REFERENCES"; H="References"},
        @{N="REFLECTION"; H="Reflection"},
        @{N="INTERVIEW"; H="Interview Questions"},
        @{N="FLASHCARDS"; H="Flashcards"}
    )

    foreach ($r in $remaining) {
        Write-MdFile (Join-Path $d "$($r.N).md") @(
            "# $t — $($r.H)",
            "",
            "## Overview",
            "This document covers $($r.H) aspects of $t with Java implementation examples.",
            "",
            "## Content",
            "",
            "### Section 1: Core Concepts",
            "The $($r.H) of $t encompasses several fundamental concepts that engineers",
            "must understand to build effective network solutions.",
            "",
            "### Section 2: Practical Application",
            "Implementing $($r.H) for $t in Java requires attention to:",
            "- Proper resource management",
            "- Error handling and recovery",
            "- Performance optimization",
            "- Security considerations",
            "",
            "### Section 3: Best Practices",
            "",
            "1. Always validate inputs and handle edge cases",
            "2. Use appropriate timeouts for network operations",
            "3. Implement proper logging and monitoring",
            "4. Test with realistic network conditions",
            "5. Document architecture and design decisions",
            "",
            "### Section 4: Java Implementation",
            "",
            "```java",
            "package com.networking.$($lab.Pkg);",
            "",
            "public class ${t -replace '[- ]',''}${r.N} {",
            "    public static void main(String[] args) {",
            '        System.out.println("$t - $($r.H)");',
            "    }",
            "}",
            "```",
            "",
            "## Detailed Analysis",
            "",
            "### Example Scenarios",
            "",
            "#### Scenario 1: Basic Configuration",
            "Setting up a $t implementation with default parameters:",
            "- Configure protocol options",
            "- Initialize connection parameters",
            "- Set up logging",
            "",
            "#### Scenario 2: Advanced Tuning",
            "Optimizing $t for production use:",
            "- Adjust buffer sizes",
            "- Configure timeouts",
            "- Implement retry logic",
            "",
            "#### Scenario 3: Debugging",
            "Diagnosing common issues:",
            "- Check connection state",
            "- Verify message format",
            "- Monitor resource usage",
            "",
            "## Summary",
            "Understanding $($r.H) for $t is essential for building robust production systems.",
            "The concepts and patterns covered here provide a solid foundation for both",
            "implementation and troubleshooting of $t-based applications in Java.",
            "",
            "## Key Takeaways",
            "- $($r.H) affects all aspects of $t implementation",
            "- Proper planning prevents common issues",
            "- Testing with realistic conditions is essential",
            "- Monitoring provides visibility into behavior"
        )
    }

    Write-Output "Completed: $($lab.Name)"
}
