#!/usr/bin/env python3
import os

BASE = r"C:\Users\jratombo-adm\Desktop\java_learning_lab\labs\data-engineering"

def w(path, content):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(content.lstrip() + "\n")
        return True
    return False

# ===== LAB 07: DATA LAKE =====
d = os.path.join(BASE, "07-data-lake")
for fname, c in {
    "THEORY.md": "# Data Lake Theory\n\n## Medallion Architecture\n- **Bronze**: Raw immutable data, original format, schema-on-read\n- **Silver**: Cleaned, deduplicated, schema enforced\n- **Gold**: Aggregated, business-ready, denormalized\n\n## Table Formats\n| Feature | Delta Lake | Iceberg | Hudi |\n|---------|-----------|---------|------|\n| ACID | Yes | Yes | Yes |\n| Time Travel | Yes | Yes | Yes |\n| Schema Evolution | Yes | Yes | Yes |\n| Upsert | Yes | Yes | Yes |",
    "INTERNALS.md": "# Data Lake Internals\n\n## Delta Lake Transaction Log\nJSON files in _delta_log/ tracking:\n- Add/remove file actions\n- Schema changes\n- Commit info\n- Checkpoint files\n\n## File Layout\n```\ns3://lake/\n  bronze/events/event_date=YYYY-MM-DD/\n    part-00001.snappy.parquet\n    _delta_log/00000000000000000001.json\n  silver/events/...\n  gold/aggregates/...\n```",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Storage\n`Raw = Sum(SourceSizes) * Replication`\n`Compressed = Raw / CompressionRatio (3-10x)`\n\n## Cost\n`Storage = DataSize * $/GB/month * Replication`\n`Compute = ScanCost * Queries`\n\n## File Size\n`Optimal = ~128MB`\n`Target: 64MB - 1GB per file`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Medallion Architecture\n```\nSource Data -> [BRONZE] raw -> [SILVER] clean -> [GOLD] aggregated -> BI\n```\n\n## Delta Lake Timeline\n```\nv1: INSERT file1 -> v2: INSERT file2 -> v3: UPDATE (remove file1, add file3)\nRead at v2: file1 + file2\nRead at v4: file3 (after update+delete)\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Delta Lake\n\n## Operations\n```java\npublic class DeltaLakeOps {\n    // Upsert\n    spark.sql(\"MERGE INTO delta.`/path` t USING updates s \" +\n        \"ON t.id = s.id \" +\n        \"WHEN MATCHED THEN UPDATE SET * \" +\n        \"WHEN NOT MATCHED THEN INSERT *\");\n\n    // Time Travel\n    spark.read().format(\"delta\").option(\"versionAsOf\", 25).load(\"/path\");\n\n    // Optimize\n    spark.sql(\"OPTIMIZE delta.`/path` ZORDER BY (customer_id)\");\n\n    // Vacuum\n    spark.sql(\"VACUUM delta.`/path` RETAIN 168 HOURS\");\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Choose Storage**: S3, ADLS, GCS, HDFS\n2. **Configure Delta**: DeltaSparkSessionExtension\n3. **Bronze**: Write raw data with partitionBy(ingestion_date)\n4. **Silver**: Clean, deduplicate, validate\n5. **Gold**: Aggregate, denormalize for BI\n6. **Optimize**: Compaction, Z-order, vacuum",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **Data Swamp**: No organization, no catalog\n2. **No Partitioning**: Full table scans on all queries\n3. **Too Many Small Files**: <64MB files cause metadata overhead\n4. **No Lifecycle**: Keep everything forever (costs grow unbounded)\n5. **Wrong Format**: Not using columnar formats (Parquet/Delta)",
    "DEBUGGING.md": "# Debugging\n\n## Transaction Log Conflicts\nMultiple writers need separate partition directories.\n\n## Metadata Issues\nLarge Iceberg metadata needs regular compaction.\n\n## Partition Pruning\nCheck if predicates are pushed down:\n```java\ndataset.explain(\"formatted\");\n```",
    "PERFORMANCE.md": "# Performance\n\n## Compaction\n```sql\nOPTIMIZE delta./path ZORDER BY (customer_id, product_id);\n```\n\n## Partitioning\n```java\ndata.write().partitionBy(\"year\",\"month\").format(\"delta\").save(\"...\");\n```\n\n## File Sizing\n```java\nspark.conf().set(\"spark.sql.files.maxPartitionBytes\", \"134217728\");\n```",
    "SECURITY.md": "# Security\n\n## Bucket Policies\nIAM policies for S3 bucket access control per layer.\n\n## Column Masking\n```java\nspark.sql(\"CREATE VIEW safe_employees AS \" +\n    \"SELECT id, name, CONCAT(LEFT(ssn,4),'***-****') as ssn \" +\n    \"FROM employees\");\n```\n\n## Encryption\nServer-side encryption (SSE-S3/KMS) for data at rest.",
    "ARCHITECTURE.md": "# Architecture\n\n## Lakehouse\n```\n[BI Tools] -> [Gold Layer] -> [Silver Layer] -> [Bronze Layer] -> [Storage]\n```\n\n## Components\n- Catalog (Unity, Glue, Hive)\n- Table Format (Delta, Iceberg, Hudi)\n- Storage (S3, ADLS, GCS)",
    "EXERCISES.md": "# Exercises\n\n1. Bronze layer: Ingest JSON to Delta with partitioning\n2. Silver layer: Clean and deduplicate\n3. Time travel: Point-in-time query\n4. Merge/Upsert: Handle late-arriving data\n5. Iceberg: Create and query with partition evolution",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 07 done")

# ===== LAB 08: WORKFLOW ORCHESTRATION =====
d = os.path.join(BASE, "08-workflow-orchestration")
for fname, c in {
    "THEORY.md": "# Orchestration Theory\n\n## DAG Fundamentals\n- **Nodes**: Tasks (operators)\n- **Edges**: Dependencies\n- **Topological Order**: Execution sequence\n- **No Cycles**: Prevents infinite loops\n\n## Execution Models\n- Sequential: One task at a time\n- Parallel: Independent tasks run simultaneously\n- Conditional: Branch based on outcome\n\n## Strategy Comparison\n| Tool | Language | Scalability |\n|------|----------|-------------|\n| Airflow | Python | High |\n| Prefect | Python | High |\n| Dagster | Python | High |\n| Luigi | Python | Medium |",
    "WHY_IT_MATTERS.md": "# Why Orchestration Matters\n\n- **Reliability**: Auto-retry reduces failures 80%\n- **Visibility**: Single UI for all pipelines\n- **Efficiency**: Parallel execution reduces runtime\n- **Governance**: Audit trail of all executions\n\n## Cost of Not Orchestrating\n- Manual monitoring 24/7\n- Missed SLAs\n- Debugging nightmare with cron dependencies",
    "INTERNALS.md": "# Orchestration Internals\n\n## Scheduler Loop\n1. Parse DAG files (every 30s)\n2. Create DAG runs (schedule, catchup)\n3. Create Task Instances\n4. Queue tasks to Executor\n5. Process results\n6. Evaluate next dependencies\n\n## Task Lifecycle\n```\nnone -> scheduled -> queued -> running -> success/failed/up_for_retry\n```",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Scheduling\n`Next = schedule_interval.ceil(start_date)`\n`Backfill = Historical runs between start_date and now`\n\n## DAG Complexity\n`Complexity = O(N + E)` for topological sort\n`Critical Path = Longest path (minimum execution time)`\n\n## SLA Metrics\n`Success Rate = Succeeded / (Succeeded + Failed)`\n`Duration P50/P95/P99 = Percentile(durations)`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## DAG Tree\n```\n[Start] -> [Extract Orders] -> [Validate] -> [Load Orders] -> [Notify]\n[Start] -> [Extract Customers] -> [Validate] -> [Load Customers] -> [Notify]\n```\n\n## Web UI Views\n- Tree: Dependency hierarchy\n- Graph: DAG visualization\n- Gantt: Task timing\n- Code: DAG source",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Airflow DAG\n\n## Complete DAG\n```python\nfrom airflow import DAG\nfrom airflow.providers.apache.spark.operators.spark_submit import SparkSubmitOperator\nfrom airflow.operators.python import PythonOperator\nfrom datetime import datetime, timedelta\n\ndag = DAG('data_pipeline', schedule_interval='0 2 * * *',\n    start_date=datetime(2024, 1, 1), catchup=True)\n\nextract = SparkSubmitOperator(task_id='extract',\n    application='/jobs/extract.py', executor_memory='8g', dag=dag)\n\nvalidate = PythonOperator(task_id='validate',\n    python_callable=run_checks, dag=dag)\n\nload = SparkSubmitOperator(task_id='load',\n    application='/jobs/load.py', dag=dag)\n\nextract >> validate >> load\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Install**: pip install apache-airflow\n2. **Init**: airflow db init\n3. **Create DAG**: Python file in dags/\n4. **Start**: airflow webserver + airflow scheduler\n5. **Monitor**: http://localhost:8080\n6. **Integrate**: SparkSubmitOperator for Java/Spark jobs",
    "DEBUGGING.md": "# Debugging\n\n## DAG Not Appearing\n```bash\naiflow dags list-import-errors\npython -c \"import ast; ast.parse(open('dag.py').read())\"\n```\n\n## Task Stuck\n```bash\naiflow jobs check\ncelery -A airflow.executors.celery_executor inspect active\n```\n\n## Test Single Task\n```bash\naiflow tasks test my_dag my_task 2024-01-01\n```",
    "PERFORMANCE.md": "# Performance\n\n## Scheduler Tuning\n```bash\naiflow config set scheduler parsing_processes 4\naiflow config set scheduler min_file_process_interval 30\n```\n\n## Database Cleanup\n```sql\nDELETE FROM task_instance WHERE start_date < NOW() - INTERVAL '30 days';\nDELETE FROM log WHERE dttm < NOW() - INTERVAL '30 days';\n```\n\n## Deferrable Operators\nUse mode='reschedule' for long-running sensors.",
    "SECURITY.md": "# Security\n\n## RBAC\nEnable RBAC in airflow.cfg for role-based access.\n\n## Variables\nUse Airflow Variables (encrypted) for secrets.\n\n## Connections\n```python\nconn = BaseHook.get_connection(\"my_db\")\npassword = conn.get_password()\n```\n\n## Network\nUse private subnets, VPC peering, SSL for webserver.",
    "ARCHITECTURE.md": "# Architecture\n\n## Production Setup\n```\n[Webserver] [Scheduler]\n     |           |\n[PostgreSQL] [Redis/Celery]\n              |\n         [Workers]\n```\n\n## Components\n- Webserver: UI\n- Scheduler: Triggers DAGs\n- Executor: Runs tasks (Celery, K8s)\n- Metadata DB: PostgreSQL/MySQL",
    "EXERCISES.md": "# Exercises\n\n1. Simple DAG with 3 tasks (extract, transform, load)\n2. Branch operator for quality check pass/fail\n3. ExternalTaskSensor to wait for upstream DAG\n4. Java/Spark integration via SparkSubmitOperator\n5. Backfill past 30 days",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 08 done")

# ===== LAB 09: DATA QUALITY =====
d = os.path.join(BASE, "09-data-quality")
for fname, c in {
    "THEORY.md": "# Data Quality Theory\n\n## Six Dimensions\n1. **Accuracy**: Data reflects real-world values\n2. **Completeness**: All required data present\n3. **Consistency**: Consistent across systems\n4. **Timeliness**: Current and available\n5. **Validity**: Conforms to formats/rules\n6. **Uniqueness**: No duplicates\n\n## Check Types\n- Freshness: How recent?\n- Volume: Expected counts\n- Schema: Column types/constraints\n- Content: Value ranges, patterns\n- Referential: FK relationships",
    "INTERNALS.md": "# Quality Internals\n\n## Check Engine\n```java\npublic abstract class QualityCheck {\n    public abstract CheckResult run(Dataset<Row> data, QualityConfig config);\n}\n```\n\n## Anomaly Detection\n```java\npublic List<Anomaly> detect(Dataset<Row> data, String column) {\n    double mean = data.agg(avg(col(column))).first().getDouble(0);\n    double stddev = data.agg(stddev(col(column))).first().getDouble(0);\n    return data.withColumn(\"z_score\", abs(col(column).minus(mean)).divide(stddev))\n        .filter(col(\"z_score\").$greater(3.0)).collectAsList();\n}\n```",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Statistical\n`Z-Score = (xi - mean) / stddev`\n`Outlier: |Z| > 3 (99.7% confidence)`\n`IQR = Q3 - Q1`\n`Outlier: x < Q1 - 1.5*IQR or x > Q3 + 1.5*IQR`\n\n## Quality Metrics\n`Completeness = NonNull / Total * 100`\n`Uniqueness = Distinct / Total * 100`\n`Overall DQ Score = WeightedAverage(dimension_scores)`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Quality Check Pipeline\n```\n[Input] -> [Schema Check] -> [Null Check] -> [Range Check]\n       -> [Uniqueness] -> [Format Check] -> [Quality Report]\n```\n\n## Quality Dashboard\n```\nOverall Score: 87%\nCompleteness: 95% [=====]\nUniqueness:   99% [======]\nConsistency:  88% [==== ]\nTimeliness:   92% [=====]\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Quality Framework\n\n## Complete Validator\n```java\n@Component\npublic class DataQualityFramework {\n    private final List<QualityRule> rules;\n    private final AlertService alertService;\n\n    public QualityReport validate(Dataset<Row> data, String dataset) {\n        QualityReport report = new QualityReport(dataset, Instant.now());\n        for (QualityRule rule : rules) {\n            RuleResult result = rule.evaluate(data);\n            report.addResult(result);\n            if (!result.isPassed() && rule.getSeverity() == CRITICAL) {\n                alertService.sendCriticalAlert(result);\n            }\n        }\n        return report;\n    }\n}\n\n@Component\nclass NullCheckRule implements QualityRule {\n    @Override\n    public RuleResult evaluate(Dataset<Row> data) {\n        Map<String, Double> nullRates = new HashMap<>();\n        for (String col : data.columns()) {\n            long nullCount = data.filter(col(col).isNull()).count();\n            nullRates.put(col, (double) nullCount / data.count());\n        }\n        return new RuleResult(\"NullCheck\", nullRates.values().stream()\n            .allMatch(r -> r < 0.05), nullRates, \"\", Severity.HIGH);\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Define Rules**: NOT_NULL, UNIQUE, RANGE, REGEX\n2. **Set Thresholds**: Configurable via properties\n3. **Implement Checks**: Deequ or custom rules\n4. **Run Scheduled**: Cron or Airflow\n5. **Alert**: Slack, email, PagerDuty\n6. **Dashboard**: Quality metrics and trends",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **End-Only Checks**: Check only at load (check every stage)\n2. **Empty DataFrames**: Not handling empty data before checks\n3. **Hardcoded Thresholds**: Not configurable via properties\n4. **No Trend Monitoring**: Check each run independently\n5. **Exposing PII**: Showing sensitive data in quality alerts",
    "DEBUGGING.md": "# Debugging\n\n## High Null Rate\nCheck for schema drift in source.\n\n## Duplicates After Restart\nCheck batch_id distribution.\n\n## Referential Failures\n```java\ndata.join(dimTable, \"key\", \"left_anti\").groupBy(\"source\").count().show();\n```\n\n## Freshness Issues\n```java\ndata.agg(max(\"updated_at\")).show();\n```",
    "PERFORMANCE.md": "# Performance\n\n## Sampling\n```java\nDataset<Row> sample = data.sample(false, 0.01); // 1%\nqualityChecks(sample);\n```\n\n## Approximate Counts\n```java\ndata.agg(approx_count_distinct(col(\"id\"))).show();\n```\n\n## Incremental Checks\n```java\nDataset<Row> incremental = data.filter(\n    col(\"etl_loaded_at\").$greater(lastCheckTime));\n```",
    "SECURITY.md": "# Security\n\n## Avoid PII in Alerts\n```java\nlong invalidCount = data.filter(...).count();\n// Report count only, not actual values\n```\n\n## Access Control\n@PreAuthorize for role-based access to quality reports.",
    "ARCHITECTURE.md": "# Architecture\n\n```\n[Quality Rules] -> [Rule Engine] -> [Metrics Store] -> [Alert Service]\n                   [Data Sources: Bronze/Silver/Gold]\n```",
    "EXERCISES.md": "# Exercises\n\n1. Basic quality checks: nulls, duplicates, type validation\n2. Anomaly detection with z-scores\n3. Schema drift detection and remediation\n4. Quality dashboard REST API\n5. Real-time quality on Kafka stream",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 09 done")

# ===== LAB 10: CDC =====
d = os.path.join(BASE, "10-change-data-capture")
for fname, c in {
    "THEORY.md": "# CDC Theory\n\n## CDC Mechanisms\n- **Log-based**: Read DB transaction log (binlog, WAL) - minimal impact\n- **Trigger-based**: DB triggers - performance impact\n- **Query-based**: Timestamp columns - simple, no deletes\n\n## Debezium Architecture\n```\n[Source DB] -> [Debezium Connector] -> [Kafka Topic] -> [Stream/Store]\n```\n\n## Change Event Structure\n```json\n{op: \"c/u/d/r\", before: {...}, after: {...}, source: {db, table, ts_ms}}\n```",
    "WHY_IT_EXISTS.md": "# Why CDC Exists\n\nBatch ETL has high latency (hours). Timestamp queries miss deletes and load sources. Log-based CDC captures all changes in real-time with zero source impact.\n\n## Use Cases\n- Real-time analytics\n- Cache invalidation\n- Search indexing\n- Database migrations\n- Audit logging\n- CQRS patterns",
    "INTERNALS.md": "# CDC Internals\n\n## Binlog Reading\nDebezium positions as MySQL replica, requests binlog stream from position, parses events (WriteRows, UpdateRows, DeleteRows), converts to Kafka events.\n\n## Offset Management\nDebezium stores offsets in Kafka topic for resume capability.\n\n## Snapshot Process\n1. Determine snapshot mode\n2. Read binlog position\n3. Export table data\n4. Emit snapshot events (op: 'r')\n5. Start streaming from recorded position",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Throughput\n`ChangeRate = DML_ops / second`\n`Lag = CurrentTime - LastCommittedTimestamp`\n`CatchupTime = LagSize / (ConsumeRate - ChangeRate)`\n\n## Event Size\n`CDCEvent = KeySize + ValueSize + Metadata`\n`NetworkLoad = CDCEvent * ChangeRate * Consumers`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## CDC Flow\n```\n[MySQL: binlog] -> [Debezium Connector] -> [Kafka: cdc.db.orders]\n                                           -> [Flink Stream]\n                                           -> [S3 Sink]\n                                           -> [Elasticsearch]\n```\n\n## Event Examples\n```\nINSERT: op:c, after:{id:1001,name:\"Jane\"}\nUPDATE: op:u, before:{name:\"Jane\"}, after:{name:\"Jane Smith\"}\nDELETE: op:d, before:{id:1001,name:\"Jane\"}, after:null\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Debezium CDC\n\n## Spring Boot Integration\n```java\n@Configuration\npublic class CdcConfig {\n    @Bean\n    public DebeziumEngine<ChangeEvent<String, String>> debeziumEngine() {\n        Properties props = new Properties();\n        props.setProperty(\"connector.class\", \"io.debezium.connector.mysql.MySqlConnector\");\n        props.setProperty(\"database.hostname\", System.getenv(\"DB_HOST\"));\n        props.setProperty(\"database.port\", \"3306\");\n        props.setProperty(\"database.user\", System.getenv(\"DB_USER\"));\n        props.setProperty(\"database.password\", System.getenv(\"DB_PASSWORD\"));\n        props.setProperty(\"topic.prefix\", \"cdc\");\n        props.setProperty(\"schema.history.internal.kafka.topic\", \"schemahistory\");\n\n        return DebeziumEngine.create(Json.class)\n            .using(props)\n            .notifying(this::handleChangeEvent)\n            .build();\n    }\n\n    private void handleChangeEvent(ChangeEvent<String, String> event) {\n        JsonNode payload = new ObjectMapper().readTree(event.value()).get(\"payload\");\n        String op = payload.get(\"op\").asText();\n        switch (op) {\n            case \"c\": handleCreate(payload.get(\"after\")); break;\n            case \"u\": handleUpdate(payload.get(\"before\"), payload.get(\"after\")); break;\n            case \"d\": handleDelete(payload.get(\"before\")); break;\n        }\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Enable binlog**: MySQL server-id, log_bin, binlog_format=ROW\n2. **Create user**: GRANT SELECT, REPLICATION SLAVE\n3. **Configure**: Debezium connector properties\n4. **Start**: Kafka Connect REST API POST /connectors\n5. **Consume**: Read from Kafka topic cdc.db.table\n6. **Process**: Stream to data lake, warehouse, cache",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **No Schema History**: In-memory loses schema on restart\n2. **Short Binlog Retention**: binlog expires before CDC processes\n3. **No Schema Evolution Handling**: DDL breaks pipeline\n4. **Single Task**: Can't keep up with large tables",
    "DEBUGGING.md": "# Debugging\n\n## Connector Status\n```bash\ncurl http://localhost:8083/connectors/inventory-connector/status\n```\n\n## Lag\n```bash\nkafka-consumer-groups --describe --group connect-connector\n```\n\n## Restart Connector\n```bash\ncurl -X POST http://localhost:8083/connectors/inventory-connector/restart\n```",
    "PERFORMANCE.md": "# Performance\n\n## Batch Size\n```java\nprops.setProperty(\"max.batch.size\", \"2048\");\nprops.setProperty(\"max.queue.size\", \"8192\");\n```\n\n## Snapshot\n```java\nprops.setProperty(\"snapshot.fetch.size\", \"10000\");\nprops.setProperty(\"snapshot.locking.mode\", \"none\");\n```\n\n## Kafka Producer\n```properties\nproducer.acks=all\nproducer.linger.ms=50\nproducer.batch.size=65536\nproducer.compression.type=snappy\n```",
    "SECURITY.md": "# Security\n\n## Credentials\nUse environment variables or Vault for DB passwords.\n\n## SSL\n```properties\ndatabase.ssl.mode=verify_full\n```\n\n## Data Masking\n```java\n.with(\"column.mask.with.2.chars.hash.salt\", \"table:sensitive_col\")\n```\n\n## Network\nCDC user should have minimal permissions (SELECT, REPLICATION SLAVE).",
    "ARCHITECTURE.md": "# Architecture\n\n## Production CDC\n```\n[MySQL] -> [Debezium] -> [Kafka Connect] -> [Kafka Cluster]\n[Postgres] -> [Debezium] -> [Kafka Connect] -> [Kafka Cluster]\n                                                 |\n                            [Flink] [S3 Sink] [Elasticsearch]\n```",
    "EXERCISES.md": "# Exercises\n\n1. Setup Debezium for MySQL, capture changes to Kafka\n2. Process CDC events with Kafka Streams (create, update, delete)\n3. Implement initial snapshot + continuous streaming\n4. Design outbox pattern for application-level CDC\n5. Handle schema change (new column) in CDC pipeline",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 10 done")

# ===== LAB 11: FEATURE STORES =====
d = os.path.join(BASE, "11-feature-stores")
for fname, c in {
    "THEORY.md": "# Feature Store Theory\n\n## Core Components\n- **Online Store**: Low-latency serving (Redis, Cassandra)\n- **Offline Store**: Historical features (S3, Delta Lake)\n- **Feature Registry**: Catalog of features, metadata, lineage\n\n## Key Problems Solved\n1. Feature reuse (no duplicated engineering)\n2. Training/serving consistency\n3. Point-in-time correctness\n4. Feature discovery\n5. Governance and lineage",
    "INTERNALS.md": "# Feature Store Internals\n\n## Point-in-Time Join\n```java\npublic Dataset<Row> pointInTimeCorrectJoin(Dataset<Row> features, Dataset<Row> labels,\n        String entityKey, String featureTs, String labelTs) {\n    return features.as(\"f\")\n        .join(labels.as(\"l\"),\n            f.col(entityKey).equalTo(l.col(entityKey))\n                .and(f.col(featureTs).$less(l.col(labelTs))))\n        .groupBy(\"l.*\")\n        .agg(max(struct(f.col(featureTs), f.col(\"*\"))).as(\"latest\"))\n        .select(\"l.*\", \"latest.*\");\n}\n```",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Storage\n`ComputeCost = Sum(FeatureCost) * UpdateFrequency`\n`Online = Entities * Features * AvgValueSize`\n`Offline = Events * Features * Size * Retention`\n\n## Serving\n`Online Latency = Network + Cache + Serialization (P99 < 10ms)`\n`Offline Throughput = ScannedData / ComputeTime (1TB / 30min)`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Architecture\n```\n[Source Events] -> [Feature Engineering] -> [Feature Store]\n                                             |           |\n                                        [Online]    [Offline]\n                                        [Redis]     [Delta]\n```\n\n## Point-in-Time\n```\nt0  t1  t2  t3  t4\ne1  e2  e3  e4  e5\n    |   |\n  Feature  Label\n  v1      L1  -> Correct (v1 < L1)\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Feature Engineering\n\n## User Feature Computation\n```java\npublic class FeatureEngineeringPipeline {\n    public Dataset<Row> computeUserFeatures(Dataset<Row> transactions) {\n        return transactions\n            .groupBy(\"user_id\")\n            .agg(\n                count(\"*\").as(\"total_orders\"),\n                sum(\"amount\").as(\"total_revenue\"),\n                avg(\"amount\").as(\"avg_order_value\"),\n                stddev(\"amount\").as(\"std_order_value\"),\n                max(\"amount\").as(\"max_order_value\"),\n                datediff(current_date(), max(\"order_date\")).as(\"days_since_last\")\n            );\n    }\n}\n```\n\n## Serving API\n```java\n@RestController\n@RequestMapping(\"/api/features\")\npublic class FeatureController {\n    @GetMapping(\"/online/{type}/{id}\")\n    public ResponseEntity<Map<String, Object>> getFeatures(\n            @PathVariable String type, @PathVariable String id,\n            @RequestParam List<String> features) {\n        return ResponseEntity.ok(featureStore.getFeatures(type, id, features));\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Define Features**: name, type, transformation\n2. **Compute Features**: Spark batch/streaming jobs\n3. **Online Store**: Deploy Redis for low-latency serving\n4. **Serve Features**: REST API for model inference\n5. **Generate Training Data**: Point-in-time correct joins",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **Point-in-Time Leakage**: Using future data in training\n2. **Online/Offline Skew**: Different computation logic\n3. **No Validation**: Trusting features without checks\n4. **No Versioning**: Overwriting feature values",
    "PERFORMANCE.md": "# Performance\n\n## Online Store\n```java\nJedisCluster cluster = new JedisCluster(\n    new HostAndPort(\"redis-1\", 6379));\nPipeline pipeline = cluster.pipelined();\n// Batch reads for multiple features\n```\n\n## Caching\n```java\n@Cacheable(value = \"features\", key = \"#type + ':' + #id\")\npublic Map<String, Object> getFeatures(String type, String id) { ... }\n```",
    "SECURITY.md": "# Security\n\n## Access Control\n```java\n@PreAuthorize(\"hasPermission('feature', 'read')\")\npublic Map<String, Object> getFeatures(...) { ... }\n```\n\n## PII\nFlag sensitive features with @FeatureMetadata(sensitive = true).\n\n## Audit\nLog all feature access for compliance.",
    "ARCHITECTURE.md": "# Architecture\n\n```\n[Feature Registry]    [Online Store]     [Offline Store]\n    (Metadata)          (Redis)         (S3/Delta)\n       |                    |                |\n       +--------[Feature Engineering]-------+\n                        |\n                   [Sources]\n```",
    "EXERCISES.md": "# Exercises\n\n1. Compute user features from transactions (avg order, frequency)\n2. Set up Redis for online feature serving\n3. Implement point-in-time correct join\n4. Build feature registry with metadata\n5. Create REST API for real-time inference features",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 11 done")

# ===== LAB 12: DATA GOVERNANCE =====
d = os.path.join(BASE, "12-data-governance")
for fname, c in {
    "THEORY.md": "# Data Governance Theory\n\n## Pillars\n1. **Data Quality**: Accuracy, completeness\n2. **Data Catalog**: Discovery, inventory\n3. **Data Lineage**: Origin, movement\n4. **Data Security**: Access control, encryption\n5. **Data Privacy**: PII handling, consent\n6. **Compliance**: GDPR, CCPA, HIPAA, SOX\n\n## Metadata Types\n- Technical: Schema, types, partitions\n- Business: Definitions, owners, tags\n- Operational: Run times, error rates",
    "INTERNALS.md": "# Governance Internals\n\n## Data Catalog Model\n```java\n@Entity\npublic class DataAsset {\n    @Id private String id;\n    private String name; private String domain; private String owner;\n    private String schemaJson; private String classification;\n    private int qualityScore; private long recordCount;\n}\n```\n\n## Lineage Database\n```java\n@Entity\npublic class LineageEdge {\n    @Id private String id;\n    private String sourceDataset; private String targetDataset;\n    private String transformation; private Instant timestamp;\n}\n```",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Compliance Risk\n`RiskScore = Sum(Regulation * Likelihood * Impact)`\n`GDPR Fine = max(10M EUR, 2% revenue) or max(20M EUR, 4% revenue)`\n\n## Coverage\n`CatalogCoverage = Cataloged / Total * 100`\n`LineageCoverage = Tracked / Cataloged * 100`\n`Target: CatalogCoverage > 90%`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Lineage\n```\n[MySQL orders] -> [Spark ETL] -> [fact_orders] -> [BI Dashboard]\n[CRM API]      -> [Spark ETL] -> [dim_customer] -> [BI Dashboard]\n```\n\n## Governance Framework\n```\n[Catalog] [Lineage] [Policies] [Quality] [Compliance]\n   Find      Track    Control    Trust    Regulations\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Governance API\n\n## REST Controllers\n```java\n@RestController\n@RequestMapping(\"/api/v1/governance\")\npublic class GovernanceApi {\n    @GetMapping(\"/catalog\")\n    public Page<DataAsset> searchCatalog(\n            @RequestParam String q, Pageable p) {\n        return catalogService.search(q, p);\n    }\n\n    @GetMapping(\"/lineage/{id}\")\n    public LineageGraph getLineage(@PathVariable String id) {\n        return lineageService.getLineage(id, Direction.UPSTREAM, 3);\n    }\n\n    @PostMapping(\"/policies/evaluate\")\n    public AccessDecision evaluate(@RequestBody AccessRequest r) {\n        return policyEngine.evaluate(r);\n    }\n\n    @GetMapping(\"/compliance/gdpr\")\n    public ComplianceReport gdprReport() {\n        return complianceService.generateReport(\"GDPR\");\n    }\n}\n```\n\n## Policy Engine\n```java\n@Component\npublic class PolicyEngine {\n    public AccessDecision evaluate(AccessRequest request) {\n        List<Policy> policies = policyRepo.findByResourceAndActive(\n            request.getResource(), true);\n        for (Policy p : policies) {\n            if (!p.isAllow()) return AccessDecision.deny(\"Denied: \" + p.getName());\n        }\n        DataAsset asset = catalogService.getAsset(request.getResource());\n        if (asset.getClassification() == Classification.PII\n            && !userContext.hasRole(\"PII_ACCESS\")) {\n            return AccessDecision.deny(\"PII requires special role\");\n        }\n        return AccessDecision.allow();\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Define Domains**: Sales, Marketing, Finance\n2. **Set Up Catalog**: Apache Atlas, DataHub, or Amundsen\n3. **Configure Lineage**: OpenLineage Spark listener\n4. **Define Policies**: Access control rules\n5. **PII Detection**: Auto-classify sensitive data\n6. **Compliance**: GDPR/CCPA report generation",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **One-Time Project**: Set up catalog but never update\n2. **Too Restrictive**: Blocking all access (hurts productivity)\n3. **Ignoring Business Metadata**: Technical only, no context\n4. **No Automated Enforcement**: Manual review bottlenecks",
    "DEBUGGING.md": "# Debugging\n\n## Missing Catalog Entries\nCheck auto-discovery scheduler is running.\n\n## Broken Lineage\nVerify OpenLineage Spark listener is configured:\n```java\nspark.conf().set(\"spark.extraListeners\",\n    \"io.openlineage.spark.agent.OpenLineageSparkListener\");\n```\n\n## Policy Not Working\n```java\nAccessDecision result = policyEngine.evaluate(\n    AccessRequest.builder().user(\"test\").resource(\"finance\").build());\n```",
    "PERFORMANCE.md": "# Performance\n\n## Indexing\n```java\n@Table(name = \"data_assets\", indexes = {\n    @Index(name = \"idx_name\", columnList = \"name\"),\n    @Index(name = \"idx_domain\", columnList = \"domain\"),\n})\n```\n\n## Caching\n```java\n@Cacheable(value = \"lineage\")\npublic LineageGraph getLineage(String id, Direction dir) { ... }\n\n@Cacheable(value = \"policies\")\npublic AccessDecision evaluate(AccessRequest r) { ... }\n```",
    "SECURITY.md": "# Security\n\n## RBAC\n```java\n@PreAuthorize(\"hasRole('GOVERNANCE_ADMIN')\")\npublic void createPolicy(Policy p) { }\n```\n\n## Data Masking\nMask PII fields in query results based on user role.\n\n## Audit Logging\n```java\n@Audited\npublic DataAsset registerAsset(DataAsset asset) { ... }\n```",
    "ARCHITECTURE.md": "# Architecture\n\n```\n[Governance Platform]\n  [Catalog] [Lineage] [Policy Engine] [Compliance]\n       |        |          |              |\n  [Metadata Storage: Postgres, Neo4j, Elasticsearch, Kafka]\n       |\n  [Collection: Spark Listeners, Kafka Connect, JDBC, APIs]\n```",
    "EXERCISES.md": "# Exercises\n\n1. Build data catalog with search functionality\n2. Implement lineage capture via OpenLineage\n3. Create policy engine for access control\n4. Build PII classifier for sensitive data\n5. Generate GDPR compliance report",
}.items():
    if w(os.path.join(d, fname), c): pass
print("Lab 12 done")

print("\nAll remaining labs generated!")
