#!/usr/bin/env python3
"""Content templates for labs 17-20."""
from gen_content_09_12 import make_docs

LABS = {}

# ===== LAB 17: REAL-TIME FEATURE STORE =====
l17 = {
    "title": "Real-Time Feature Store",
    "short": "Feature Store",
    "overview": "A feature store is a centralized repository for feature engineering, storage, and serving. It enables feature reuse, training-serving consistency, and point-in-time correct joins for ML models. This lab covers Feast, feature serving, online/offline stores, and point-in-time joins.",
    "concepts": [
        ("Feature Store", "Centralized platform for feature engineering, storage, discovery, and serving"),
        ("Online Store", "Low-latency feature serving for real-time inference (Redis, Cassandra)"),
        ("Offline Store", "Historical feature storage for training data generation (S3, BigQuery)"),
        ("Point-in-Time Join", "Correctly join features to labels using temporal alignment"),
        ("Feast", "Open-source feature store with online/offline stores and serving API"),
        ("Feature Serving", "REST/gRPC API for real-time feature retrieval during model inference"),
    ],
    "objectives": [
        "Understand feature store architecture (online, offline, registry)",
        "Deploy Feast feature store with Redis online store and BigQuery offline store",
        "Define feature views and feature services in Feast",
        "Implement point-in-time correct join for training data",
        "Serve features via REST API for real-time model inference",
        "Monitor feature freshness and consistency between online and offline stores",
    ],
    "exercises": [
        "Deploy Feast with Redis online store and file offline store",
        "Define feature views for user features (total_spent, avg_order_value, days_since_last)",
        "Materialize features to online store for low-latency serving",
        "Generate point-in-time correct training data using historical features",
        "Serve features via Python SDK and REST API",
        "Monitor online/offline feature consistency with validation jobs",
    ],
    "quiz_qa": [
        ("What does the online store provide?", ["Historical data", "Low-latency serving", "Training data", "Feature definitions"]),
        ("What problem does point-in-time join solve?", ["Duplicates", "Data leakage", "Missing values", "Slow queries"]),
        ("What is Feast?", ["ETL tool", "Feature store platform", "ML framework", "Database"]),
        ("Which is a common online store backend?", ["BigQuery", "Redis", "S3", "Spark"]),
        ("What is a feature view?", ["Dashboard", "Logical grouping of features", "Database view", "ML model"]),
    ],
    "quiz_answers": ["B", "B", "B", "B", "B"],
    "flashcards": [
        ("What is a feature store?", "Centralized repository for feature engineering, storage, discovery, and serving for ML"),
        ("What is the difference between online and offline store?", "Online: low-latency for inference (Redis). Offline: historical for training (S3, BigQuery)."),
        ("What is a point-in-time join?", "Join that uses timestamps to ensure features don't use future data relative to labels"),
        ("What is Feast?", "Open-source feature store by Tecton with Python SDK, online/offline stores, and serving API"),
        ("What is feature materialization?", "Computing features from source data and writing to online store for low-latency serving"),
    ],
    "interview": [
        ("Architecture", "Explain feature store architecture.", "Registry: feature definitions and metadata. Offline store: historical features for training. Online store: low-latency features for inference. Serving API: retrieve features by entity key. All three are kept consistent."),
        ("Point-in-Time", "Why is point-in-time join important?", "Prevents data leakage by ensuring features use only information available at prediction time. Without it, features from the future would leak into training, creating overly optimistic model performance."),
        ("Serving", "How do you serve features for real-time inference?", "Materialize features to online store (Redis, Cassandra). Inference service calls feature store REST/gRPC API with entity keys. Feature values returned in <10ms for real-time predictions."),
        ("Consistency", "How to ensure online/offline consistency?", "Validation jobs compare online and offline feature values for sample entities. Monitor materialization latency. Alert on drift between online and offline distributions."),
    ],
    "reflection": [
        "Feature stores eliminate duplicate feature engineering across teams",
        "Point-in-time correctness is the most critical and most misunderstood aspect",
        "Online/offline consistency requires careful materialization pipeline management",
        "Feast provides excellent abstractions but requires infrastructure investment",
        "Start with batch features; add streaming features as real-time requirements grow",
    ],
    "references": [
        "Feast: https://feast.dev/",
        "Feast Docs: https://docs.feast.dev/",
        "Point-in-Time Joins: https://docs.feast.dev/getting-started/concepts/point-in-time-joins",
        "Tecton: https://www.tecton.ai/",
        "Feature Store Summit: https://www.featurestore.org/",
    ],
    "history": [
        ("2017", "Uber open-sources Michelangelo (includes feature store concepts)"),
        ("2018", "Tecton founded; Feast project started"),
        ("2019", "Feast v0.1: first open-source feature store"),
        ("2020", "Feast v0.5: stable API, Redis online store"),
        ("2021", "Feast v0.10: improved performance, multi-store support"),
        ("2022", "Feast v0.20: stream feature support, Java SDK"),
        ("2023", "Feast v0.30: improved registry, offline store plugins"),
        ("2024", "Feast v0.35: enhanced streaming, AWS/GCP integrations"),
    ],
    "mental_models": [
        ("The Library", "Feature store is a library. Feature definitions = catalog cards. Offline store = archives. Online store = reference desk (quick lookup). Librarian (serving API) fetches books (features) by call number (entity ID)."),
        ("The Recipe Book", "Features are ingredients. Feature recipes = transformations. Training = cooking one big batch. Serving = cooking individual portions. Same recipe must produce same ingredient for training and serving."),
        ("The Time Machine", "Point-in-time join is a time machine. When you generate training labels (event at time T), the time machine ensures you only see features from before time T. No peeking into the future!"),
    ],
    "theory_sections": [
        ("Feature Store Architecture", "Registry: stores feature definitions, metadata, and lineage. Offline Store: historical feature values for training data generation (S3, BigQuery, Snowflake). Online Store: low-latency feature serving (Redis, Cassandra, DynamoDB). Serving Layer: REST/gRPC API for real-time retrieval. Transformation Layer: compute features from source data (Spark, Flink)."),
        ("Point-in-Time Correctness", "When joining features to labels, each label timestamp must only use features computed from data available at or before that timestamp. Without point-in-time joins, training data leaks future information, causing models to appear more accurate than they will be in production. Implemented via AS OF join or temporal join (SQL: FOR SYSTEM_TIME AS OF)."),
        ("Feature Materialization", "Process of computing features from source data and writing to online store. Batch materialization: scheduled Spark/Airflow jobs compute features and push to online store. Streaming materialization: Flink/Kafka pipelines continuously update online store. Materialization must be monitored for freshness and consistency."),
        ("Training-Serving Skew", "Features computed during training must exactly match features computed during serving. Differences (skew) cause model degradation. Prevention: use same transformation code in both paths, validate distributions match, monitor online vs offline feature values."),
    ],
    "internals_sections": [
        ("Feast Architecture", "Feast Core (Registry): manages feature definitions, stores in PostgreSQL/MySQL. Feast Online Serving: FastAPI/gRPC server reading from online store. Feast Job Service: manages materialization jobs. Python SDK: user-facing API for defining features, generating training data, serving."),
        ("Registry and Metadata", "Feature Table: source + entities + features + batch source. Feature View: logical grouping of features with transformations. Feature Service: collection of feature views for serving. Data Source: batch or stream source for feature computation. Entity: join key (customer_id, user_id) with timestamp."),
        ("Online Store Operations", "Write path: materialization job computes features, writes to online store with upsert semantics. Read path: serving API receives entity keys, fetches feature values, returns in milliseconds. Backends: Redis (in-memory, fast), Cassandra (distributed, durable), DynamoDB (AWS managed). Redshift/BigQuery (analytical, slower)."),
        ("Offline Store Operations", "Storage: Parquet files in S3/GCS, or tables in BigQuery/Redshift. Retrieval: Feast generates point-in-time correct SQL/queries. Returns training dataset as DataFrame. Supports time-partitioned retrieval for incremental training data generation."),
    ],
    "math": [
        ("Serving Latency", "OnlineLatency = Network + CacheLookup + Deserialization\nP50 Target: <5ms\nP99 Target: <20ms"),
        ("Storage", "OnlineSize = Entities * FeaturesPerEntity * AvgFeatureSize\nOfflineSize = HistoricalEvents * Features * RetentionPeriod\nStorageCost = OnlineSize * CostPerGB + OfflineSize * CostPerGB"),
        ("Materialization", "MaterializationTime = EntitiesToUpdate * Features / Throughput\nFreshnessLag = CURRENT_TIME - LastMaterializedTime\nStalenessThreshold = configurable (e.g., 1 hour)"),
        ("Consistency", "ConsistencyScore = matching_feature_pairs / total_checked_pairs\nDrift = |online_distribution - offline_distribution|\nAlertThreshold = drift > 0.1 (KS statistic)"),
    ],
    "visual": "```\nFeature Store Architecture:\n[Source Data] -> [Feature Engineering] -> [Feature Store]\n    |                                     |          |\n[Transaction DB]                   [Online Store]  [Offline Store]\n[Customer DB]                      [Redis/Cass]   [S3/BigQuery]\n    |                                     |          |\n[Streaming: Kafka]              [Serving API: REST/gRPC]  [Training Data]\n                                        |               |\n                                 [ML Inference]    [Model Training]\n\nPoint-in-Time Join:\nLabel @ T1 -> Features BEFORE T1 (correct)\nLabel @ T1 + Feature @ T2 (T2 > T1) -> DATA LEAKAGE (wrong!)\n\nFeature Timeline:\nt0    t1    t2    t3    t4    t5\n[e1]  [e2]  [e3]  [e4]  [e5]\n  |            |\nFeature v1    Label L1\n  |            |\n  v            v\nCorrect: L1 uses v1 (v1 < L1)\nWrong:   L1 uses v3 (v3 > L1, future data)\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/seventeen/ for:\n- FeatureClient.java: Feature store serving client with caching\n- PointInTimeJoin.java: Temporal join implementation for training data\n\nKey patterns:\n```java\n// Feature serving\nFeatureClient client = new FeatureClient(\"http://localhost:6566\");\nMap<String, FeatureValue> features = client.getOnlineFeatures(\n    \"user_features\",\n    Map.of(\"user_id\", \"user_123\"),\n    List.of(\"total_orders\", \"avg_order_value\", \"days_since_last\")\n);\n\n// Point-in-time join (conceptual)\nDataset<Row> trainingData = pointInTimeJoin(\n    labels, features, \"user_id\", \"label_ts\", \"feature_ts\");\n```",
    "step_by_step": [
        "Install Feast: pip install feast",
        "Initialize project: feast init my_feature_repo",
        "Define entity: entity = Entity(name=\"user_id\", join_keys=[\"user_id\"])",
        "Define feature view with batch source and transformations",
        "Apply registry: feast apply (uploads definitions to registry)",
        "Materialize features to online store: feast materialize-incremental",
        "Generate training data: get_historical_features(entity_df, features)",
        "Serve features: feast serve (starts REST server)",
        "Test serving: curl http://localhost:6566/get-online-features",
        "Monitor materialization lag and online/offline consistency",
    ],
    "common_mistakes": [
        ("No Point-in-Time Join", "Joining features to labels without temporal alignment causes data leakage"),
        ("Training-Serving Skew", "Using different transformation code for training and serving"),
        ("Large Online Store", "Storing all features online when only recent values are needed; use TTL"),
        ("Slow Materialization", "Materializing full feature table every run instead of incremental"),
        ("No Validation", "Not validating online/offline consistency leads to silent serving failures"),
    ],
    "debugging": [
        ("Missing Features at Serving", "Check entity key exists in online store; verify materialization ran; check key format"),
        ("Slow Serving", "Optimize online store connection; use batch retrieval (multiple entities per request); cache frequently accessed features"),
        ("Inconsistent Results", "Compare online and offline values for same entity; check materialization freshness; verify transformation logic"),
        ("Point-in-Time Errors", "Verify label and feature timestamps; check for null timestamps; validate join condition"),
    ],
    "refactoring": "## Ad-hoc to Feature Store\nBefore: Individual feature computation in each notebook\nAfter: Centralized feature store with shared definitions\n\n## Batch to Real-Time\nBefore: Daily feature batch to online store\nAfter: Streaming feature computation with Kafka -> Flink -> Online Store\n\n## Validation Automation\nBefore: Manual validation of feature values\nAfter: Automated online/offline consistency checks with alerting",
    "performance": [
        ("Online Store Optimization", "Redis cluster with pipelining for batch reads. Feature TTL to manage memory. Connection pooling for serving API."),
        ("Materialization", "Incremental materialization (only new/changed entities). Parallel materialization for independent feature views."),
        ("Training Data Generation", "Partition pruning by time range. Column selection (only needed features). Caching of intermediate feature tables."),
        ("Serving API", "Batch entity retrieval (100+ entities per request). Feature value caching with TTL. gRPC for lower latency than REST."),
    ],
    "security": "## Access Control\n- Feature-level access (some features are PII-sensitive)\n- Entity-level access (user A can't query user B's features)\n- API authentication (API keys, OAuth)\n\n## Privacy\n- PII masking in feature values\n- Differential privacy for aggregate features\n- Audit logging of all feature retrievals\n\n## Infrastructure\n- TLS for serving API\n- Network isolation for online store\n- Encryption at rest for offline store",
    "architecture": "```\n[Feature Engineering]\n    |\n[Feast Registry] -> [PostgreSQL/MySQL]\n    |\n[Offline Store: S3/BigQuery]    [Online Store: Redis/Cassandra]\n    |                                    |\n[Training Data Generation]       [Feature Serving API]\n    |                                    |\n[Model Training]                 [Real-Time Inference]\n```",
    "how_it_works": "1. Users define feature views in Python using Feast SDK\n2. Registry stores feature definitions and metadata\n3. Feature engineering jobs compute features from source data (Spark, Flink)\n4. Batch features stored in offline store (S3, BigQuery) for training\n5. Materialization jobs push latest feature values to online store\n6. Model training: get_historical_features() generates point-in-time correct training data\n7. Model inference: get_online_features() retrieves features by entity key in real-time\n8. Consistency validation jobs compare online vs offline feature values",
    "why_exists": "ML teams waste 60-80% of their time on feature engineering. Features are duplicated across teams. Training and serving use different code, causing skew. Point-in-time correctness is complex and frequently wrong. Feature stores solve these problems through centralized, versioned, and validated feature infrastructure.",
    "why_matters": "- **Productivity**: Reuse features across teams; reduce duplicate engineering\n- **Correctness**: Point-in-time joins prevent data leakage in training\n- **Consistency**: Same feature code for training and serving\n- **Speed**: Low-latency serving for real-time ML models\n- **Governance**: Feature discovery, lineage, versioning, and ownership\n- **Scale**: Proven at Uber, Airbnb, Netflix, and Tecton customers",
    "package": "com.dataeng.seventeen",
    "JavaSources": {},
    "Tests": {},
}
LABS["17-real-time-feature-store"] = l17

# ===== LAB 18: DATA OBSERVABILITY =====
l18 = {
    "title": "Data Observability",
    "short": "Data Observability",
    "overview": "Data observability is the practice of monitoring, understanding, and troubleshooting data health across the data lifecycle. It provides data lineage, profiling, anomaly detection, and monitoring tools to ensure data reliability. This lab covers Monte Carlo, Soda, data profiling, and anomaly detection techniques.",
    "concepts": [
        ("Data Observability", "End-to-end monitoring of data health across pipelines, warehouses, and lakes"),
        ("Data Lineage", "Tracking data origin, transformations, and dependencies end-to-end"),
        ("Data Profiling", "Analyzing data characteristics: distributions, patterns, quality metrics"),
        ("Anomaly Detection", "Identifying unusual patterns: volume spikes, freshness delays, distribution shifts"),
        ("Monte Carlo", "Data observability platform for real-time monitoring and incident management"),
        ("Soda", "Open-source data quality and observability tool with SQL-based checks"),
    ],
    "objectives": [
        "Understand the five pillars of data observability",
        "Implement data profiling for automated statistical analysis",
        "Build anomaly detection for volume, freshness, and distribution changes",
        "Use Soda for open-source data observability checks",
        "Create data health dashboards and incident management workflows",
        "Implement data lineage tracking for impact analysis",
    ],
    "exercises": [
        "Set up Soda Core and configure data source connections",
        "Write Soda checks for freshness, volume, schema, and custom SQL",
        "Implement anomaly detection for row count and distribution changes",
        "Build data profiling pipeline (histograms, null rates, distinct counts)",
        "Create observability dashboards with trend charts and alerts",
        "Design incident response workflow for data quality incidents",
    ],
    "quiz_qa": [
        ("What are the pillars of data observability?", ["3", "4", "5", "6"]),
        ("What does Soda Core provide?", ["Data storage", "Open-source quality checks", "ML platform", "Data catalog"]),
        ("What is data freshness?", ["How recent data is", "How fast queries run", "Data quality score", "Storage efficiency"]),
        ("What is Monte Carlo?", ["ETL tool", "Data observability platform", "Database", "ML framework"]),
        ("What is data lineage used for?", ["Faster queries", "Impact analysis of changes", "Data storage", "Compression"]),
    ],
    "quiz_answers": ["C", "B", "A", "B", "B"],
    "flashcards": [
        ("What are the 5 pillars of data observability?", "Freshness (recency), Distribution (statistical), Volume (completeness), Schema (structure), Lineage (dependencies)"),
        ("What is Soda?", "Open-source data observability tool with SQL-based checks for freshness, volume, schema, and custom rules"),
        ("What is anomaly detection in data?", "Identifying patterns: volume spikes, freshness delays, distribution shifts, schema changes that deviate from historical norms"),
        ("What is data profiling?", "Automated statistical analysis: row counts, null rates, distinct counts, min/max, distribution shapes, patterns"),
        ("What is data incident management?", "Process: detect anomaly -> classify severity -> notify owner -> investigate -> resolve -> prevent recurrence"),
    ],
    "interview": [
        ("Observability", "What are the 5 pillars of data observability?", "Freshness (how recent?), Distribution (how similar to expected?), Volume (how complete?), Schema (how structured?), Lineage (how derived?)"),
        ("Anomaly Detection", "How do you detect data volume anomalies?", "Compare to historical window (7/30/90 day moving average). Z-score or IQR-based outlier detection. Adjust for seasonality (day-of-week, month-end)."),
        ("Lineage", "Why is data lineage important for observability?", "Impact analysis: if source table changes, which dashboards break? Root cause: if dashboard is wrong, which upstream stage caused it? Governance: track data flow for compliance."),
        ("Soda vs Monte Carlo", "Compare Soda and Monte Carlo.", "Soda: open-source, SQL-based checks, self-hosted, flexible. Monte Carlo: SaaS, ML-based anomaly detection, automatic lineage, managed incident workflows. Soda for control and cost, Monte Carlo for automated detection."),
    ],
    "reflection": [
        "Observability shifts data quality from reactive (fix after failure) to proactive (detect before impact)",
        "Anomaly detection is most valuable for unknown unknowns — issues you didn't think to check",
        "Data lineage is essential for both root cause analysis and impact assessment",
        "Start with the 5 pillars and expand coverage iteratively",
        "Alert fatigue is a real risk; tune thresholds and severity levels carefully",
    ],
    "references": [
        "Monte Carlo: https://www.montecarlodata.com/",
        "Soda: https://www.soda.io/",
        "5 Pillars of Data Observability: https://www.montecarlodata.com/blog-the-5-pillars-of-data-observability/",
        "Great Expectations: https://greatexpectations.io/",
        "Datafold: https://www.datafold.com/",
    ],
    "history": [
        ("2019", "Monte Carlo founded by Barr Moses (former WeWork data lead)"),
        ("2020", "Soda open-sourced by Tom Baeyens and friends"),
        ("2020", "Data observability concept formalized by Monte Carlo (5 pillars)"),
        ("2021", "Widespread adoption of data observability tools"),
        ("2022", "Soda raises Series B; Monte Carlo reaches unicorn status"),
        ("2023", "Open-source alternatives grow; Soda Core gains momentum"),
        ("2024", "AI-powered anomaly detection; observability for streaming data"),
    ],
    "mental_models": [
        ("The Car Dashboard", "Data observability = car dashboard. Freshness = speedometer. Volume = fuel gauge. Distribution = check engine light. Schema = warning lights. Lineage = GPS tracking route."),
        ("The Health Monitor", "Data observability is like a hospital patient monitor. Vital signs (metrics) stream continuously. Alarms (alerting) trigger when readings exceed thresholds. Trend charts show improvement or deterioration over time."),
        ("The Security Camera", "Data observability = security cameras for your data platform. Lineage = camera recording showing data flow. Profiling = periodic snapshots. Anomaly detection = motion detection alerting on unusual activity."),
    ],
    "theory_sections": [
        ("Five Pillars of Data Observability", "Freshness: how up-to-date is the data (lag between event and availability). Distribution: are data values within expected statistical ranges. Volume: is all expected data present (row count expectations). Schema: has the structure changed without notice. Lineage: how is data produced and consumed."),
        ("Anomaly Detection Techniques", "Static thresholds: row count > 1M. Moving average: compare to 7/30/90 day window. Z-score: |value - mean| / stddev > 3. IQR: value outside Q1-1.5*IQR or Q3+1.5*IQR. Seasonality: compare to same day last week, last month, last year. ML-based: isolation forest, LSTM for time series."),
        ("Data Profiling", "Column-level: null count, distinct count, min/max, mean/stddev, value distribution (histogram). Table-level: row count, size, partition count, timestamp range. Cross-column: correlation, functional dependencies, foreign key violations. Profiling runs on schedule and compares to historical baselines."),
        ("Incident Lifecycle", "1. Detection: check fails or anomaly triggered. 2. Classification: severity (critical, high, medium, low). 3. Notification: email, Slack, PagerDuty. 4. Investigation: use lineage for root cause. 5. Resolution: fix pipeline, backfill data. 6. Post-mortem: prevent recurrence. 7. Documentation: update runbooks."),
    ],
    "internals_sections": [
        ("Soda Architecture", "Soda Core: Python library for executing checks. Soda SQL: command-line for SQL-based validation. Soda Cloud: managed dashboard and alerting. Checks: SQL queries returning measurement values. Metrics: numerical results of checks. Alerts: threshold violations."),
        ("Monte Carlo Architecture", "Agent: deploys in customer environment (reads metadata, profiles data). Backend: ML-based anomaly detection models. Dashboard: observability UI with health scores. Teams: integration with PagerDuty, Slack, Jira. Lineage: automatic capture from query logs."),
        ("Profiling Pipeline", "1. Extract sample (deterministic or random). 2. Compute statistics (summary + distribution). 3. Compare to historical baseline. 4. Store results in metrics database. 5. Update dashboards. 6. Trigger alerts on anomalies. 7. Retain history for trend analysis."),
        ("Lineage Capture", "SQL parsing: extract table/column dependencies from query text. Snowflake/Presto query history: analyze execution logs. ETL tool metadata: import lineage from dbt, Airflow, Spark. Manual annotation: document external ingestion. Graph storage: Neo4j, custom DAG store with indexing for impact analysis."),
    ],
    "math": [
        ("Anomaly Detection", "ZScore = (value - mean) / stddev\nOutlier = |Z| > 3 (strict) or |Z| > 2 (sensitive)\nIQR = Q3 - Q1\nOutlier: x < Q1 - 1.5*IQR or x > Q3 + 1.5*IQR"),
        ("Freshness", "Freshness_Lag = CURRENT_TIMESTAMP - MAX(update_timestamp)\nSLA_Breach = Freshness_Lag > SLA_Threshold\nHistorical_P50 = PERCENTILE(freshness_lags, 0.5)\nHistorical_P95 = PERCENTILE(freshness_lags, 0.95)"),
        ("Volume Monitoring", "Expected = EMA(historical_volumes) or same_day_last_week\nDeviation = (Actual - Expected) / Expected\nAlert_Threshold = |Deviation| > 0.5 (50% change)\nSeasonal = Expected * day_of_week_factor * hour_factor"),
        ("Distribution Comparison", "KS_Stat = max(|CDF_Actual(x) - CDF_Expected(x)|)\nDrift_Threshold = 0.1 (significant)\nJensen_Shannon = SQRT(mean divergence)\nEarth_Movers = Wasserstein distance between distributions"),
    ],
    "visual": "```\nObservability Dashboard:\nData Health Score: 92/100\n\nFreshness: \\\\[========= ] 92% (avg lag: 12 min)\nVolume:    \\\\[==========] 99% (within expected range)\nSchema:    \\\\[==========] 100% (no changes detected)\n\nLineage View:\n[Source API] -> [Kafka] -> [Flink Job] -> [Snowflake] -> [Dashboard]\n                                   |                     |\n                              [Alert: lag spike]    [Impacted]\n\nAnomaly Timeline:\nVolume:  ----####----++++----####----\n        Normal   Spike  Drop   Spike\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/eighteen/ for:\n- AnomalyDetector.java: Volume, freshness, and distribution anomaly detection\n- DataProfiler.java: Automated profiling with statistical analysis\n\nKey patterns:\n```java\n// Anomaly detection\nAnomalyDetector detector = new AnomalyDetector();\nVolumeAnomaly anomaly = detector.detectVolumeAnomaly(\n    currentRowCount, historicalRowCounts);\nif (anomaly.isAnomaly()) {\n    alertService.sendAlert(anomaly);\n}\n\n// Data profiling\nDataProfiler profiler = new DataProfiler();\nProfileResult result = profiler.profile(dataset);\nSystem.out.println(\"Null rate: \" + result.getNullRate());\nSystem.out.println(\"Distinct rate: \" + result.getDistinctRate());\n```",
    "step_by_step": [
        "Install Soda Core: pip install soda-core-snowflake (or your warehouse)",
        "Create configuration: YAML file with connection details",
        "Write checks: YAML checks for freshness, volume, schema, custom SQL",
        "Run scan: soda scan -d my_datasource checks.yml",
        "Review output: check results in terminal output",
        "Set up automated scans in Airflow or cron",
        "Integrate with Slack for alerts on failed checks",
        "Build observability dashboard (Grafana, Superset)",
        "Configure anomaly detection with moving averages",
        "Set up data profiling pipeline and trend monitoring",
    ],
    "common_mistakes": [
        ("Too Many Alerts", "Every failed check triggers alert; aggregate by severity and use escalation policies"),
        ("No Baselines", "Anomaly detection requires historical baselines; start collecting immediately"),
        ("Ignoring Schema Drift", "Only monitoring volume/freshness; schema changes silently break downstream"),
        ("Manual Lineage", "Relying on manual documentation; automated capture is more reliable and current"),
        ("No Incident Response", "Detecting issues without defined process; incidents should have clear ownership and SLA"),
    ],
    "debugging": [
        ("Freshness Alert False Positive", "Check if system clock is correct; pipeline may have legitimate delay (upstream issue)"),
        ("Volume Anomaly False Positive", "Check for double-counting; upstream deduplication may have changed; holiday/weekend pattern"),
        ("Distribution Drift", "Drift may be legitimate (business change, new segment); verify before escalating"),
        ("Soda Scan Failure", "Check connection credentials, warehouse availability, SQL syntax in checks"),
    ],
    "refactoring": "## Reactive to Proactive\nBefore: Users report data issues -> investigate\nAfter: Automated detection -> alert before users notice\n\n## Manual to Automated\nBefore: Manual SQL queries for validation\nAfter: Automated Soda checks in CI/CD pipeline\n\n## Siloed to Centralized\nBefore: Each team monitors their own data\nAfter: Centralized observability platform with shared alerts and dashboards",
    "performance": [
        ("Profiling Performance", "Sample for large tables (0.1-1%). Approximate counts (HyperLogLog). Incremental profiling (only changed partitions)."),
        ("Anomaly Detection", "Use window functions for historical computation. Pre-compute baseline statistics. Cache profiles for non-changing data."),
        ("Lineage Processing", "Batch lineage queries for efficiency. Incremental graph updates. Index lineage queries for impact analysis."),
        ("Alert Throttling", "Deduplicate alerts (same table, same check, consecutive failures). Cooldown period between alerts. Escalate only for persistent or high-severity issues."),
    ],
    "security": "## Data Privacy\n- Profiling on masked/sampled data for PII protection\n- Alert information should not contain actual data values\n- Role-based access to observability dashboards\n\n## Access Control\n- Read-only access for monitoring tools\n- Separate credentials from production systems\n- Audit logging of all observability checks\n\n## Compliance\n- Retention of observability history for audits\n- Data lineage for regulatory traceability\n- Quality metrics for data governance reporting",
    "architecture": "```\n[Data Sources: DB, Lake, Warehouse, Stream]\n                    |\n[Observability Agents: Collectors, Profilers, Parsers]\n    |                 |                  |\n[Freshness]    [Volume/Profiling]    [Lineage Capture]\n    |                 |                  |\n[Alerting] <--- [Anomaly Detection] ---> [Metrics DB]\n    |                                    |\n[PagerDuty/Slack]              [Dashboard/Grafana]\n```",
    "how_it_works": "1. Observability agents collect metadata: table sizes, update timestamps, schemas\n2. Data profilers sample data and compute statistics (null rates, distributions)\n3. Lineage parsers analyze SQL logs to build dependency graph\n4. Anomaly detection compares current metrics against historical baselines\n5. Violations trigger alerts based on severity and thresholds\n6. Incident management workflows notify owners and track resolution\n7. Dashboards provide real-time health scores and trend charts\n8. Metrics stored for historical analysis and compliance\n9. Root cause analysis uses lineage graph to trace upstream issues",
    "why_exists": "Data pipelines fail silently. Tables stop updating, schemas change unexpectedly, data volumes drop or spike. These issues propagate downstream, breaking dashboards, ML models, and reports. Traditional monitoring (infrastructure metrics) doesn't capture data-level issues. Data observability fills this gap by monitoring the actual data content and behavior.",
    "why_matters": "- **Proactive Detection**: Find issues before users report them\n- **Root Cause Analysis**: Trace failures through lineage to find origin\n- **Reduced MTTR**: Faster incident detection and resolution\n- **Data Trust**: Health scores and quality metrics build user confidence\n- **Cost Efficiency**: Catch expensive pipeline failures early\n- **Compliance**: Demonstrate data quality and lineage for regulations",
    "package": "com.dataeng.eighteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["18-data-observability"] = l18

# ===== LAB 19: DATA GOVERNANCE =====
l19 = {
    "title": "Data Governance",
    "short": "Data Governance",
    "overview": "Data governance defines policies, processes, and technologies for managing data assets. This lab covers RBAC for data, PII detection and masking, data classification, GDPR/compliance frameworks, data retention, and audit logging for enterprise data platforms.",
    "concepts": [
        ("Data Governance", "Framework of policies, processes, and controls for data management"),
        ("RBAC", "Role-Based Access Control for granular data permissions"),
        ("PII Detection", "Automated identification of personally identifiable information"),
        ("Data Masking", "Protecting sensitive data through obfuscation techniques"),
        ("GDPR/Compliance", "Regulatory frameworks for data privacy and protection"),
        ("Data Retention", "Lifecycle policies for data storage and deletion"),
    ],
    "objectives": [
        "Design and implement RBAC for data platform access control",
        "Build automated PII detection using patterns and classifiers",
        "Implement data masking strategies (static, dynamic, on-the-fly)",
        "Apply GDPR compliance requirements to data pipelines",
        "Establish data retention and deletion policies",
        "Set up audit logging for data access and governance operations",
    ],
    "exercises": [
        "Design RBAC model with roles, permissions, and inheritance hierarchy",
        "Implement PII scanner using regex and ML-based classifiers",
        "Apply dynamic data masking based on user roles",
        "Create GDPR compliance checklist and implement right-to-deletion",
        "Set up data retention policies with automated lifecycle management",
        "Build audit log pipeline for tracking data access events",
    ],
    "quiz_qa": [
        ("What does RBAC stand for?", ["Rule-Based Access", "Role-Based Access Control", "Resource-Based Auth", "Random Access"]),
        ("What PII detection method uses patterns?", ["Machine learning", "Regular expressions", "Graph analysis", "Statistics"]),
        ("Which regulation is about EU data privacy?", ["CCPA", "HIPAA", "GDPR", "SOX"]),
        ("What is dynamic data masking?", ["Permanent modification", "On-the-fly obfuscation", "Data deletion", "Data encryption"]),
        ("What does data retention policy define?", ["How long data is kept", "Who can access data", "Data quality rules", "Backup frequency"]),
    ],
    "quiz_answers": ["B", "B", "C", "B", "A"],
    "flashcards": [
        ("What is data governance?", "Framework of policies, processes, and technologies for managing data availability, usability, integrity, and security"),
        ("What is RBAC?", "Role-Based Access Control: permissions assigned to roles, users assigned to roles, role hierarchy for inheritance"),
        ("What is PII?", "Personally Identifiable Information (name, SSN, email, phone, address) that can identify an individual"),
        ("What is data masking?", "Techniques to obfuscate sensitive data: substitution, shuffling, nulling, encryption, format-preserving masking"),
        ("What is GDPR?", "EU General Data Protection Regulation: right to access, rectification, erasure, portability, and restriction of processing"),
    ],
    "interview": [
        ("Governance", "What are the key components of data governance?", "Policies: rules and standards. Processes: how policies are enforced. Roles: data owners, stewards, custodians. Technology: RBAC, masking, audit, catalog. Metrics: compliance rate, coverage, incidents."),
        ("RBAC", "How would you design RBAC for a data platform?", "Roles: Admin (full access), DataEngineer (read/write), DataAnalyst (read-only), DataConsumer (limited). Groups: org hierarchy. Row-level: department filters. Column-level: masking for sensitive columns."),
        ("GDPR", "How do you implement GDPR right-to-erasure?", "1. Identify all locations of user data (DB tables, S3 files, logs). 2. Anonymize or delete records. 3. Verify deletion via count checks. 4. Enforce retention of deletion confirmation. 5. Automate via data platform's lifecycle management."),
        ("PII Detection", "How do you find PII in a data platform?", "Column name scanning (email, ssn, phone). Pattern matching (regex for emails, credit cards). ML classification (NLP models). Data sampling and inspection. Schema registry with sensitivity tags."),
    ],
    "reflection": [
        "Data governance requires both technology and organizational commitment",
        "PII detection at scale is harder than it seems — context matters (is 'zip code' PII? sometimes)",
        "RBAC must balance security with usability; overly restrictive models cause workarounds",
        "GDPR compliance is an ongoing process, not a one-time project",
        "Automation is essential for governance at scale; manual processes don't scale",
    ],
    "references": [
        "GDPR: https://gdpr.eu/",
        "CCPA: https://oag.ca.gov/privacy/ccpa",
        "NIST Data Governance: https://www.nist.gov/data-governance",
        "Apache Ranger: https://ranger.apache.org/",
        "Apache Atlas: https://atlas.apache.org/",
    ],
    "history": [
        ("1970s", "Data administration emerges as formal discipline"),
        ("1990s", "Data governance frameworks (DGI, CMMI)"),
        ("2000s", "Sarbanes-Oxley (SOX) drives governance technology"),
        ("2014", "EU Data Protection Regulation drafted (GDPR precursor)"),
        ("2018", "GDPR goes into effect; major compliance push"),
        ("2020", "CCPA in California; global privacy regulation wave"),
        ("2023", "AI governance emerges; data governance for ML/AI pipelines"),
        ("2024", "Automated governance; AI-driven policy enforcement"),
    ],
    "mental_models": [
        ("The Constitution", "Data governance is like a constitution: sets the rules (policies), defines branches (roles), establishes rights (data privacy), and provides enforcement mechanisms (audit, penalties)."),
        ("The City Planning", "Data platform is a city. Governance = zoning laws. RBAC = building access. Masking = window blinds. PII detection = police identifying unsafe buildings. Audit = security cameras."),
        ("The Bank Vault", "Data governance is bank security. Vault = encrypted data. Access cards = RBAC. Security cameras = audit logs. Bank manager = data owner. Customers = data subjects with rights."),
    ],
    "theory_sections": [
        ("Governance Framework Components", "Policies: data classification, access control, retention, quality, privacy. Processes: approval workflows, incident response, compliance reviews. Roles: data owner (accountable), data steward (day-to-day management), data custodian (technical implementation), data consumer (user with access). Technology: access control, masking, audit, catalog."),
        ("RBAC Design Patterns", "Flat RBAC: user -> roles -> permissions (simple). Hierarchical RBAC: roles inherit from parent roles (organization hierarchy). Constrained RBAC: separation of duties (can't be in conflicting roles). Row-level: filter rows based on user attributes. Column-level: mask columns based on role sensitivity."),
        ("PII Detection Methods", "Pattern-based: regex for emails, phones, SSN, credit cards. Column name: keywords in column names (email, ssn, password). Sampling: read data samples and classify values. ML: NLP models trained on labeled PII data. Third-party APIs: specialized PII detection services."),
        ("Data Masking Types", "Static masking: permanently modify data in staging environments. Dynamic masking: obfuscate on-the-fly during query (user's role determines view). Deterministic: same input produces same masked output (for joins). Format-preserving: masked values look like original format. Encryption: reversible masking for authorized re-identification."),
    ],
    "internals_sections": [
        ("PII Scanner Pipeline", "1. Scan catalog for tables/columns. 2. Apply column-name patterns (keyword list). 3. Read data sample (N rows). 4. Apply regex patterns to values. 5. Calculate confidence score. 6. Flag potential PII columns. 7. Route for human review. 8. Update metadata catalog with sensitivity tags."),
        ("Dynamic Masking Implementation", "Query intercept: proxy modifies SQL before execution. View-based: pre-defined views with masking per role. Policy engine: evaluate user's role + sensitivity of requested data. Apply masking function: substitute, null, encrypt. Return masked results transparently to user."),
        ("GDPR Compliance Pipeline", "Right to access: search all data stores for user record -> compile report. Right to erasure: locate all copies -> delete or anonymize -> confirm deletion -> retain deletion log. Right to portability: export data in machine-readable format. Data Protection Impact Assessment (DPIA): automated scanner for high-risk processing."),
        ("Audit Log System", "Capture: query events, access attempts, permission changes, data modifications. Store: immutable log (S3, Kafka). Index: for search and analysis. Retain: per compliance requirements (GDPR: 3 years, SOX: 7 years). Alert: on security-critical events (unusual access patterns, permission escalation)."),
    ],
    "math": [
        ("PII Coverage", "PII_Coverage = IdentifiedPII / TotalPII * 100\nConfidence = Average(confidence_score) across all columns\nFalsePositiveRate = FalsePositives / TotalAlerts"),
        ("Access Control", "EffectivePermissions = permissions_granted + inherited_permissions - restrictions\nLeastPrivilegeScore = actual_permissions / required_permissions\nGoal: Minimize LeastPrivilegeScore while maintaining functionality"),
        ("Compliance", "ComplianceRate = CompliantAssets / TotalAssets * 100\nAuditCoverage = AuditedData / TotalData * 100\nRiskScore = Sensitivity * (1 - ComplianceRate) * ExposureFactor"),
        ("Retention", "StorageUsed = SUM(data_by_age_bucket)\nRetentionSavings = DataBeyondRetention * CostPerGB\nDeletionImpact = DataDeletionRequests * AvgCostPerRequest"),
    ],
    "visual": "```\nRBAC Model:\n[Admin] -> [Data Engineer] -> [Data Analyst] -> [Data Consumer]\n    |             |                  |                |\n[Full Access] [Read/Write]     [Read Only]      [Limited]\n                                    |\n                              [Column Masking]\n                              email: ***@***.com\n                              ssn: ***-**-1234\n\nPII Detection Pipeline:\n[Column Names] -> [Pattern Matching] -> [Value Sampling] -> [Classification]\n                                                              |\n                                                    [Confidence Score]\n                                                    [Sensitivity Tag]\n\nGDPR Workflow:\nSubject Request -> Identity Verification -> Search Data Stores\n                    -> Process Request (access/erase/port)\n                    -> Confirm Completion -> Log for Audit\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/nineteen/ for:\n- PiiDetector.java: Automated PII detection using patterns and classifiers\n- DataMasker.java: Dynamic masking with format preservation\n\nKey patterns:\n```java\n// PII detection\nPiiDetector detector = new PiiDetector();\nPiiResult result = detector.analyzeColumn(\"email\", sampleValues);\nSystem.out.println(\"PII type: \" + result.getPiiType() +\n    \", confidence: \" + result.getConfidence());\n\n// Dynamic masking\nDataMasker masker = new DataMasker();\nString masked = masker.mask(\"john@example.com\", MaskingType.EMAIL);\n// Result: j***@example.com\n```",
    "step_by_step": [
        "Define data classification policy: Public, Internal, Confidential, Restricted",
        "Implement RBAC: create roles, assign permissions, set up hierarchy",
        "Build PII scanner: regex patterns, column name analysis, sampling",
        "Tag sensitive columns in metadata catalog with classification levels",
        "Implement dynamic masking for sensitive columns in query engine",
        "Set up GDPR compliance workflows: access, erase, portability",
        "Configure data retention policies per classification level",
        "Build audit log pipeline for data access tracking",
        "Set up governance dashboards with compliance metrics",
        "Establish data ownership and stewardship roles",
    ],
    "common_mistakes": [
        ("Over-Classification", "Classifying all data as 'Confidential' dilutes focus; be specific about what needs protection"),
        ("RBAC Sprawl", "Creating too many roles creates management overhead; keep role hierarchy simple"),
        ("Masking Without Testing", "Masking breaks joins if not deterministic; test masking in downstream consumers"),
        ("One-Time Compliance", "Treating GDPR as one-time project; it requires ongoing process and monitoring"),
        ("No Enforcement", "Having policies without technical enforcement; policies must be implemented in code"),
    ],
    "debugging": [
        ("PII Missed", "Check if column naming differs from expected patterns; sample size may be too small; update regex patterns"),
        ("Masking Performance", "Dynamic masking adds query latency; consider view-based masking for frequently accessed data"),
        ("RBAC Access Issues", "Users can't access legitimate data for their role; check role membership, inheritance, row filters"),
        ("GDPR Erasure Failures", "Data may exist in unexpected locations (logs, cache, backups); expand search scope"),
    ],
    "refactoring": "## Manual to Automated PII Detection\nBefore: Manual review of schemas for sensitive data\nAfter: Automated PII scanner with confidence scoring\n\n## Static to Dynamic Masking\nBefore: Masking at ETL stage (permanent)\nAfter: Dynamic masking based on user role (flexible)\n\n## Siloed to Centralized Governance\nBefore: Each team manages own access policies\nAfter: Centralized RBAC with consistent policies across platform",
    "performance": [
        ("PII Scanning", "Sample-based scanning for large tables; parallel scanning across partitions; incremental scanning (only new columns)"),
        ("Masking", "Pre-compute masked views for frequent access patterns; cache masking rules per role; optimize masking UDFs"),
        ("Audit Logging", "Async audit log writes (non-blocking); batch log aggregation; partition logs by date for efficient querying"),
        ("RBAC Evaluation", "Cache resolved permissions per user session; optimize role hierarchy traversal; index permission lookups"),
    ],
    "security": "## Core Security\n- Encryption at rest and in transit for all sensitive data\n- Key management for masking and encryption functions\n- Network isolation for governance infrastructure\n\n## Access Control\n- Strict access to governance tools (PII detection, masking config)\n- Separation of duties: data owner != security admin\n- Regular access reviews and remediation\n\n## Compliance\n- Audit trail of all governance actions\n- Breach notification procedures\n- Regular compliance assessments",
    "architecture": "```\n[Data Platform: Sources, Lake, Warehouse, Stream]\n                    |\n[Governance Layer]\n    |         |          |           |\n[RBAC]   [PII Detect] [Masking]  [Audit]\n    |         |          |           |\n[GDPR/Compliance Engine]\n                    |\n[Data Catalog + Metadata]\n                    |\n[Governance Dashboard]\n```",
    "how_it_works": "1. Data classification policy defines sensitivity levels (Public, Internal, Confidential, Restricted)\n2. RBAC maps user roles to permission levels with row and column granularity\n3. PII scanner continuously scans for sensitive data using patterns and ML\n4. Sensitive columns tagged in metadata catalog with classification\n5. Dynamic masking engine intercepts queries and masks based on user role\n6. Retention policies automatically expire data beyond lifecycle\n7. Audit pipeline logs all data access and governance operations\n8. GDPR workflows handle subject rights requests (access, erasure, portability)\n9. Governance dashboard tracks compliance metrics and risk scores",
    "why_exists": "Organizations collect massive amounts of data, much of it sensitive (PII, financial, health). Without governance: data breaches, regulatory fines, loss of customer trust, and inability to manage data as an asset. Regulations (GDPR, CCPA, HIPAA, SOX) mandate data protection. Governance provides the framework and technology to comply while enabling responsible data use.",
    "why_matters": "- **Compliance**: Meet regulatory requirements (GDPR, CCPA, HIPAA, SOX)\n- **Trust**: Protect customer data and maintain brand reputation\n- **Risk Reduction**: Minimize breach impact through least-privilege access\n- **Data Value**: Well-governed data is trusted and usable\n- **Operational Efficiency**: Automated policies reduce manual overhead\n- **Auditability**: Clear trails for compliance and incident investigation",
    "package": "com.dataeng.nineteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["19-data-governance"] = l19

# ===== LAB 20: STREAMING ANALYTICS =====
l20 = {
    "title": "Streaming Analytics",
    "short": "Streaming Analytics",
    "overview": "Streaming analytics enables real-time processing, analysis, and visualization of data as it arrives. This lab covers real-time dashboards, streaming SQL, Kinesis Analytics, Flink SQL, and the architecture for building real-time analytics applications.",
    "concepts": [
        ("Streaming Analytics", "Real-time data processing and analysis with sub-second latency"),
        ("Real-Time Dashboards", "Live updating visualizations of streaming data (Grafana, Superset)"),
        ("Streaming SQL", "SQL-based querying of streaming data (Flink SQL, Kinesis Analytics)"),
        ("Kinesis Analytics", "AWS managed service for streaming SQL with Flink"),
        ("Materialized Views", "Pre-computed views that update incrementally with streaming data"),
        ("Lambda Architecture", "Hybrid batch + streaming architecture for comprehensive analytics"),
    ],
    "objectives": [
        "Design streaming analytics architecture with Kafka + Flink SQL",
        "Build real-time dashboards with live-updating visualizations",
        "Write streaming SQL queries for time-based aggregations",
        "Implement materialized views that update with stream data",
        "Use Kinesis Analytics for serverless streaming SQL",
        "Monitor and troubleshoot streaming analytics pipelines",
    ],
    "exercises": [
        "Set up Kafka topic with simulated event generator",
        "Write Flink SQL queries for tumbling window aggregations",
        "Build real-time dashboard with Grafana + streaming data source",
        "Create materialized view from Kafka stream using Flink SQL",
        "Deploy Kinesis Analytics application with SQL queries",
        "Implement alerting on streaming analytics (threshold breaches)",
    ],
    "quiz_qa": [
        ("What is streaming analytics?", ["Batch data processing", "Real-time data analysis", "Data storage", "Data catalog"]),
        ("Which SQL engine supports streaming queries?", ["PostgreSQL", "Flink SQL", "MySQL", "Oracle"]),
        ("What is a materialized view?", ["Database query", "Pre-computed incremental view", "Table index", "Data backup"]),
        ("What does Kinesis Analytics provide?", ["Data storage", "Serverless streaming SQL", "Data catalog", "Batch processing"]),
        ("What is Lambda Architecture?", ["Cloud function", "Hybrid batch+stream processing", "Data lake format", "SQL engine"]),
    ],
    "quiz_answers": ["B", "B", "B", "B", "B"],
    "flashcards": [
        ("What is streaming analytics?", "Real-time analysis of data as it arrives, enabling sub-second insights and immediate action"),
        ("What is Flink SQL?", "ANSI SQL interface for Apache Flink supporting streaming queries with windowed aggregations"),
        ("What is a materialized view in streaming?", "Result of streaming query stored in persistent table, updated incrementally as new data arrives"),
        ("What is Kinesis Analytics?", "AWS managed service running Flink-based streaming SQL without infrastructure management"),
        ("What is Lambda Architecture?", "Dual pipeline: batch layer (comprehensive, accurate) + speed layer (low-latency, approximate) + serving layer"),
    ],
    "interview": [
        ("Architecture", "How would you design a real-time analytics platform?", "Kafka for ingestion -> Flink SQL for processing -> Materialized views in PostgreSQL/ClickHouse -> Grafana for dashboards. Alerting via threshold-based or anomaly detection on streaming aggregates."),
        ("Flink SQL", "What Flink SQL features are important for streaming analytics?", "Windowed aggregations (TUMBLE, HOP, SESSION), WATERMARK for event time, upsert/sink to materialized views, CDC source connectors for database streams."),
        ("Lambda vs Kappa", "Lambda vs Kappa architecture for streaming analytics?", "Lambda: batch + stream (reconciled). Kappa: streaming only (simpler). Lambda is redundant if streaming can provide sufficient accuracy. Kappa is preferred for modern streaming analytics."),
        ("Dashboard Design", "How do you ensure real-time dashboards stay performant?", "Pre-aggregate in stream processor (not raw events to dashboard). Use materialized views. Implement TTL on data freshness. Push updates instead of poll. Cache dashboard queries."),
    ],
    "reflection": [
        "Streaming analytics fundamentally changes decision-making: from what happened (yesterday) to what's happening (now)",
        "Materialized views bridge the gap between stream processing and user-facing analytics",
        "Flink SQL makes streaming accessible to analysts familiar with SQL",
        "Dashboard design must balance real-time freshness with query performance",
        "Lambda architecture is sometimes over-engineering; Kappa architecture covers most use cases",
    ],
    "references": [
        "Flink SQL: https://nightlies.apache.org/flink/flink-docs-stable/docs/dev/table/sql/",
        "Kinesis Analytics: https://aws.amazon.com/kinesis/data-analytics/",
        "Grafana Streaming: https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/",
        "Materialize: https://materialize.com/",
        "ClickHouse: https://clickhouse.com/",
    ],
    "history": [
        ("2000s", "Early streaming: CEP engines (Esper, StreamBase)"),
        ("2011", "Apache Kafka created at LinkedIn"),
        ("2014", "Apache Flink emerges as streaming-first engine"),
        ("2016", "AWS Kinesis Analytics launched"),
        ("2019", "Flink SQL GA; stream processing becomes mainstream"),
        ("2020", "Materialize (streaming SQL database) public launch"),
        ("2022", "ClickHouse gains streaming ingestion capabilities"),
        ("2024", "Streaming analytics for real-time ML; AI-driven dashboards"),
    ],
    "mental_models": [
        ("The TV News Feed", "Streaming analytics is like a TV news ticker. Data flows continuously (news feed). Queries filter to relevant events (matching topics). Aggregations are headlines (summary statistics). Alerts are breaking news (threshold breaches)."),
        ("The Live Sports Scoreboard", "Scoreboard updates in real-time as game events happen. Hits, runs, errors = streaming events. Box score = aggregation. Win probability = analytics. No game (no data) means scoreboard is stale."),
        ("The Air Traffic Control", "ATC monitors planes in real-time. Position = streaming event. Altitude/speed = metrics. Collision warnings = alerts. Route planning = predictive analytics. Every second counts."),
    ],
    "theory_sections": [
        ("Streaming Analytics Architecture", "Ingestion layer: Kafka, Kinesis, Event Hub (buffers streams). Processing layer: Flink, Kafka Streams, Kinesis Analytics (computes aggregations). Storage layer: ClickHouse, PostgreSQL, Druid (materialized views for fast queries). Visualization layer: Grafana, Superset, custom dashboards."),
        ("Flink SQL for Analytics", "Window functions: TUMBLE (fixed non-overlapping), HOP (fixed overlapping), SESSION (activity-based). Watermarks: define event-time completeness. Aggregations: COUNT, SUM, AVG, MIN, MAX, DISTINCT. Joins: stream-stream, stream-table (lookup), stream-table (temporal). Upsert/CDC: maintain materialized views."),
        ("Materialized Views", "Pre-computed query results that update incrementally. Approach: Flink SQL writes upserts to sink table (PostgreSQL, ClickHouse). Incremental: only changed rows are re-computed. Benefits: dashboard queries are fast (read from pre-computed store). Trade-off: slight staleness (materialization latency)."),
        ("Real-Time Dashboard Patterns", "Push-based: server pushes updates to browser via WebSocket (live updates). Pull-based: dashboard polls fresh data on interval (every 5s). Hybrid: initial load from materialized view + incremental push for changes. Aggregation: pre-aggregate in stream processor to reduce dashboard query load."),
    ],
    "internals_sections": [
        ("Flink SQL Execution", "SQL → Logical Plan → Optimized Plan → StreamGraph. The planner converts SQL operators to streaming operators. Window functions become window operators. Joins become CoProcessFunction or IntervalJoin. Aggregations become stateful operators with state backends."),
        ("Materialized View Pipeline", "1. Kafka stream events. 2. Flink SQL aggregates into window slots. 3. UPSERT output to JDBC sink (PostgreSQL upsert). 4. Database maintains aggregated table. 5. Dashboard queries the aggregated table. 6. CRON/trigger for periodic full refresh to reconcile accuracy."),
        ("Kinesis Analytics Internals", "SQL queries run on Flink under the hood. Kinesis Data Stream as source. In-application streams (similar to SQL tables). Pump operations create streaming pipelines. Group by + window creates sliding/tumbling aggregations. Sink to Firehose, Lambda, Kinesis Data Stream, or external."),
        ("Lambda vs Kappa Trade-offs", "Lambda: two independent pipelines (batch + stream). Reconciliation layer merges results. Complex but accurate and comprehensive. Kappa: single streaming pipeline. Simpler but limited to windowed processing. For most analytics use cases, Kappa with sufficient streaming resources covers requirements."),
    ],
    "math": [
        ("Latency", "EndToEnd = Ingestion + Processing + Storage + Query + Render\nProcessingLatency = watermark - event_time\nRefreshLag = dashboard_freshness - realtime"),
        ("Throughput", "EventsPerSecond = input_partitions * partition_throughput\nAggregationThroughput = EventsPerSecond / aggregation_cardinality\nDashboardQueries = users * query_rate"),
        ("Window Semantics", "Tumbling: num_windows = time_range / window_size\nSliding: num_windows = time_range / slide + window_size / slide - 1\nSession: session_window_end = last_event_time + gap_duration"),
        ("Materialized View Sizing", "ViewRows = distinct_keys * distinct_windows\nViewSize = ViewRows * avg_row_size\nRefreshThroughput = aggregate_changes_per_second"),
    ],
    "visual": "```\nStreaming Analytics Architecture:\n[Event Sources: Apps, IoT, DBs]\n    |\n[Kafka / Kinesis: Stream Buffer]\n    |\n[Flink SQL / Kinesis Analytics: Stream Processing]\n    |\n[Materialized Views (PostgreSQL/ClickHouse)]\n    |\n[Grafana Dashboard / BI Tools]\n\n\nFlink SQL Example:\nCREATE TABLE orders (order_id BIGINT, amount DECIMAL, ts TIMESTAMP(3))\nWITH ('connector' = 'kafka', 'topic' = 'orders', 'format' = 'json');\n\nSELECT TUMBLE_START(ts, INTERVAL '1' MINUTE) AS window_start,\n       SUM(amount) AS total_revenue\nFROM orders\nGROUP BY TUMBLE(ts, INTERVAL '1' MINUTE);\n\nDashboard: Real-Time Revenue\nCurrent Minute: $12,450  [========          ] 62%\nToday:         $847,230  [===============   ] 85%\nActive Users:  1,423     [====              ]\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/twenty/ for:\n- StreamingAnalyticsJob.java: Flink SQL streaming analytics pipeline\n- DashboardDataService.java: REST API for materialized view serving\n\nKey patterns:\n```java\n// Flink SQL streaming analytics\nStreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();\nStreamTableEnvironment tEnv = StreamTableEnvironment.create(env);\n\ntEnv.executeSql(\"CREATE TABLE orders (\" +\n    \"order_id BIGINT, amount DECIMAL(10,2), customer_id STRING, \" +\n    \"order_ts TIMESTAMP(3), WATERMARK FOR order_ts AS order_ts - INTERVAL '5' SECOND\" +\n    \") WITH ('connector' = 'kafka', 'topic' = 'orders', 'format' = 'json', \" +\n    \"'properties.bootstrap.servers' = 'localhost:9092')\");\n\ntEnv.executeSql(\"CREATE TABLE metrics (\" +\n    \"window_start TIMESTAMP(3), revenue DECIMAL(10,2), order_count BIGINT, \" +\n    \"PRIMARY KEY (window_start) NOT ENFORCED\" +\n    \") WITH ('connector' = 'jdbc', 'url' = 'jdbc:postgresql://localhost/metrics', ...)\");\n\ntEnv.executeSql(\"INSERT INTO metrics SELECT \" +\n    \"TUMBLE_START(order_ts, INTERVAL '1' MINUTE), \" +\n    \"SUM(amount), COUNT(*) \" +\n    \"FROM orders GROUP BY TUMBLE(order_ts, INTERVAL '1' MINUTE)\");\n\nenv.execute(\"Revenue Analytics Pipeline\");\n```",
    "step_by_step": [
        "Set up Kafka cluster and create input topic",
        "Build event generator producing JSON events to Kafka",
        "Configure Flink cluster: standalone, YARN, or K8s",
        "Create Kafka source table in Flink SQL with watermark",
        "Write windowed aggregation query (TUMBLE, HOP, SESSION)",
        "Create sink table (PostgreSQL, ClickHouse) for materialized view",
        "Insert streaming results into sink table",
        "Configure Grafana datasource to PostgreSQL/ClickHouse",
        "Build dashboard panels with auto-refresh",
        "Set up alerting rules (threshold, anomaly)",
    ],
    "common_mistakes": [
        ("No Watermark Strategy", "Default processing time gives wrong results for out-of-order events"),
        ("Overloading Dashboards", "Raw event streams go directly to dashboard; always pre-aggregate"),
        ("No Punctuation", "Streaming queries without window limits grow unboundedly"),
        ("Wrong Parallelism", "Too few parallelism for high-throughput streams causes backpressure"),
        ("Ignoring Late Data", "Not configuring allowed lateness causes data loss without warning"),
    ],
    "debugging": [
        ("Dashboard Not Updating", "Check Kafka consumer lag; verify Flink job is running; check sink database for new rows"),
        ("Wrong Aggregations", "Verify watermark progress; check allowed lateness; verify event timestamps"),
        ("High Latency", "Check backpressure in Flink web UI; increase parallelism; optimize sink throughput"),
        ("Data Loss", "Check checkpoint failures; verify at-least-once or exactly-once semantics; check allowed lateness"),
    ],
    "refactoring": "## Batch to Streaming\nBefore: Hourly batch aggregations\nAfter: Streaming aggregations with Flink SQL\n\n## Pull to Push\nBefore: Dashboard polls database\nAfter: WebSocket push from stream processor to dashboard\n\n## Monolithic to Microservices\nBefore: Single analytics pipeline\nAfter: Independent streaming pipelines per business metric with materialized views",
    "performance": [
        ("Stream Processing", "Match parallelism to Kafka partition count. Use RocksDB state backend for large state. Tune checkpoint interval (30-60s for streaming)."),
        ("Materialized Views", "Use UPSERT sinks to minimize write operations. Batch writes to sink (buffer + flush). Partition materialized views by time for efficient pruning."),
        ("Dashboards", "Pre-aggregate at stream level (dashboard never reads raw data). Cache dashboard queries (5-30s TTL). Use push-based WebSocket for live updates."),
        ("Alerting", "Evaluate alert conditions in stream processor (not dashboard). Deduplicate alerts. Escalate based on severity and duration."),
    ],
    "security": "## Pipeline Security\n- TLS for Kafka, Flink, database connections\n- Authentication for all data sources\n- Authorization for stream processing jobs\n\n## Dashboard Security\n- Grafana authentication (LDAP, OAuth)\n- Row-level filters for multi-tenant dashboards\n- Audit logging of dashboard access\n\n## Data Protection\n- Encrypt sensitive fields before streaming\n- Mask PII in dashboard visualizations\n- Retention limits on stream data",
    "architecture": "```\n[Event Sources]\n    |\n[Kafka / Kinesis: Ingestion]\n    |\n[Flink SQL / Kinesis Analytics: Processing]\n    |\n[Materialized Views (PostgreSQL/ClickHouse)]\n    |\n[REST API / Grafana]\n    |\n[Users: Dashboards, Alerts, Applications]\n\nTypical Query:\nINSERT INTO materialized_view\nSELECT window_start, metric, COUNT(*), AVG(value)\nFROM stream\nGROUP BY TUMBLE(event_ts, INTERVAL '1' MINUTE), metric\n```",
    "how_it_works": "1. Events produced to Kafka topic from various sources (apps, IoT, DBs)\n2. Flink SQL reads stream with watermark strategy for event-time handling\n3. SQL queries compute windowed aggregations (per minute, hour, day)\n4. Results upserted into materialized view (PostgreSQL, ClickHouse)\n5. Grafana connects to materialized view database for fast queries\n6. Dashboard panels auto-refresh to show latest aggregated data\n7. Alert rules evaluate streaming metrics (threshold, trend, anomaly)\n8. Alert notifications sent via Slack, email, PagerDuty\n9. Users interact with dashboards for real-time business insights",
    "why_exists": "Batch analytics provides yesterday's data by the time it's available. Many use cases require immediate action: fraud detection, operational monitoring, user experience, system health, financial trading. Streaming analytics processes data as it arrives, enabling sub-second insights and automated responses to changing conditions.",
    "why_matters": "- **Real-Time Decisions**: Act on data as it arrives, not hours later\n- **Operational Awareness**: Live visibility into system and business health\n- **Customer Experience**: Detect and respond to issues before users notice\n- **Competitive Advantage**: Faster insights enable faster responses\n- **Cost Efficiency**: Process only what's needed, not full daily reprocessing\n- **Scalability**: Handle increasing event volumes without batch window constraints",
    "package": "com.dataeng.twenty",
    "JavaSources": {},
    "Tests": {},
}
LABS["20-streaming-analytics"] = l20
