#!/usr/bin/env python3
import os

BASE = r"C:\Users\jratombo-adm\Desktop\java_learning_lab\labs\data-engineering"

def w(path, content):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            f.write(content.lstrip() + "\n")
        return True
    return False

# ===== LAB 04: APACHE SPARK =====
d = os.path.join(BASE, "04-apache-spark")
for fname, c in {
    "THEORY.md": "# Apache Spark Theory\n\n## Architecture\n- **Driver**: Main program, creates SparkContext\n- **Cluster Manager**: YARN, K8s, Standalone\n- **Executors**: Worker processes\n- **Tasks**: Units of work\n\n## Core Abstractions\n- **RDD**: Immutable partitioned collection\n- **DataFrame**: RDD + Schema, optimized via Catalyst\n- **Dataset**: Type-safe DataFrame\n\n## Execution Model\nDAG Scheduler -> Task Scheduler -> Executors",
    "WHY_IT_MATTERS.md": "# Why Spark Matters\n\n## Impact\n- **Speed**: 100x faster than Hadoop MR for iterative algorithms\n- **Unified**: Batch, Streaming, SQL, ML, Graph in one engine\n- **Ecosystem**: Integrates with Kafka, HBase, Cassandra, S3\n- **Adoption**: 80%+ Fortune 500 companies\n\n## Performance\n- Process 100TB+ datasets\n- Stream millions of events/sec\n- Sub-second streaming latency",
    "INTERNALS.md": "# Spark Internals\n\n## Catalyst Optimizer\n1. Analysis: Resolve column/table references\n2. Logical Optimization: Predicate pushdown, constant folding\n3. Physical Planning: Join strategies, partitioning\n4. Code Generation: Generate optimized bytecode\n\n## Tungsten\n- Off-heap memory management\n- Cache-friendly data layout\n- Whole-stage code generation\n\n## Memory Regions\n- Execution: joins, sorts, aggregations\n- Storage: cache, broadcast\n- Reserved: overhead",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Memory\n`Total = executor.memory * instances`\n`Execution = Total * fraction * (1 - storageFraction)`\n`Storage = Total * fraction * storageFraction`\n\n## Shuffle Cost\n`Shuffle = Serialization + Network + Spill + Deserialization`\n\n## Join Costs\n- Broadcast: O(n)\n- Hash: O(n + m)\n- Sort Merge: O(n log n + m log m + n + m)",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Architecture\n```\n+--------+  +--------+  +--------+  +--------+\n| Driver |  | Exec 1 |  | Exec 2 |  | Exec 3 |\n+--------+  +--------+  +--------+  +--------+\n| DAG     |  | Cache  |  | Cache  |  | Cache  |\n| Sched   |  | Tasks  |  | Tasks  |  | Tasks  |\n+--------+  +--------+  +--------+  +--------+\n```\n\n## DAG\n```\nStage 0: Read + Filter (narrow)\nStage 1: Shuffle + Aggregate (wide)\nStage 2: Sort (wide)\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Spark DataFrame API\n\n## DataFrame Operations\n```java\npublic class DataFrameOps {\n    public Dataset<Row> analyzeSales(Dataset<Row> sales) {\n        return sales\n            .select(\"product_id\", \"amount\", \"date\")\n            .filter(col(\"amount\").$greater(0))\n            .withColumn(\"year\", year(col(\"date\")))\n            .groupBy(\"product_id\", \"year\")\n            .agg(sum(\"amount\").as(\"total\"), count(\"*\").as(\"count\"))\n            .orderBy(col(\"year\").desc());\n    }\n}\n```\n\n## Spark Streaming\n```java\nDataset<Row> stream = spark.readStream()\n    .format(\"kafka\").option(\"subscribe\", \"topic\").load()\n    .selectExpr(\"CAST(value AS STRING)\");\n\nstreamingQuery = stream.writeStream()\n    .outputMode(\"append\").format(\"console\").start();\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Setup**: Add spark-core and spark-sql dependencies\n2. **Initialize**: SparkSession.builder().appName().getOrCreate()\n3. **Load**: spark.read().format().load()\n4. **Transform**: filter, groupBy, agg, withColumn\n5. **Write**: result.write().mode().format().save()\n6. **Submit**: spark-submit --class Main --master yarn app.jar",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **Collecting Large Datasets**: Use foreachPartition instead of collectAsList\n2. **Not Broadcasting**: Small tables should use broadcast hint\n3. **Too Many Tasks**: Match shuffle partitions to cluster size\n4. **Not Caching**: Reused DataFrames should be cached\n5. **Serialization Issues**: Lambdas capturing non-serializable objects",
    "DEBUGGING.md": "# Debugging\n\n## OOM\n- Check Spark UI Executors tab\n- Increase executor memory\n- Enable off-heap memory\n\n## Skew\n- Check task time distribution\n- Add salting: key + \"_\" + salt\n- Enable AQE: spark.sql.adaptive.skewJoin.enabled=true\n\n## Plan Inspection\n```java\ndataset.explain(\"formatted\");\ndataset.explain(\"cost\");\n```",
    "REFACTORING.md": "# Refactoring\n\n## RDD to DataFrame\nBefore: `rdd.map(...).reduceByKey(...)`\nAfter: `df.groupBy(\"key\").count()`\n\n## SQL to Dataset API\n```java\n// Before: spark.sql(\"SELECT * FROM sales\")\n// After: salesDF.select(\"*\")\n```",
    "PERFORMANCE.md": "# Performance\n\n## AQE\n```java\nSparkSession.builder()\n    .config(\"spark.sql.adaptive.enabled\", \"true\")\n    .config(\"spark.sql.adaptive.coalescePartitions.enabled\", \"true\")\n    .config(\"spark.sql.adaptive.skewJoin.enabled\", \"true\")\n    .getOrCreate();\n```\n\n## Kryo Serialization\n```java\nspark.conf().set(\"spark.serializer\", \"org.apache.spark.serializer.KryoSerializer\");\n```\n\n## Broadcast Joins\n```java\nlargeDF.join(broadcast(smallDF), \"key\");\n```",
    "SECURITY.md": "# Security\n\n## Authentication\n```java\nspark.conf().set(\"spark.authenticate\", \"true\");\nspark.conf().set(\"spark.network.crypto.enabled\", \"true\");\n```\n\n## SQL Redaction\n```java\nspark.conf().set(\"spark.sql.redaction.string.regex\", \"(?i)(password|secret)\");\n```",
    "ARCHITECTURE.md": "# Architecture\n\n## Cluster Mode\n```\n[Driver] <-> [Cluster Manager] <-> [Executors]\n```\n\n## Application Components\n- SparkSession\n- DataFrame/Dataset API\n- Catalyst Optimizer\n- Tungsten Engine",
    "EXERCISES.md": "# Exercises\n\n1. Word count with RDD and DataFrame APIs\n2. Sales analysis: daily revenue by category\n3. Streaming pipeline with Kafka + Delta Lake\n4. Custom UDAF for percentile calculation\n5. Performance tuning: optimize slow query with AQE",
}.items():
    if w(os.path.join(d, fname), c): pass

print("Lab 04 done")

# ===== LAB 05: APACHE FLINK =====
d = os.path.join(BASE, "05-apache-flink")
for fname, c in {
    "THEORY.md": "# Flink Theory\n\n## Time Semantics\n- **Event Time**: When event occurred (source timestamp)\n- **Processing Time**: When event is processed\n- **Ingestion Time**: When event enters Flink\n\n## State Management\n- **Keyed State**: Per-key in keyed streams\n- **Operator State**: Per-operator parallelism\n- **Managed State**: Auto checkpoint/recovery\n\n## Windows\n- **Tumbling**: Fixed non-overlapping\n- **Sliding**: Fixed overlapping\n- **Session**: Inactivity gaps",
    "WHY_IT_MATTERS.md": "# Why Flink Matters\n\n- **True Streaming**: Event-by-event, not micro-batches\n- **Exactly-Once**: Distributed snapshots + transactional sinks\n- **Event-Time**: Watermarks for handling late data\n- **Performance**: Millions events/sec per node, sub-ms latency",
    "INTERNALS.md": "# Flink Internals\n\n## Architecture\n```\n[JobManager] <-> [TaskManager 1] [TaskManager 2]\n                   Task Slots        Task Slots\n```\n\n## State Backends\n- MemoryStateBackend (dev only)\n- FsStateBackend (production, file-based)\n- RocksDBStateBackend (large state, disk-based)",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Parallelism\n`Throughput = Events / Time`\n`Optimal Parallelism = min(SourcePartitions, Cores)`\n\n## Checkpoint Cost\n`Duration = StateSize / SnapshotBandwidth + AlignTime`\n\n## Watermarks\n`Watermark = min(EventTimes) - MaxOutOfOrderness`\n`LateFraction = LateEvents / TotalEvents`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Streaming Topology\n```\n[Kafka Source] -> [Map: Parse] -> [KeyBy] -> [Window] -> [Aggregate] -> [Sink]\n```\n\n## Watermark Progress\n```\nEvent Time --> 10:00  10:01  10:02  W=10:02  10:03  W=10:03\n```",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Flink Fraud Detection\n\n## KeyedProcessFunction\n```java\npublic class FraudDetector extends KeyedProcessFunction<String, Transaction, Alert> {\n    private ValueState<Double> lastAmountState;\n\n    @Override\n    public void open(Configuration params) {\n        lastAmountState = getRuntimeContext()\n            .getState(new ValueStateDescriptor<>(\"lastAmount\", Types.DOUBLE));\n    }\n\n    @Override\n    public void processElement(Transaction tx, Context ctx, Collector<Alert> out) {\n        Double last = lastAmountState.value();\n        if (last != null && tx.getAmount() > 1000 && last > 1000\n            && tx.getTimestamp() - lastTimestamp < 60000) {\n            out.collect(new Alert(\"Suspicious activity\", tx.getAccountId()));\n        }\n        lastAmountState.update(tx.getAmount());\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Setup**: Add flink-java, flink-streaming dependencies\n2. **Create Env**: StreamExecutionEnvironment.getExecutionEnvironment()\n3. **Add Source**: env.addSource(new FlinkKafkaConsumer<>(...))\n4. **Transform**: .keyBy().window().aggregate()\n5. **Add Sink**: .addSink(new FlinkKafkaProducer<>(...))\n6. **Execute**: env.execute(\"job-name\")",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **Wrong Time Characteristic**: Using ProcessingTime for event-time logic\n2. **No Watermark Strategy**: Missing assignTimestampsAndWatermarks\n3. **Wrong State Backend**: JVM heap OOM for large state\n4. **No Checkpointing**: Missing fault tolerance config",
    "DEBUGGING.md": "# Debugging\n\n## Backpressure\n- Flink Web UI shows backpressure in red for tasks\n- Fix: Increase parallelism, optimize operators\n\n## Watermark Not Advancing\n- Check if timestamps are monotonic\n- Verify valid timestamps in events\n\n## Checkpoint Failures\n- Increase timeout for large state\n- Check logs for serialization issues",
    "PERFORMANCE.md": "# Performance\n\n## Buffer Timeout\n```java\nenv.setBufferTimeout(50); // Lower = lower latency, higher CPU\n```\n\n## Operator Chaining\n```java\nenv.disableOperatorChaining(); // Debug only\n```\n\n## RocksDB Tuning\n```java\nRocksDBStateBackend backend = new RocksDBStateBackend(uri, true);\nbackend.setPredefinedOptions(PredefinedOptions.SPINNING_DISK_OPTIMIZED_HIGH);\nenv.setStateBackend(backend);\n```",
    "SECURITY.md": "# Security\n\n## Kerberos\n```java\nenv.getConfig().setGlobalJobParameters(new Configuration() {{\n    setString(\"security.kerberos.login.keytab\", \"/path/to/keytab\");\n}});\n```\n\n## SSL\nEnable SSL in flink-conf.yaml for network encryption.",
    "ARCHITECTURE.md": "# Architecture\n\n```\n[Flink Client] -> [JobManager] -> [TaskManager 1] [TaskManager 2]\n                                  [Task Slots]    [Task Slots]\n```\n\n## Spring Boot Integration\n```java\n@Bean\npublic StreamExecutionEnvironment flinkEnv() {\n    return StreamExecutionEnvironment.getExecutionEnvironment();\n}\n```",
    "EXERCISES.md": "# Exercises\n\n1. Real-time word count from socket/Kafka\n2. Event-time aggregation with 5-min tumbling windows\n3. CEP pattern: 3 failed logins in 5 minutes\n4. Stateful enrichment with external data\n5. Custom ProcessFunction with timers for heartbeat monitoring",
}.items():
    if w(os.path.join(d, fname), c): pass

print("Lab 05 done")

# ===== LAB 06: KAFKA STREAMING =====
d = os.path.join(BASE, "06-kafka-streaming")
for fname, c in {
    "THEORY.md": "# Kafka Streams Theory\n\n## Stream-Table Duality\n- **KStream**: Append-only log of facts\n- **KTable**: Changelog representing current state\n- Either can be derived from the other\n\n## Processing Guarantees\n- At-most-once: No retries\n- At-least-once: Retry with duplicates\n- Exactly-once: Kafka transactions + idempotent writes\n\n## State Stores\n- RocksDB: Embedded KV store (default)\n- InMemory: Pure in-memory",
    "WHY_IT_MATTERS.md": "# Why Kafka Streams Matters\n\n- **No Separate Cluster**: Embedded in your Java app\n- **Exactly-Once**: Native Kafka transactions\n- **Interactive Queries**: Query state stores via REST\n- **Operational Simplicity**: Standard Java deployment\n- **Performance**: Millions events/sec, sub-ms latency",
    "INTERNALS.md": "# Kafka Streams Internals\n\n## Task Architecture\nApplication splits into tasks (one per partition). Each task has its own consumer + producer.\n\n## State Management\nRocksDB state stores with changelog topics for fault tolerance. Local state + Kafka-backed recovery.\n\n## Exactly-Once\nTransactional writes to output + offset commits in same transaction.",
    "MATH_FOUNDATION.md": "# Math Foundation\n\n## Throughput\n`Records/Sec = BatchSize / ProcessingTime`\n`MaxThroughput = Partitions * PerPartitionThroughput`\n\n## State Size\n`StateSize = Keys * ValueSize * (1 + Overhead)`\n`ChangelogSize = StateSize * UpdateRate * Retention`",
    "VISUAL_GUIDE.md": "# Visual Guide\n\n## Topology\n```\n[Source: orders] -> [Join: customers] -> [EnrichedOrder]\n                     |                   |\n                     |         [GroupBy region] -> [Count] -> [Sink]\n                     |         [Filter: amount>10000] -> [Alert] -> [Sink]\n```\n\n## Stream-Table Duality\nKStream: append-only log. KTable: latest value per key.",
    "CODE_DEEP_DIVE.md": "# Code Deep Dive: Kafka Streams\n\n## Clickstream Pipeline\n```java\n@Configuration\n@EnableKafkaStreams\npublic class ClickstreamPipeline {\n    @Bean\n    public KStream<String, ClickEvent> clickStream(StreamsBuilder builder) {\n        return builder.stream(\"clicks\");\n    }\n\n    @Bean\n    public KTable<String, Long> pageViews(KStream<String, ClickEvent> clicks) {\n        return clicks.groupBy((k, v) -> v.getUrl())\n            .count(Materialized.as(\"page-view-counts\"));\n    }\n}\n```\n\n## Interactive Queries\n```java\n@RestController\npublic class StateQueryController {\n    @GetMapping(\"/count/{url}\")\n    public Long getCount(@PathVariable String url) {\n        ReadOnlyKeyValueStore<String, Long> store =\n            streams.store(StoreQueryParameters.fromNameAndType(\n                \"page-view-counts\", QueryableStoreTypes.keyValueStore()));\n        return store.get(url);\n    }\n}\n```",
    "STEP_BY_STEP.md": "# Step-by-Step\n\n1. **Add Deps**: kafka-streams, spring-kafka\n2. **Configure**: application.id, bootstrap.servers, serdes\n3. **Build Topology**: StreamsBuilder, KStream, KTable, joins\n4. **Start**: KafkaStreams.start()\n5. **Monitor**: Consumer groups, state store sizes, lag",
    "COMMON_MISTAKES.md": "# Common Mistakes\n\n1. **Wrong Serde**: Missing serialization config causes errors\n2. **State Store Name Conflicts**: Duplicate names across topologies\n3. **Not Handling Tombstones**: Null values in KTable cause NPE\n4. **Ignoring Rebalance**: No state listener for graceful shutdown",
    "DEBUGGING.md": "# Debugging\n\n## Lag\n```bash\nkafka-consumer-groups --bootstrap-server localhost:9092 \\\n  --group app-id --describe\n```\n\n## Topology\n```java\nSystem.out.println(builder.build().describe());\n```\n\n## Error Handling\n```java\nprops.put(DEFAULT_DESERIALIZATION_EXCEPTION_HANDLER_CLASS_CONFIG,\n    LogAndContinueExceptionHandler.class);\n```",
    "PERFORMANCE.md": "# Performance\n\n## Tuning\n```java\nprops.put(StreamsConfig.COMMIT_INTERVAL_MS_CONFIG, 100);\nprops.put(StreamsConfig.NUM_STREAM_THREADS_CONFIG, 4);\nprops.put(StreamsConfig.CACHE_MAX_BYTES_BUFFERING_CONFIG, 10L * 1024 * 1024);\n```\n\n## RocksDB\n```java\nprops.put(StreamsConfig.ROCKSDB_CONFIG_SETTER_CLASS_CONFIG,\n    (RocksDBConfigSetter) (db, config) -> {\n        db.setOptions(o -> o.setIncreaseParallelism(4));\n    }.getClass());\n```",
    "SECURITY.md": "# Security\n\n## SASL/SSL\n```java\nprops.put(SECURITY_PROTOCOL_CONFIG, \"SASL_SSL\");\nprops.put(SASL_MECHANISM, \"SCRAM-SHA-512\");\nprops.put(SASL_JAAS_CONFIG, \"...\");\n```\n\n## ACLs\nGrant read/write permissions for source/sink topics and changelog topics.",
    "ARCHITECTURE.md": "# Architecture\n\n```\n[Kafka Streams App]\n  [Topology: Source -> Process -> Sink]\n  [State Stores: RocksDB]\n    |              |\n[Kafka Topics]  [Changelog Topics]\n```",
    "EXERCISES.md": "# Exercises\n\n1. Word count with KStream/KTable\n2. Stream-table join (orders + customers)\n3. Session window for clickstream\n4. Custom stateful processor for rapid-fire detection\n5. Interactive query REST API",
}.items():
    if w(os.path.join(d, fname), c): pass

print("Lab 06 done")

print("Labs 04-06 complete")
