#!/usr/bin/env python3
import os

BASE = r"C:\Users\jratombo-adm\Desktop\java_learning_lab\labs\data-engineering"

labs = {
    "05-apache-flink": {"REFACTORING.md": "# Refactoring Flink Applications\n\n## Before: Monolithic ProcessFunction\n```java\nstream.process(new MyComplexProcessFunction() {\n    // 500 lines\n});\n```\n\n## After: Modular Operators\n```java\nDataStream<Raw> raw = env.addSource(source);\nDataStream<Parsed> parsed = raw.map(new Parser());\nDataStream<Enriched> enriched = parsed.keyBy(...).process(new Enricher());\nDataStream<Output> result = enriched.window(...).aggregate(new Aggregator());\n```\n\n## Before: Hardcoded Config\n```java\nstream.window(TumblingProcessingTimeWindows.of(Time.minutes(5)));\n```\n\n## After: Parameterized\n```java\n@Value(\"${window.size.minutes:5}\")\nprivate int windowSize;\nstream.window(TumblingProcessingTimeWindows.of(Time.of(windowSize, TimeUnit.MINUTES)));\n```"},
    "06-kafka-streaming": {"REFACTORING.md": "# Refactoring Kafka Streams\n\n## Before: Single Large Topology\n```java\nbuilder.stream(\"input\").mapValues(v -> { /* complex */ })\n    .filter((k,v) -> { /* more logic */ }).groupByKey().count().toStream().to(\"output\");\n```\n\n## After: Modular Topologies\n```java\nKStream<String, Processed> processed = processInput(builder.stream(\"input\"));\nKTable<String, Long> counts = aggregate(processed);\noutputResults(counts);\n```\n\n## Before: Hardcoded Topics\n```java\nbuilder.stream(\"orders\");\n```\n\n## After: Configuration\n```java\n@Value(\"${kafka.topics.input}\")\nprivate String inputTopic;\n```"},
    "07-data-lake": {"REFACTORING.md": "# Refactoring Data Lakes\n\n## From Ad-hoc to Medallion\n**Before**: No structure, random paths\n```java\nspark.read().parquet(\"s3://data/sales_march.parquet\");\nspark.read().json(\"s3://data/export_20240301.json\");\n```\n\n**After**: Structured medallion\n```java\nspark.table(\"bronze.sales\");\nspark.table(\"silver.events\");\nspark.table(\"gold.daily_metrics\");\n```\n\n## From No ACID to Delta Lake\n**Before**: Parquet with no transactions\n**After**: Delta Lake with ACID, time travel, schema evolution"},
    "08-workflow-orchestration": {"REFACTORING.md": "# Refactoring Orchestration\n\n## Before: Monolithic DAG\n```python\n# 500-line DAG with everything\ndag = DAG('everything')\ntask1 = ... task2 = ... # 50 more tasks\n```\n\n## After: Modular DAGs\nUse SubDagOperators or separate DAG files per domain.\n\n## Before: Duplicated Code\nSame validation in 5 DAGs.\n\n## After: Shared Plugins\n```python\n# airflow/plugins/custom_operators.py\nclass QualityCheckOperator(BaseOperator):\n    def execute(self, context):\n        # Shared validation logic\n        pass\n```", "COMMON_MISTAKES.md": "# Common Orchestration Mistakes\n\n1. **Not Using Idempotent Tasks**: Append without checking for duplicates\n2. **Hardcoding Dependencies**: Rigid task ordering\n3. **No Task Timeouts**: Tasks can run forever\n4. **Too Many Tasks in One DAG**: 200+ tasks unwieldy to monitor\n5. **Ignoring Catchup**: Missing backfill logic"},
    "09-data-quality": {"REFACTORING.md": "# Refactoring Data Quality\n\n## Before: Ad-hoc Checks\n```java\nif (data.filter(col(\"id\").isNull()).count() > 100) { alert(); }\nif (!data.schema().fieldNames().contains(\"email\")) { alert(); }\n```\n\n## After: Unified Framework\n```java\nQualityReport report = framework.validate(data, \"customers\");\nif (!report.isPassed()) { alert(report); }\n```\n\n## Before: Hardcoded Rules\n## After: Declarative Configuration\n```yaml\ncustomers:\n  rules:\n    - type: NOT_NULL\n      columns: [customer_id, email]\n    - type: UNIQUE\n      columns: [customer_id]\n```"},
    "10-change-data-capture": {"REFACTORING.md": "# Refactoring CDC\n\n## Before: Timestamp-Based Polling\n```java\nSELECT * FROM orders WHERE updated_at > ?;\n// Misses deletes, high latency\n```\n\n## After: Log-Based CDC\n```java\nDebeziumEngine.create(Json.class)\n    .using(config)\n    .notifying(this::process)\n    .build();\n// Captures all changes, zero source impact\n```\n\n## Before: Raw Table CDC\nNoisy, captures all internal changes.\n\n## After: Outbox Pattern\n```java\n// Application writes to outbox table with explicit events\n// Clean, intentional event publication\n```"},
    "11-feature-stores": {"REFACTORING.md": "# Refactoring Feature Engineering\n\n## Before: Ad-hoc Notebook Features\n```python\nfeatures = df.groupby('user').agg({'amount': 'mean'})\n```\n\n## After: Centralized Feature Store\n```java\nFeatureDefinition def = FeatureDefinition.builder()\n    .name(\"avg_order_value\")\n    .transformation(\"SELECT user_id, AVG(amount) FROM transactions GROUP BY user_id\")\n    .build();\nregistry.register(def);\n```\n\n## Before: Inconsistent Serving Logic\nBatch and serving use different code!\n\n## After: Unified Logic\n```java\npublic double compute(List<Transaction> txns) {\n    return txns.stream().mapToDouble(Transaction::getAmount).average().orElse(0);\n}\n// Used in both Spark (offline) and Java service (online)\n```", "DEBUGGING.md": "# Debugging Feature Stores\n\n## Training/Serving Skew\n```java\nspark.read().parquet(\"s3://features/train/\").describe().show();\nspark.read().parquet(\"s3://features/serving/\").describe().show();\n```\n\n## Feature Freshness\n```java\nspark.sql(\"SELECT MAX(feature_timestamp) FROM offline.user_features\").show();\n```\n\n## Online Store Connectivity\n```java\nJedis jedis = new Jedis(\"feature-store-redis\", 6379);\nString pong = jedis.ping();\nif (!\"PONG\".equals(pong)) { log.error(\"Redis not reachable\"); }\n```\n\n## Missing Features\n```java\nFeatureDefinition def = registry.getFeature(\"avg_order_value\");\nif (def == null) { log.error(\"Feature not registered\"); }\n```"},
    "12-data-governance": {"REFACTORING.md": "# Refactoring Governance\n\n## Before: No Governance\n```java\n// Anyone can access any data\nspark.sql(\"SELECT * FROM customers\").show();\n```\n\n## After: Policy Enforced\n```java\nspark.sql(\"SELECT * FROM governed.customers\").show();\n// Automatically filtered by policies\n```\n\n## Before: Manual Documentation\nREADME.txt out of date within days.\n\n## After: Automated Catalog\n```java\ncatalog.getAsset(\"fact_orders\");\n// Returns: schema, owner, domain, lineage, quality score\n```\n\n## Before: No Lineage (2-hour investigation)\n## After: Automated Lineage\n```java\nlineageService.getLineage(\"fact_orders\");\n// Returns: CRM -> ETL -> fact_orders -> BI Dashboard\n```"},
}

for lab, files in labs.items():
    d = os.path.join(BASE, lab)
    for fname, content in files.items():
        path = os.path.join(d, fname)
        if not os.path.exists(path):
            with open(path, "w", encoding="utf-8") as f:
                f.write(content.lstrip() + "\n")
            print(f"Created: {lab}/{fname}")
        else:
            print(f"Exists: {lab}/{fname}")

print("\nAll missing files generated!")
