#!/usr/bin/env python3
"""Content templates for labs 13-16."""
from gen_content_09_12 import make_docs

LABS = {}

# ===== LAB 13: DELTA LAKE =====
l13 = {
    "title": "Delta Lake",
    "short": "Delta Lake",
    "overview": "Delta Lake is an open-source storage layer that brings ACID transactions to Apache Spark and big data workloads. It provides time travel, schema enforcement, and unified batch/streaming on data lakes.",
    "concepts": [
        ("ACID Transactions", "Atomicity, Consistency, Isolation, Durability on data lake storage"),
        ("Transaction Log", "JSON-based commit log in _delta_log/ directory tracking all changes"),
        ("Time Travel", "Query and restore historical versions of data using version or timestamp"),
        ("Schema Enforcement", "Prevents corrupt data writes by validating against table schema"),
        ("Merge/Upsert", "Efficient INSERT, UPDATE, DELETE operations via MERGE INTO"),
        ("Optimize & Vacuum", "File compaction with Z-ordering and cleanup of unreferenced files"),
    ],
    "objectives": [
        "Understand Delta Lake's transaction log protocol and ACID guarantees",
        "Implement time travel queries for data auditing and recovery",
        "Use MERGE INTO for upsert operations with conflict resolution",
        "Configure schema enforcement and evolution for production pipelines",
        "Run OPTIMIZE with Z-ordering for query performance",
        "Manage storage lifecycle with VACUUM and retention policies",
    ],
    "exercises": [
        "Create Delta table from Parquet; inspect _delta_log/ directory structure",
        "Implement MERGE INTO with WHEN MATCHED and WHEN NOT MATCHED clauses",
        "Query different versions using versionAsOf and timestampAsOf",
        "Optimize small files with OPTIMIZE and ZORDER BY",
        "Configure Change Data Feed and read row-level changes",
        "Simulate concurrent write conflicts and implement retry logic",
    ],
    "quiz_qa": [
        ("What storage format does Delta Lake use?", ["CSV", "Parquet", "Avro", "ORC"]),
        ("Where does Delta Lake store transaction logs?", ["External DB", "_delta_log/ directory", "ZooKeeper", "In-memory"]),
        ("What does VACUUM do?", ["Compacts small files", "Removes unreferenced files", "Changes partitions", "Updates statistics"]),
        ("What does OPTIMIZE ZORDER BY improve?", ["Write speed", "Read pruning", "Compression ratio", "Network transfer"]),
        ("How does Delta Lake handle concurrent writes?", ["Pessimistic locking", "Optimistic concurrency control", "Single writer", "Last-write-wins"]),
    ],
    "quiz_answers": ["B", "B", "B", "B", "B"],
    "flashcards": [
        ("What is Delta Lake?", "Open-source storage layer adding ACID transactions to data lakes using Parquet + transaction log"),
        ("How does Delta handle concurrent writes?", "Optimistic concurrency control with conflict detection; writers retry on conflict"),
        ("What is OPTIMIZE?", "File compaction that bin-packs small files and optionally Z-orders data for better pruning"),
        ("What is the transaction log?", "JSON files in _delta_log/ recording every commit; enables time travel and ACID"),
        ("What is Z-ordering?", "Clustering related data within files for better file skipping during queries"),
    ],
    "interview": [
        ("Transaction Log", "Explain Delta Lake's transaction log protocol.", "JSON files in _delta_log/, each commit creates new version; readers reconstruct file list from log; concurrent writes use optimistic locking with retry"),
        ("Time Travel", "How does Time Travel work in Delta Lake?", "Each version tracks complete file set; read at version N reconstructs state from log; VACUUM removes old files beyond retention window"),
        ("Optimization", "How does OPTIMIZE improve performance?", "Compacts small files into larger ones (256MB-1GB); Z-ordering colocates related data; reduces metadata overhead and improves file skipping"),
        ("Comparison", "Difference between Delta Lake and Apache Iceberg?", "Delta: Spark-native, JSON transaction log. Iceberg: catalog abstraction, partition evolution, broader engine support. Both provide ACID on data lakes."),
    ],
    "reflection": [
        "Transaction log is Delta's killer feature enabling reliable data lakes with ACID guarantees",
        "OPTIMIZE and VACUUM lifecycle management is essential for production performance",
        "Schema enforcement prevents silent data corruption from schema drift",
        "MERGE operations are powerful but require careful conflict handling at scale",
        "Z-ordering on the right columns can dramatically improve query performance",
    ],
    "references": [
        "Delta Lake Docs: https://docs.delta.io/latest/",
        "Delta Lake GitHub: https://github.com/delta-io/delta",
        "Transaction Log: https://docs.delta.io/latest/delta-internals.html",
        "Optimization: https://docs.delta.io/latest/optimizations-oss.html",
        "Change Data Feed: https://docs.delta.io/latest/delta-change-data-feed.html",
    ],
    "history": [
        ("2017", "Developed internally at Databricks"),
        ("2019", "Open-sourced under Linux Foundation"),
        ("2020", "Delta Lake 0.8 with Delta Sharing"),
        ("2021", "Delta Lake 1.0 GA; change data feed"),
        ("2022", "Delta Lake 2.0; Delta Sharing open-sourced"),
        ("2023", "Delta Lake 3.0; UniForm (Iceberg compatibility)"),
        ("2024", "Delta Lake 3.2; liquid clustering, identity columns"),
    ],
    "mental_models": [
        ("Git for Data", "Delta is like git for data lakes. Commit = write, Log = git log, Checkout = Time Travel, Branch = Clone, Merge = MERGE INTO, Revert = restore from version."),
        ("The Filing Cabinet", "Transaction log = index card catalog. Each commit = new entries in catalog. VACUUM = shredding old cards no longer referenced. Files = documents in drawers."),
        ("The Layered Cake", "Each version is a layer of cake. You can slice at any layer (Time Travel). OPTIMIZE is like pressing the cake into fewer, denser layers. VACUUM removes stale crumbs."),
    ],
    "theory_sections": [
        ("Transaction Log Protocol", "JSON files in _delta_log/ directory track every commit. Each commit records AddFile and RemoveFile actions. Readers read latest version and construct full file list. Checkpoint files (Parquet) periodically snapshot log state for faster reads."),
        ("ACID Guarantees", "Atomicity: all changes in commit succeed or fail. Consistency: schema and constraints enforced. Isolation: optimistic concurrency control detects conflicts. Durability: committed data persisted to storage. Multiple writers can write concurrently with conflict detection and automatic retry."),
        ("Schema Enforcement & Evolution", "By default, Delta enforces schema on write — mismatched columns cause errors. mergeSchema=true allows automatic schema evolution (adding columns, widening types). Schema tracking in transaction log enables audit trail of all schema changes."),
        ("Lifecycle Management", "OPTIMIZE: bin-packs small files into larger ones (target 256MB-1GB). ZORDER BY: colocates related data for file skipping. VACUUM: removes files not referenced by any version within retention period (default 7 days). Change Data Feed: enables streaming consumption of row-level changes."),
    ],
    "internals_sections": [
        ("Commit Protocol", "1. Read latest table version from _delta_log. 2. Check for conflicts (file overlap). 3. Create new commit JSON with AddFile/RemoveFile actions. 4. Write atomically to _delta_log/. 5. On conflict, retry with latest version. 6. Periodic checkpoints reduce log replay overhead."),
        ("File Layout", "Table stored as Parquet files in directory. _delta_log/ contains commit JSONs (00000001.json, 00000002.json) and checkpoint Parquet files. Each commit is complete snapshot of files for that version. Time travel reads historical commit's file list."),
        ("Optimize Mechanics", "1. Scan all small files in table. 2. Read and repartition data into target file size. 3. Write new larger files. 4. Commit AddFile for new files + RemoveFile for old files. 5. Optionally Z-order data within files by specified columns. 6. All happen atomically in single commit."),
        ("Change Data Feed", "Enabled per table. Records insert, update, delete events with before/after images. Reads as version table with _change_type column. Supports incremental processing without full table scans. Output compatible with streaming consumers."),
    ],
    "math": [
        ("Storage Versioning", "VersionedStorage = SUM(file_sizes * num_versions_referencing)\nTableSize = CurrentSize + LogSize + CheckpointSize\nOptimizeReduction = OriginalFiles / OptimizedFiles"),
        ("Compaction", "OptimalFileSize = 256MB (configurable)\nFilesAfterOptimize = TotalDataSize / OptimalFileSize\nReductionRatio = OriginalFiles / OptimizedFiles"),
        ("Transaction Log", "CommitDuration = ReadLog + Validate + WriteLog\nCheckpointInterval = 10 commits (default)\nLogReplayTime = NumVersions * DeserializeTime"),
        ("Vacuum", "SafeFiles = FilesReferencedByLast(N * retention_period)\nOrphanFiles = TotalFiles - SafeFiles\nSavings = OrphanFiles * AvgFileSize"),
    ],
    "visual": "```\nTransaction Log Timeline:\nv1: +file1.parquet (INSERT 1000 rows)\nv2: +file2.parquet (INSERT 500 rows)\nv3: -file1.parquet +file3.parquet (UPDATE 200 rows)\nv4: -file2.parquet (DELETE file2 rows)\n\nRead at v2: file1 + file2\nRead at v4: file3 (latest)\n\nDelta Architecture:\n[Parquet Files] + [Delta Log: _delta_log/]\n                      |\n             [Transaction Log]\n             [JSON Commits] [Checkpoints]\n\nMerge Flow:\nMERGE INTO target USING source ON key\n-> Read latest version\n-> Compute matches\n-> Generate AddFile/RemoveFile\n-> Write commit atomically\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/thirteen/ for:\n- DeltaLakeManager.java: Table CRUD, upsert, time travel, optimize, vacuum\n- DeltaOptimizer.java: File compaction, Z-ordering, partitioning strategies\n\nKey patterns:\n```java\n// Upsert via MERGE INTO\nspark.sql(\"MERGE INTO delta.`/path` t USING updates s \" +\n    \"ON t.id = s.id \" +\n    \"WHEN MATCHED THEN UPDATE SET * \" +\n    \"WHEN NOT MATCHED THEN INSERT *\");\n\n// Time travel\nspark.read().format(\"delta\").option(\"versionAsOf\", 25).load(\"/path\");\n\n// Optimize with Z-order\nspark.sql(\"OPTIMIZE delta.`/path` ZORDER BY (customer_id)\");\n\n// Vacuum\nspark.sql(\"VACUUM delta.`/path` RETAIN 168 HOURS\");\n```",
    "step_by_step": [
        "Add Delta Lake package to Spark: --packages io.delta:delta-core_2.12:x.y.z",
        "Configure SparkSession with Delta extensions and catalog",
        "Write DataFrame: df.write().format(\"delta\").save(\"/path\")",
        "Explore _delta_log/ with ls and cat on JSON files",
        "Time travel: spark.read().format(\"delta\").option(\"versionAsOf\", N).load(\"/path\")",
        "Upsert: MERGE INTO delta.`/path` t USING ... ON key WHEN MATCHED/WHEN NOT MATCHED",
        "Optimize: OPTIMIZE delta.`/path` ZORDER BY (columns)",
        "Vacuum: VACUUM delta.`/path` RETAIN 168 HOURS",
        "Enable Change Data Feed: ALTER TABLE SET TBLPROPERTIES (delta.enableChangeDataFeed=true)",
    ],
    "common_mistakes": [
        ("No VACUUM Retention", "Setting too short retention (<7 days) breaks time travel queries; default 7 days is safe"),
        ("Too Many Small Files", "Without OPTIMIZE, thousands of small files cause metadata overhead; run OPTIMIZE regularly"),
        ("Wrong Z-order Columns", "Z-ordering on low-cardinality columns (booleans, status codes) provides no benefit"),
        ("Concurrent Merge Conflicts", "High contention on same partition causes frequent retries; partition by high-cardinality keys"),
        ("Expecting Auto Schema Evolution", "mergeSchema=true must be explicitly set; default behavior rejects schema changes"),
    ],
    "debugging": [
        ("Conflict Resolution", "Check isolation level; analyze overlapping file modifications; implement retry with backoff in application code"),
        ("Transaction Log Analysis", "ls _delta_log/ for version history; cat JSON files to see actions; use DESCRIBE DETAIL for table metadata"),
        ("Version Operations", "DESCRIBE HISTORY delta.`/path` shows full history; DESCRIBE DETAIL shows current state; FSCK REPAIR TABLE for orphan files"),
        ("Performance Issues", "Check file count and sizes; verify partition pruning; analyze Z-order effectiveness with EXPLAIN"),
    ],
    "refactoring": "## File Compaction\nBefore: Thousands of small files from streaming writes\nAfter: Scheduled OPTIMIZE with ZORDER BY\n\n## Schema Evolution\nBefore: Schema change causes job failures\nAfter: Enable mergeSchema=true for automatic evolution\n\n## Batch to Streaming\nBefore: Hourly batch upserts\nAfter: Continuous streaming MERGE with Change Data Feed consumer",
    "performance": [
        ("File Sizing", "Target 256MB-1GB per file after OPTIMIZE. Set spark.sql.files.maxPartitionBytes to 128MB. Repartition() before writes for uniform file sizes."),
        ("Z-ordering", "Choose high-cardinality, frequently filtered columns. Avoid low-cardinality (booleans). Composite Z-order: ZORDER BY (date, customer_id)."),
        ("Partition Pruning", "Partition by date granularity (year/month/day). Ensure queries filter on partition columns. Use DELTA statistics for file skipping."),
        ("Read Performance", "Enable file listing caching. Set Delta session configs. Use Data Skipping statistics for metadata-based pruning."),
    ],
    "security": "## File Access\n- IAM policies for S3/ADLS/GCS bucket access per medallion layer\n- Bucket policies restricting access to Bronze/Silver/Gold\n\n## Column-Level Security\n```sql\nCREATE VIEW safe_orders AS\nSELECT id, amount, CONCAT(LEFT(card_last4,2),'**') AS masked_card\nFROM delta.`/path`\n```\n\n## Encryption\n- Server-side encryption (SSE-S3/SSE-KMS)\n- Client-side encryption for sensitive PII columns\n- Audit logging for all table access via Spark listener",
    "architecture": "## Lakehouse Architecture\n```\n[Bronze: Raw Ingestion] -> [Silver: Clean/Enriched] -> [Gold: Aggregated/Business]\n     |                            |                           |\n[Delta Lake + Transaction Log] [Delta Lake]              [Delta Lake]\n     |                            |                           |\n[Object Storage: S3/ADLS/GCS]\n```\n\n## Components\n- Delta Lake (storage format with ACID)\n- Delta Sharing (cross-platform data sharing)\n- Delta UniForm (Iceberg format compatibility)\n- Delta Connectors (Presto, Athena, Flink, Hive)",
    "how_it_works": "1. When writing, Delta reads latest version of transaction log\n2. Determines files to add or remove based on operation\n3. Writes new commit JSON to _delta_log/ atomically\n4. If conflict detected (another writer committed), retry with latest\n5. Readers read latest version and construct file list from log\n6. Time travel: reconstruct file list from historical version\n7. Optimize: rewrite small files into larger ones, update log\n8. Vacuum: delete files unreferenced by any version within retention",
    "why_exists": "Data lakes (S3, HDFS, GCS) lack ACID transactions, leading to partial writes, corrupt data, and schema drift. Delta Lake adds reliability, consistency, and performance optimizations to low-cost object storage, transforming data swamps into reliable lakehouses with warehouse-grade guarantees.",
    "why_matters": "- **Reliability**: ACID transactions on low-cost object storage\n- **Performance**: File compaction, Z-ordering, data skipping for fast queries\n- **Unified Batch/Streaming**: Same table for batch jobs and streaming pipelines\n- **Schema Flexibility**: Evolution without breaking existing consumers\n- **Open Format**: Apache-licensed, no vendor lock-in\n- **Ecosystem**: Spark, Presto, Athena, Flink, dbt, Trino integrations",
    "package": "com.dataeng.thirteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["13-delta-lake"] = l13

# ===== LAB 14: APACHE ICEBERG =====
l14 = {
    "title": "Apache Iceberg",
    "short": "Iceberg",
    "overview": "Apache Iceberg is an open table format for huge analytic datasets. It adds table-level semantics to data lakes with features like partitioning evolution, hidden partitioning, time travel, and schema evolution. Iceberg is designed for performance and reliability at petabyte scale.",
    "concepts": [
        ("Table Format", "Open specification for managing large analytic tables in data lakes"),
        ("Partition Evolution", "Change partition layout without rewriting entire table"),
        ("Hidden Partitioning", "Automatic partition management; users query without partition columns"),
        ("Time Travel", "Snapshot isolation for consistent reads and historical queries"),
        ("Compaction", "File merging and sorting for optimal read performance"),
        ("Catalog Integration", "Hive, Nessie, JDBC, REST, Glue, DynamoDB catalog support"),
    ],
    "objectives": [
        "Understand Iceberg's table format and file layout on storage",
        "Use partition evolution to adapt partitioning over time",
        "Query Iceberg tables with hidden partitioning for simplified queries",
        "Implement time travel and snapshot isolation for consistent reads",
        "Manage table maintenance (compaction, expiration, orphan cleanup)",
        "Integrate Iceberg with Spark, Flink, Trino, and other engines",
    ],
    "exercises": [
        "Create Iceberg table from Parquet data; inspect metadata files",
        "Implement partition evolution: change partition spec without rewrite",
        "Use hidden partitioning for simplified time-based queries",
        "Time travel: query specific snapshots",
        "Run compaction to merge small files",
        "Configure Iceberg catalog with Hive or REST catalog",
    ],
    "quiz_qa": [
        ("What is Apache Iceberg?", ["Query engine", "Table format", "Storage system", "File format"]),
        ("What is partition evolution?", ["Change partitions without rewrite", "Delete partitions", "Copy partitions", "Merge partitions"]),
        ("What catalogs does Iceberg support?", ["Hive only", "Hive, Nessie, JDBC, REST, Glue", "JDBC only", "REST only"]),
        ("What does compaction do in Iceberg?", ["Deletes data", "Merges small files", "Changes schema", "Adds partitions"]),
        ("What is hidden partitioning?", ["Encrypted partitions", "Auto partition from values", "Secret partitions", "System partitions"]),
    ],
    "quiz_answers": ["B", "A", "B", "B", "B"],
    "flashcards": [
        ("What is Apache Iceberg?", "Open table format for huge analytic datasets with ACID, schema/partition evolution, and engine-agnostic design"),
        ("What is partition evolution?", "Ability to change table partitioning scheme without rewriting existing data files"),
        ("What is hidden partitioning?", "Automatic partition derivation from column values; users query by value not partition name"),
        ("What catalogs does Iceberg support?", "Hive, Nessie, JDBC, REST, Glue, DynamoDB — providing engine-agnostic metadata management"),
        ("What is an Iceberg snapshot?", "Point-in-time view of table; enables time travel, rollback, and incremental reads"),
    ],
    "interview": [
        ("Table Format", "Explain Iceberg's table format layers.", "Catalog → Table Metadata (JSON) → Snapshot List → Manifest List → Manifest Files → Data Files (Parquet/Avro/ORC). Each layer provides discoverability and consistency."),
        ("Partition Evolution", "How does partition evolution work?", "Iceberg stores partition spec per snapshot. New data uses new spec. Old data remains in old layout. Queries read both seamlessly. No data rewrite needed."),
        ("Hidden Partitioning", "What is hidden partitioning?", "Users don't specify partition columns in queries. Iceberg automatically derives partitions from filter values. SQL like WHERE event_ts >= '2024-01-01' correctly prunes partitions."),
        ("Compaction", "How does Iceberg compaction work?", "RewritingDataFiles action merges small files into larger ones, sorts by specified columns, and produces new snapshot. Old files retained until snapshot expiration."),
    ],
    "reflection": [
        "Partition evolution is revolutionary — partition decisions are no longer permanent",
        "Hidden partitioning greatly simplifies user queries and reduces errors",
        "Catalog abstraction (Hive, Nessie, REST, Glue) provides deployment flexibility",
        "Iceberg's snapshot isolation enables consistent reads across engines",
        "Compaction is essential but can be disruptive if run during peak query times",
    ],
    "references": [
        "Apache Iceberg Docs: https://iceberg.apache.org/",
        "Iceberg Spec: https://iceberg.apache.org/spec/",
        "Iceberg GitHub: https://github.com/apache/iceberg",
        "Partition Evolution: https://iceberg.apache.org/docs/latest/partition-evolution/",
        "Spark Integration: https://iceberg.apache.org/docs/latest/spark-getting-started/",
    ],
    "history": [
        ("2017", "Created by Ryan Blue at Netflix for the data lake use case"),
        ("2018", "Open-sourced by Netflix; joined Apache Incubator"),
        ("2019", "Adopted by Airbnb, Expedia, and LinkedIn"),
        ("2020", "Apache Iceberg top-level project"),
        ("2021", "1.0 release with stable API; broad adoption"),
        ("2022", "Iceberg 1.1 with Spark 3.3 support, enhanced catalog support"),
        ("2023", "Iceberg 1.3 with REST catalog GA, Flink 1.17 integration"),
        ("2024", "Iceberg 1.5 with multi-engine enhancements, Puffin blob stats"),
    ],
    "mental_models": [
        ("The Library Catalog", "Table metadata = library catalog card. Snapshot = edition of catalog. Manifest = shelf list. Data files = books on shelves. Partition evolution = reorganizing shelves without moving books."),
        ("The ZIP Archive", "Partition evolution is like adding files to a ZIP without recompressing the whole archive. Old files stay in old format, new files follow new format. Extracting still works seamlessly."),
        ("The Time Capsule", "Each snapshot is a time capsule. You can open any capsule to see the table as it was. Compaction is like reorganizing (and dating) the contents."),
    ],
    "theory_sections": [
        ("Table Format Hierarchy", "Catalog → Table Metadata (JSON) → Snapshot List → Manifest List → Manifest Files → Data Files. Each layer is immutable or append-only. Metadata files track schema, partition spec, sort order, and properties. This layered approach enables atomic updates and snapshot isolation."),
        ("Partition Evolution", "Traditional formats lock you into initial partition choice. Iceberg stores partition spec per snapshot. When spec changes, new data uses new layout while old data remains. Queries transparently read both layouts. Example: partition by hour initially, then by day — no rewrite needed."),
        ("Hidden Partitioning", "Users write SQL with value-based filters, not partition expressions. Iceberg automatically converts WHERE event_date >= '2024-01-01' AND event_date < '2024-02-01' to partition pruning. No need to know partition column exists. Reduces user errors and query complexity."),
        ("Manifest Files & Metadata", "Manifest files (Avro) track which data files belong to which partition. Manifest lists aggregate manifests per snapshot. Metadata files (JSON) store table state, schema history, partition specs. Periodic metadata compaction prevents small-file explosion in metadata layer."),
    ],
    "internals_sections": [
        ("Metadata Layer", "v1.metadata.json: current table state, schema, partition spec, snapshot list. Snapshots reference manifest lists. Manifest lists reference manifest files. Manifest files reference data files with column statistics (min/max, null counts, row counts)."),
        ("Snapshot Isolation", "Each write creates new snapshot (immutable view of table). Reads use snapshot at start of transaction (serializable isolation). Commit checks for conflicts (concurrent writes to same partition). On conflict, one writer commits, others retry with new snapshot."),
        ("File Formats", "Data: Parquet (default), Avro, ORC. Metadata: Avro (manifests), JSON (table metadata). Column statistics in manifests enable predicate pushdown and partition pruning without scanning data files."),
        ("Maintenance Operations", "Compaction (RewriteDataFiles): merge small files, optionally sort by columns. Expire Snapshots: remove old snapshots and unreferenced files. Remove Orphan Files: clean files not tracked in metadata. Rewrite Manifests: merge small manifest files."),
    ],
    "math": [
        ("Metadata Size", "ManifestSize = NumPartitions * NumDataFiles * StatsSizePerFile\nMetadataOverhead = ManifestSizes + SnapshotMetadataJson\nOptimalManifestSize = ~8MB (before requiring compaction)"),
        ("Partition Pruning", "FilesScanned = TotalFiles * (1 - PartitionSelectivity)\nPartitionSelectivity = FilteredPartitions / TotalPartitions\nPruningEfficiency = 1 - FilesScanned/TotalFiles"),
        ("Snapshot Retention", "Storage = SUM(snapshot_file_sets)\nSavings = ExpiredSnapshots / TotalSnapshots * TotalStorage\nRetentionCatch = ActiveSnapshots * ActiveFiles"),
        ("Compaction", "TargetFileSize = 512MB (default)\nCompactionReduction = OriginalFiles / (TotalBytes / TargetFileSize)\nIO_Reduction = 1 - (FilesAfter / FilesBefore)"),
    ],
    "visual": "```\nIceberg Metadata Hierarchy:\n[Catalog] -> [Table Metadata JSON]\n                  |\n           [Snapshot List]\n                  |\n           [Manifest List]\n                  |\n           [Manifest Files]\n           /    |      \\\\\n[File.parquet] [File.parquet] [File.parquet]\n\nPartition Evolution:\nSpec v1: PARTITION BY hour(event_ts)\nSpec v2: PARTITION BY day(event_ts)  -- changed without rewrite\n\nOld files stay partitioned by hour\nNew files partitioned by day\nBoth readable in same query\n\nTime Travel:\nSnapshot 1 @ t1 ---> Snapshot 2 @ t2 ---> Snapshot 3 @ t3\n                  \\\\                     /\n                   v                    v\n             Read at t1.5 = Snapshot 1\n             Read at t2.5 = Snapshot 2\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/fourteen/ for:\n- IcebergTableManager.java: Catalog operations, table CRUD, partition management\n- IcebergMaintenance.java: Compaction, snapshot expiration, orphan cleanup\n\nKey patterns:\n```java\n// Create Iceberg table\nspark.sql(\"CREATE TABLE events (id BIGINT, ts TIMESTAMP, data STRING)\" +\n    \"USING iceberg \" +\n    \"PARTITIONED BY (days(ts))\");\n\n// Partition evolution\nspark.sql(\"ALTER TABLE events SET PARTITION SPEC (months(ts))\");\n\n// Time travel\nspark.read().option(\"snapshot-id\", 12345L).table(\"events\");\n\n// Incremental read\nspark.read().option(\"start-snapshot-id\", 12345L)\n    .option(\"end-snapshot-id\", 12346L).table(\"events\");\n\n// Compaction\nspark.sql(\"CALL system.rewrite_data_files(table => 'events')\");\n\n// Expire snapshots\nspark.sql(\"CALL system.expire_snapshots(table => 'events', older_than => '2024-01-01')\");\n```",
    "step_by_step": [
        "Add Iceberg to Spark: --packages org.apache.iceberg:iceberg-spark-runtime-3.4_2.12:x.y.z",
        "Configure Spark with Iceberg catalog (Hive, REST, or in-memory)",
        "Create table: spark.sql(\"CREATE TABLE ... USING iceberg PARTITIONED BY (...)\")",
        "Write data: df.writeTo(\"events\").append()",
        "Inspect metadata: SHOW TBLPROPERTIES events; DESCRIBE HISTORY events",
        "Time travel: Read with snapshot-id or timestamp option",
        "Evolve partition: ALTER TABLE SET PARTITION SPEC",
        "Compact: CALL system.rewrite_data_files(table => 'events')",
        "Expire snapshots: CALL system.expire_snapshots(table => 'events', older_than => ...)",
    ],
    "common_mistakes": [
        ("No Compaction", "Streaming writes create millions of small files; schedule regular compaction"),
        ("Not Expiring Snapshots", "Old snapshots accumulate storage; expire snapshots older than retention"),
        ("Wrong Catalog Choice", "Hive catalog has limitations; use REST catalog for multi-engine deployments"),
        ("Large Manifest Files", "Frequent writes create many manifests; rewrite manifests when too many"),
        ("Migration Without Validation", "Migrating from Parquet/Hive to Iceberg needs thorough validation of counts"),
    ],
    "debugging": [
        ("Metadata Issues", "Check metadata JSON files for corruption; verify snapshot list integrity"),
        ("Performance Problems", "Use Spark explain() to check partition pruning; verify manifest file count and size"),
        ("Concurrent Write Failures", "Check commit conflicts; implement retry logic; consider partition design"),
        ("Migration Verification", "Row count validation; checksum comparison; random sampling queries"),
    ],
    "refactoring": "## Hive to Iceberg Migration\nBefore: Hive table with manual partition management\nAfter: Iceberg table with partition evolution and hidden partitioning\n\n## Partition Strategy Change\nBefore: Partition by hour (too many small partitions)\nAfter: Evolve to partition by day (no rewrite needed)\n\n## Manual to Automated Maintenance\nBefore: Manual file cleanup and compaction scripts\nAfter: Automated maintenance via CALL procedures",
    "performance": [
        ("File Sizing", "Target 256MB-1GB data files. Use spark.sql.shuffle.partitions to control output size. Compact regularly with target-file-size-bytes."),
        ("Manifest Management", "Rewrite manifests when count exceeds threshold. Periodic metadata compaction. Balance between metadata size and query planning time."),
        ("Partition Pruning", "Filter on partition columns for maximum pruning. Use hidden partitioning for time-based queries. Monitor pruning via explain() output."),
        ("Catalog Optimization", "Use REST catalog for multi-engine access. Enable catalog caching. Configure table statistics collection."),
    ],
    "security": "## Catalog Security\n- AWS Glue catalog IAM policies\n- Hive Metastore authentication\n- REST catalog TLS + API keys\n\n## Data Protection\n- Server-side encryption for data files\n- Column-level security via Spark SQL views\n- Audit logging of metadata operations\n\n## Access Control\n- Catalog-level RBAC\n- Table-level grant/revoke\n- File-level permissions via bucket policies",
    "architecture": "```\n[Engines: Spark, Flink, Trino, Hive, Presto, Dremio]\n                         |\n                  [Iceberg Catalog]\n            (Hive/REST/Nessie/JDBC/Glue)\n                         |\n            [Table Metadata (JSON)]\n                         |\n           [Snapshot List] [Manifests]\n                         |\n            [Data Files: Parquet/Avro/ORC]\n                         |\n               [Object Storage]\n            (S3/ADLS/GCS/HDFS)\n```",
    "how_it_works": "1. Engines interact with catalog to discover table metadata\n2. Table metadata points to current snapshot (immutable view)\n3. Snapshot references manifest list which references manifest files\n4. Manifest files track data files with column statistics\n5. Queries use statistics for partition pruning and predicate pushdown\n6. Writes create new snapshot with updated manifest references\n7. Partition evolution allows changing partition spec without data rewrite\n8. Maintenance operations (compaction, snapshot expiration) create new metadata versions\n9. All operations are atomic via catalog's commit protocol",
    "why_exists": "Traditional Hive-style partitioning is rigid — changing partition structure requires rewriting entire table. File listing on object storage is slow (API calls are expensive). Iceberg's layered metadata enables fast planning, partition evolution without rewrite, and engine-agnostic table management. It solves the problems of Hive tables at petabyte scale.",
    "why_matters": "- **Performance**: O(1) planning avoids listing files on object store\n- **Partition Evolution**: Change partitioning without rewriting data\n- **Hidden Partitioning**: Users don't need to know partition columns\n- **Engine Agnostic**: Works with Spark, Flink, Trino, Hive, Presto, Dremio\n- **ACID**: Serializable snapshot isolation for consistent reads\n- **Time Travel**: Query and rollback to any snapshot\n- **Open Format**: Apache-licensed, no vendor lock-in",
    "package": "com.dataeng.fourteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["14-apache-iceberg"] = l14

# ===== LAB 15: DATA QUALITY =====
l15 = {
    "title": "Data Quality Engineering",
    "short": "Data Quality",
    "overview": "Data quality engineering ensures that data meets standards for accuracy, completeness, consistency, timeliness, and validity. This lab covers Great Expectations, dbt tests, data contracts, SLAs, schema drift detection, and automated quality monitoring pipelines.",
    "concepts": [
        ("Quality Dimensions", "Accuracy, completeness, consistency, timeliness, validity, uniqueness"),
        ("Great Expectations", "Open-source data quality framework with automated expectation suites"),
        ("dbt Tests", "Built-in and custom data tests in dbt transformations"),
        ("Data Contracts", "Formal agreements between data producers and consumers"),
        ("Schema Drift", "Detection and handling of unexpected schema changes"),
        ("Quality SLAs", "Service Level Agreements for data freshness, volume, and quality metrics"),
    ],
    "objectives": [
        "Define and measure the six dimensions of data quality",
        "Implement automated quality checks with Great Expectations",
        "Write dbt tests for data quality validation",
        "Design data contracts between producers and consumers",
        "Detect and handle schema drift in production pipelines",
        "Set up monitoring dashboards for quality SLAs",
    ],
    "exercises": [
        "Define expectation suite for a dataset (null rates, value ranges, uniqueness)",
        "Implement Great Expectations checkpoint with Slack alerting",
        "Write dbt tests: unique, not_null, accepted_values, relationships, custom",
        "Create a data contract document with schema, SLAs, and ownership",
        "Build schema drift detection: compare incoming vs expected schema",
        "Create quality dashboard with trend metrics over time",
    ],
    "quiz_qa": [
        ("How many quality dimensions are standard?", ["3", "4", "5", "6"]),
        ("What tool is used for Great Expectations checkpoints?", ["Expectation Suite", "Data Contract", "Schema Evolution", "Quality Report"]),
        ("What dbt test checks foreign key relationships?", ["unique", "not_null", "relationships", "accepted_values"]),
        ("What is a data contract?", ["Database schema", "Agreement with SLAs", "Quality report", "Data pipeline"]),
        ("What is schema drift?", ["Intentional schema change", "Unexpected schema change", "Schema optimization", "Schema deletion"]),
    ],
    "quiz_answers": ["D", "A", "C", "B", "B"],
    "flashcards": [
        ("What are the six data quality dimensions?", "Accuracy, Completeness, Consistency, Timeliness, Validity, Uniqueness"),
        ("What is a Great Expectations Expectation Suite?", "Collection of expectations (quality rules) applied to a dataset for validation"),
        ("What is a data contract?", "Formal agreement specifying schema, quality SLAs, ownership, and change procedures between producers and consumers"),
        ("What does schema drift mean?", "Unexpected changes to data schema (new columns, type changes, missing columns) that can break pipelines"),
        ("What is a dbt test?", "SQL query that returns failing rows; built-in: unique, not_null, accepted_values, relationships"),
    ],
    "interview": [
        ("Quality Dimensions", "Explain the six dimensions of data quality.", "Accuracy (matches reality), Completeness (no nulls where required), Consistency (no contradictions), Timeliness (current enough), Validity (conforms to format/rules), Uniqueness (no duplicates)"),
        ("Great Expectations", "How does Great Expectations work?", "Define expectations (rules) in Expectation Suite. Run against dataset. Results include passing statistics, failures, and metadata. Use checkpoints to enforce quality gates."),
        ("Schema Drift", "How do you handle schema drift?", "Detect via schema comparison (incoming vs expected). Alert on drift. Classify severity (add column = evolve, remove column = critical). Auto-evolve for additive changes; block for breaking changes."),
        ("Data Contracts", "What should a data contract include?", "Schema definition with types, ownership, SLAs (freshness, completeness), change procedure, consumer list, quality guarantees, and notification channels"),
    ],
    "reflection": [
        "Data quality is not a one-time check but a continuous monitoring practice requiring automated feedback loops",
        "Great Expectations provides a powerful declarative framework but requires organizational adoption",
        "Data contracts shift quality ownership from consumers to producers",
        "Schema drift is inevitable; automated detection is more important than prevention",
        "Quality SLAs must be realistic; 100% quality is rarely achievable or cost-effective",
    ],
    "references": [
        "Great Expectations: https://greatexpectations.io/",
        "dbt Tests: https://docs.getdbt.com/docs/build/tests",
        "Data Contracts: https://datacontracts.org/",
        "Data Quality Dimensions: https://en.wikipedia.org/wiki/Data_quality",
        "Soda Core: https://docs.soda.io/soda-core/overview.html",
    ],
    "history": [
        ("1990s", "Data quality recognized as formal discipline; TDWI data quality framework"),
        ("2000s", "ETL tools include basic quality checks (Informatica, DataStage)"),
        ("2015", "Great Expectations founded by Abe Gong at Superconductive"),
        ("2018", "dbt Labs popularizes data testing in transformation layer"),
        ("2020", "Data contracts concept formalized; data mesh influence"),
        ("2022", "Soda and Monte Carlo emerge for data observability"),
        ("2024", "AI-assisted quality monitoring; automated schema evolution handling"),
    ],
    "mental_models": [
        ("The Building Inspection", "Quality checks are like building inspections. Before occupancy (data consumption), verify foundation (schema), wiring (relationships), plumbing (nulls), and permits (format validation)."),
        ("The Factory QC", "Quality checks are factory quality control stations. Each station checks a dimension. Failed items are flagged, quarantined, or reworked. Trend charts show quality over production runs."),
        ("The Health Checkup", "Data quality monitoring is like regular health checkups. Vital signs (metrics) are tracked over time. Anomalies (spikes in failure rates) trigger alerts for investigation."),
    ],
    "theory_sections": [
        ("Six Quality Dimensions", "Accuracy: data reflects real-world values (e.g., zip code matches city). Completeness: all required fields have values (no unexpected nulls). Consistency: data doesn't contradict itself across systems. Timeliness: data is current enough for its use case. Validity: data conforms to format (email format, date range). Uniqueness: no unexpected duplicates in key columns."),
        ("Great Expectations Framework", "Expectation Suites contain expectations (one rule per check). DataContext manages project config. Checkpoints evaluate expectations against data and produce validation results. Data Docs render results as human-readable reports. Actions: Slack, email, update Data Docs on failure."),
        ("dbt Tests", "Built-in: unique (no duplicates), not_null (no nulls), accepted_values (values in set), relationships (FK integrity). Custom tests: SQL query returning failing rows. Severity: warn (pass pipeline) or error (fail pipeline). Freshness tests: are tables updated within SLA window."),
        ("Data Contracts", "Producer-owned, consumer-reviewed. Components: schema with types, ownership, SLAs (freshness, completeness threshold), change management (adding column = 7 day notice, breaking change = 30 day notice), quality metrics, notification channels (Slack, email, PagerDuty)."),
    ],
    "internals_sections": [
        ("Great Expectations Architecture", "Expectation: atomic rule (expect_column_values_to_not_be_null). Suite: collection of expectations. Checkpoint: configuration for evaluation. Data Docs: rendered HTML reports. Store: backend for expectation/config/validation artifacts (filesystem, S3, GCS)."),
        ("Quality Check Pipeline", "1. Extract data sample or full dataset. 2. Run expectation suite. 3. Generate validation results. 4. Compare against thresholds. 5. Pass/fail decision. 6. Trigger actions (alert, block downstream, notify). 7. Update Data Docs. 8. Send metrics to monitoring system."),
        ("Schema Drift Detection", "Incoming schema → Compare with expected schema (stored in schema registry). Detect: new columns, missing columns, type changes, nullability changes. Classify: additive (safe), breaking (dangerous). Respond: auto-evolve for additive, alert for breaking, block pipeline for destructive."),
        ("Quality Metric Store", "Store quality results over time for trending. Common backends: PostgreSQL, BigQuery, S3. Metrics schema: dataset, expectation, pass_count, fail_count, run_timestamp, run_id. Trend queries: quality score over last 30 days, failure rate by expectation."),
    ],
    "math": [
        ("Quality Score", "Completeness = NonNullRows / TotalRows * 100\nUniqueness = DistinctKeys / TotalRows * 100\nOverallScore = WeightedAvg(dimension_scores)"),
        ("Freshness SLA", "Freshness = CURRENT_TIMESTAMP - MAX(updated_at)\nWithinSLA = Freshness <= SLAThreshold\nLagPercentile = PERCENTILE(lags, 0.95)"),
        ("Anomaly Detection", "ZScore = (value - mean) / stddev\nOutlier = |Z| > 3 (99.7% confidence)\nMovingAvg = AVG(values) OVER (last N periods)"),
        ("Volume Monitoring", "ExpectedVolume = MovingAvg(30d)\nVolumeDeviation = (Actual - Expected) / Expected\nAlertThreshold = VolumeDeviation > 0.5 (50% change)"),
    ],
    "visual": "```\nQuality Check Pipeline:\n[Source Data] -> [Schema Check] -> [Null Check] -> [Range Check]\n              -> [Uniqueness] -> [Format Check] -> [Quality Report]\n                                                    |\n                                              [Pass/Fail Decision]\n                                               /        \\\\\n                                          [Proceed]  [Alert/Block]\n\nQuality Dashboard:\nOverall: 87% [==========-]\nCompleteness: 95% [==========]\nUniqueness: 99% [===========]\nConsistency: 88% [========- ]\nTimeliness: 92% [========= ]\n\nTemporal Trends:\nMar  | #########\nApr  | ##########\nMay  | #######\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/fifteen/ for:\n- QualityCheckEngine.java: Rule execution engine with pass/fail evaluation\n- SchemaValidator.java: Schema drift detection and evolution\n\nKey patterns:\n```java\n// Quality check rule\nQualityRule rule = new NotNullRule(\"customer_id\");\nRuleResult result = rule.evaluate(dataset);\nif (!result.isPassed()) {\n    alertService.sendAlert(result);\n}\n\n// Schema drift detection\nSchemaDiff diff = SchemaValidator.compare(incomingSchema, expectedSchema);\nif (diff.hasBreakingChanges()) {\n    throw new SchemaDriftException(\"Breaking schema change detected\");\n}\n```",
    "step_by_step": [
        "Identify critical data assets and quality dimensions per asset",
        "Install Great Expectations: pip install great_expectations",
        "Initialize project: great_expectations init",
        "Create Expectation Suite with automated profiling or manual rules",
        "Configure Data Context with store backends and Data Docs site",
        "Create Checkpoint to run suite against data source",
        "Integrate checkpoints into pipeline (Airflow hook, Spark listener)",
        "Set up alerting: email, Slack, PagerDuty on critical failures",
        "Build quality dashboard with trending over time",
        "Establish data contracts with producers: schema, SLAs, change process",
    ],
    "common_mistakes": [
        ("End-Only Checks", "Checking quality only at final destination; check at every pipeline stage"),
        ("Empty DataFrame Handling", "Quality checks on empty data produce division-by-zero or false positives"),
        ("Hardcoded Thresholds", "Thresholds should be configurable per dataset and adjustable over time"),
        ("No Trend Monitoring", "Single run pass/fail ignores degradation trends; track quality over time"),
        ("Over-alerting", "Alerting on every failure causes alert fatigue; aggregate and escalate by severity"),
    ],
    "debugging": [
        ("High Null Rate Unexpectedly", "Check for schema drift; source system schema change may have renamed column"),
        ("Duplicates After Restart", "Check batch_id or watermark distribution; restart may reprocess data"),
        ("Referential Integrity Failures", "Join failing keys with LEFT ANTI to source; check for deleted or updated source records"),
        ("Freshness SLA Misses", "Check pipeline lag; upstream delay or resource contention may slow processing"),
    ],
    "refactoring": "## Manual to Automated Checks\nBefore: Manual SQL queries for quality validation\nAfter: Great Expectations automated checkpoints\n\n## Monolithic to Granular\nBefore: One large validation script\nAfter: Individual expectation suites per dataset with severity levels\n\n## Reaction to Prevention\nBefore: Alert on quality failures\nAfter: Data contracts with schema enforcement and preventive checks",
    "performance": [
        ("Sampling for Large Datasets", "Use sample(0.01) for quick checks; full scan only for critical paths. Approximate distinct counts for uniqueness checks."),
        ("Incremental Checks", "Only check new/changed data since last validation. Use watermark or batch_id filters to limit scan scope."),
        ("Parallel Rule Execution", "Run independent expectations in parallel. Use Spark for distributed quality checks."),
        ("Monitoring Overhead", "Minimize performance impact: async quality checks, tiered validation (fast checks first, heavy checks async)"),
    ],
    "security": "## PII Protection\n- Never include actual values in quality alerts (counts only)\n- Column masking in validation reports\n- Role-based access to quality dashboards\n\n## Alert Security\n- Avoid exposing PII or sensitive data in alert messages\n- Use secure channels for notifications (Slack with restricted channels)\n- Audit logging of quality data access",
    "architecture": "```\n[Data Sources] -> [Quality Check Engine]\n     |                   |\n[Schema Registry] <- [Expectation Suites]\n     |                   |\n     +-----> [Validation Results] <-----+\n                    |\n           [Quality Metric Store]\n                    |\n           [Dashboard] [Alerting]\n\n[Data Contracts]: Producer -> Contract -> Consumer\n                       |                       |\n                 [Schema + SLAs]         [Quality Validation]\n```",
    "how_it_works": "1. Data arrives at quality checkpoint (batch or streaming)\n2. Schema validated against expected schema from data contract\n3. Expectations suite runs configured checks (null, unique, range, format)\n4. Results compared against thresholds and SLAs\n5. Pass: data flows to next stage with quality metrics recorded\n6. Fail: based on severity, either alert or block downstream processing\n7. Metrics stored for trending analysis and dashboard\n8. Data contracts enforced: schema changes require coordination",
    "why_exists": "Without automated quality checks, data pipelines silently produce bad data. Manual validation doesn't scale. Quality issues compound downstream — bad data leads to bad decisions, bad ML models, and erodes trust in data platforms. Automated quality engineering ensures trust at scale.",
    "why_matters": "- **Trust**: Reliable data enables data-driven decision making\n- **Automation**: Catch issues before consumers are affected\n- **Governance**: Enforce standards across the organization\n- **Cost**: Fix quality issues upstream vs propagating downstream\n- **Compliance**: Meet regulatory requirements for data accuracy\n- **Observability**: Trend analysis reveals systemic issues",
    "package": "com.dataeng.fifteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["15-data-quality"] = l15

# ===== LAB 16: DATA CATALOG =====
l16 = {
    "title": "Data Catalog",
    "short": "Data Catalog",
    "overview": "A data catalog is a metadata management tool that enables data discovery, governance, and collaboration across the organization. This lab covers Apache Atlas, DataHub, OpenMetadata, metadata harvesting, data lineage, and data discovery.",
    "concepts": [
        ("Metadata Management", "Systematic collection, storage, and access to data about data"),
        ("Data Discovery", "Search and browse capabilities for finding relevant datasets"),
        ("Data Lineage", "Tracking data flow from source through transformations to consumption"),
        ("Apache Atlas", "Open-source data governance and metadata platform (Hadoop ecosystem)"),
        ("DataHub", "Modern open-source metadata platform by LinkedIn"),
        ("OpenMetadata", "Open-source metadata platform with active community and extensive integrations"),
    ],
    "objectives": [
        "Understand metadata management principles and best practices",
        "Deploy and configure a data catalog (Atlas, DataHub, or OpenMetadata)",
        "Harvest metadata from databases, data lakes, and ETL pipelines",
        "Build and visualize data lineage for critical data assets",
        "Implement data discovery with search and business glossary",
        "Automate metadata ingestion using REST APIs and crawlers",
    ],
    "exercises": [
        "Deploy OpenMetadata using Docker Compose and configure ingestion",
        "Harvest metadata from PostgreSQL database and explore the catalog UI",
        "Build data lineage for a sample ETL pipeline (source -> transform -> target)",
        "Create a business glossary with terms, categories, and relationships",
        "Set up automated metadata ingestion via Airflow integration",
        "Implement data discovery search with custom facets and filters",
    ],
    "quiz_qa": [
        ("What is a data catalog primarily used for?", ["Data storage", "Data discovery and governance", "Data processing", "Data visualization"]),
        ("Which tool is part of the Hadoop ecosystem?", ["OpenMetadata", "DataHub", "Apache Atlas", "Amundsen"]),
        ("What is data lineage?", ["Data types", "Data origin and transformation path", "Data storage format", "Data ownership"]),
        ("What is a business glossary?", ["Technical metadata", "Business terms and definitions", "Database schema", "Quality rules"]),
        ("What is metadata harvesting?", ["Deleting data", "Collecting metadata from sources", "Copying data", "Transforming data"]),
    ],
    "quiz_answers": ["B", "C", "B", "B", "B"],
    "flashcards": [
        ("What is a data catalog?", "Centralized metadata platform for data discovery, governance, lineage, and collaboration"),
        ("What is data lineage?", "End-to-end tracking of data flow: origin, transformations, and consumption points"),
        ("What is Apache Atlas?", "Open-source data governance platform for Hadoop ecosystem with lineage and classification"),
        ("What is OpenMetadata?", "Modern open-source metadata platform with active community and extensive connector ecosystem"),
        ("What is a business glossary?", "Curated collection of business terms, definitions, and relationships for consistent data understanding"),
    ],
    "interview": [
        ("Catalog Concepts", "What is the difference between technical and business metadata?", "Technical: schema, types, partitions, file sizes. Business: definitions, ownership, PII tags, quality scores, usage context."),
        ("Lineage", "How is data lineage captured?", "Parsing SQL queries, instrumenting ETL tools, capturing Spark plan, manual annotation. Column-level lineage shows exact transformation paths."),
        ("Tool Selection", "When would you choose OpenMetadata vs DataHub?", "OpenMetadata: comprehensive all-in-one, active community, extensive integrations. DataHub: strong lineage, stream-oriented, LinkedIn-proven at massive scale."),
        ("Deployment", "How do you automate metadata ingestion?", "Crawlers on schedule, event-driven (Kafka), ETL hooks (Airflow callbacks), incremental updates via REST API. All major tools support scheduled ingestion."),
    ],
    "reflection": [
        "Metadata management is essential for data mesh, data governance, and regulatory compliance",
        "Automated lineage is more reliable than manual documentation but requires tool investment",
        "Business glossary bridges the gap between technical and business teams",
        "Catalog adoption is a culture change, not just a technical deployment",
        "Start with critical data assets, demonstrate value, then expand coverage iteratively",
    ],
    "references": [
        "Apache Atlas: https://atlas.apache.org/",
        "DataHub: https://datahubproject.io/",
        "OpenMetadata: https://open-metadata.org/",
        "CKAN: https://ckan.org/",
        "Marquez: https://marquezproject.ai/",
    ],
    "history": [
        ("2000s", "Enterprise data catalogs emerge (Informatica, Collibra, Alation)"),
        ("2015", "Apache Atlas enters incubation for Hadoop metadata management"),
        ("2016", "LinkedIn open-sources WhereHive (precursor to DataHub)"),
        ("2020", "DataHub open-sourced by LinkedIn; OpenMetadata founded"),
        ("2021", "OpenMetadata enters Apache Incubator; DataHub grows rapidly"),
        ("2022", "OpenMetadata top-level Apache project; wide adoption"),
        ("2024", "AI-powered metadata enrichment; automated classification; real-time lineage"),
    ],
    "mental_models": [
        ("The Library Catalog", "Data catalog is like a library card catalog. Books = datasets. Cards = metadata. Search = find relevant books. Subject headings = business glossary. Call numbers = storage locations."),
        ("The GPS Navigation", "Data lineage is GPS tracking for data. Origin shown as source system. Route = transformations. Destination = consumption (dashboard, ML model, report). Alt routes = alternative data paths."),
        ("The Company Directory", "Business glossary is the company directory. Employee name = business term. Department = data domain. Title = technical details. Phone = data owner. Just enough info to find and contact."),
    ],
    "theory_sections": [
        ("Metadata Types", "Technical: schema, column types, partitions, file sizes, row counts, update frequency. Business: definitions, ownership, data domain, PII classification, quality scores, usage context. Operational: pipeline runs, freshness, error rates, access logs. All three types are critical for comprehensive data management."),
        ("Data Discovery", "Search: full-text, faceted, filtered. Browse: by domain, database, owner, tag. Collaboration: ratings, comments, ownership, usage stats. Data preview: sample rows, statistics, quality badges. Discovery reduces time spent finding data from days to seconds."),
        ("Data Lineage", "Table-level: which tables feed which. Column-level: exactly how columns are transformed. Capture methods: SQL parsing (Calcite, jOOQ), Spark listener, ETL tool hooks, manual annotation. Column-level lineage is essential for impact analysis (which reports will break if this column changes?)."),
        ("Business Glossary", "Terms: canonical business definitions. Categories: hierarchical groupings. Relationships: synonym, parent-child, related. Stewards: responsible owners. Tags: domain, compliance, PII. Glossary bridges gap between technical metadata (schema) and business understanding (meaning)."),
    ],
    "internals_sections": [
        ("OpenMetadata Architecture", "UI (React) + API Server (Java) + Ingestion Framework (Python). Metadata store: MySQL/PostgreSQL. Search: Elasticsearch. Lineage: custom graph database. UI interacts with API; Ingestion Framework runs connectors and pushes metadata via API. Scheduler runs ingestion workflows."),
        ("DataHub Architecture", "Frontend (React/TypeScript) + GMS (GraphQL + Metadata Service, Java) + MAE/MCE (Kafka). Metadata store: Neo4j (graph) + Elasticsearch (search). Stream-oriented: emit metadata change events (MCE) to Kafka; GMS processes and stores. Real-time ingestion via event hooks."),
        ("Apache Atlas Architecture", "Web UI + Atlas REST API + Kafka (notification) + HBase (storage) + Solr (index). Type System: define entity types (Table, Column, View) with attributes. Classification: tag entities (PII, Sensitive, Public). Lineage: provenance tracking via entity relationships."),
        ("Ingestion Patterns", "Push: sources emit metadata events (Kafka, webhook). Pull: crawler fetches metadata on schedule (nightly). Hook: ETL tools report lineage during execution (Airflow callbacks, Spark listeners). Incremental: only changed metadata since last sync (uses watermark or audit timestamps)."),
    ],
    "math": [
        ("Coverage", "CatalogedAssets = AssetsWithMetadata / TotalAssets\nCoverage = CatalogedAssets / TotalDataAssets * 100\nGoal: >90% coverage for trusted data platform"),
        ("Lineage Completeness", "LineageCoverage = AssetsWithLineage / CatalogedAssets\nColumnLevelCoverage = ColsWithLineage / TotalColumns\nGoal: 100% for critical data, 80% for all data"),
        ("Search Effectiveness", "TimeToFind = Avg(query_execution_time + results_browsing)\nResultRelevance = ClickedResults / TotalResultsShown\nZeroResultRate = QueriesWithNoResults / TotalQueries"),
        ("Adoption", "ActiveUsers = UsersWithRecentSearches / TotalDataUsers\nWeeklyActiveRate = WeeklyActiveUsers / TotalUsers\nAdoptionGoal: >60% weekly active users"),
    ],
    "visual": "```\nOpenMetadata Architecture:\n[UI (React)] -> [API Server (Java)] -> [MySQL/PostgreSQL]\n                   |                      [Elasticsearch]\n                   |\n[Ingestion Framework (Python)]\n    |\n[Connectors: DB, Lake, ETL, BI]\n\nData Lineage Example:\n[Orders DB] -> [ETL Job] -> [Order Fact Table] -> [Revenue Dashboard]\n    |                      |                       |\n[Customers DB] -> [ETL] -> [Customer Dim] -> [Customer 360 Dashboard]\n\nBusiness Glossary:\nTerm: 'Active Customer'\nDefinition: 'Customer with at least 1 transaction in last 90 days'\nDomain: Sales\nOwner: Sales Data Team\nSynonyms: Current Customer\n```",
    "code_dive": "See Java source files in src/main/java/com/dataeng/sixteen/ for:\n- MetadataIngestionClient.java: REST API client for pushing metadata\n- LineageBuilder.java: Build and submit data lineage relationships\n\nKey patterns:\n```java\n// Push metadata via REST API\nMetadataIngestionClient client = new MetadataIngestionClient(catalogUrl);\nDatasetMetadata metadata = new DatasetMetadata(\n    \"my_database\", \"public\", \"orders\",\n    List.of(new ColumnMetadata(\"id\", \"BIGINT\", \"Primary key\"), ...),\n    \"Order transactions fact table\",\n    \"ETL Pipeline\");\nclient.ingestDataset(metadata);\n\n// Build lineage\nLineageBuilder lineage = new LineageBuilder()\n    .addSource(\"db.public.orders_raw\")\n    .addTransformation(\"dbt_etl_job_v2\")\n    .addTarget(\"analytics.fact_orders\");\nclient.submitLineage(lineage.build());\n```",
    "step_by_step": [
        "Choose catalog platform: OpenMetadata, DataHub, or Atlas based on ecosystem",
        "Deploy using Docker Compose or Helm chart on Kubernetes",
        "Configure metadata database (MySQL/PostgreSQL) and search index (Elasticsearch)",
        "Set up ingestion connectors for databases, data lakes, and ETL tools",
        "Run initial metadata harvest to populate the catalog",
        "Review harvested metadata: verify completeness and accuracy",
        "Create business glossary: terms, categories, ownership, definitions",
        "Build lineage for critical pipelines using SQL parser or ETL hooks",
        "Set up scheduled ingestion for continuous metadata freshness",
        "Enable data discovery search and train users",
    ],
    "common_mistakes": [
        ("No Business Context", "Harvesting only technical metadata without business glossary reduces catalog value"),
        ("Stale Metadata", "Scheduled ingestion without incremental updates leads to stale information"),
        ("No Ownership", "Datasets without owners become orphaned; enforce ownership at ingestion"),
        ("Over-Engineering", "Trying to catalog everything at once; start with critical assets, expand iteratively"),
        ("Ignoring Users", "Catalog fails without user adoption; invest in training, search, and integration"),
    ],
    "debugging": [
        ("Ingestion Failures", "Check connector configuration, network access, credentials, and source query timeouts"),
        ("Missing Lineage", "Verify SQL parser captures the transformation pattern; some dialects need custom parsing"),
        ("Search Not Reflecting Changes", "Check Elasticsearch indexing; force reindex if needed"),
        ("Performance Issues", "Batch ingestion in smaller chunks; schedule during off-peak hours"),
    ],
    "refactoring": "## Spreadsheet to Catalog\nBefore: Data dictionaries in Google Sheets\nAfter: Automated metadata catalog with search and lineage\n\n## Manual to Automated\nBefore: Manual documentation of lineage\nAfter: Auto-captured lineage from SQL parsing and pipeline hooks\n\n## Siloed to Centralized\nBefore: Each team maintains own documentation\nAfter: Single catalog of record with ownership and governance",
    "performance": [
        ("Ingestion Performance", "Batch metadata in chunks of 100-500 assets. Schedule during off-peak. Use incremental ingestion where possible. Monitor API throughput."),
        ("Search Performance", "Index optimization (facets, analyzers). Caching frequently accessed metadata. Search query timeout configuration."),
        ("Storage Management", "Archive old metadata versions. Purge detailed lineage for aged data. Compress metadata storage."),
        ("API Throughput", "Rate limiting for API calls. Connection pooling for database connections. Monitor and tune thread pool sizes."),
    ],
    "security": "## Access Control\n- Catalog platform authentication (LDAP, OAuth, SAML)\n- Role-based access to metadata (Admin, Editor, Viewer)\n- Data classification policies (public, internal, restricted, confidential)\n\n## Sensitive Data\n- Automatic PII detection and tagging\n- Column-level security for sensitive metadata\n- Audit logging of all metadata access\n\n## API Security\n- API keys for automated ingestion\n- TLS for all catalog communications\n- Network isolation for catalog deployment",
    "architecture": "```\n[Data Sources: Databases, Lakes, ETL, BI]\n                    |\n[Ingestion Framework: Crawlers, Hooks, API]\n                    |\n[Catalog Platform]\n    |---------|---------|\n[Metadata DB] [Search] [Graph]\n    |\n[Catalog API]\n    |\n[UI: Discovery, Lineage, Glossary, Governance]\n    |\n[Users: Data Engineers, Analysts, Scientists]\n```",
    "how_it_works": "1. Ingestion framework connects to data sources via connectors\n2. Crawler extracts metadata: schema, row counts, partitions, descriptions\n3. Metadata formatted and pushed to catalog API\n4. Catalog stores in metadata DB and indexes in search engine\n5. Lineage captured via SQL parsers, ETL tool hooks, or manual annotation\n6. Classification engine tags assets (PII, sensitive, public)\n7. Business glossary terms linked to technical assets\n8. Users discover data via search and browse\n9. Impact analysis shows downstream dependencies\n10. Governance workflows manage changes and approvals",
    "why_exists": "Modern organizations have hundreds or thousands of datasets across databases, data lakes, streaming platforms, and BI tools. Without a catalog, finding the right dataset takes hours or days. Data lineage is unknown. Ownership is unclear. Metadata is scattered across wikis, spreadsheets, and READMEs. A data catalog centralizes metadata, enables discovery, and provides the foundation for data governance.",
    "why_matters": "- **Productivity**: Reduce time finding data from hours to seconds\n- **Trust**: Verified metadata, ownership, and quality scores build confidence\n- **Governance**: Track data lineage, enforce classification, manage changes\n- **Collaboration**: Shared business glossary aligns data and business teams\n- **Compliance**: Identify and track sensitive data for regulatory requirements\n- **Impact Analysis**: Before changing a source, see all downstream dependencies",
    "package": "com.dataeng.sixteen",
    "JavaSources": {},
    "Tests": {},
}
LABS["16-data-catalog"] = l16
