spring:
  application:
    name: multi-tenancy-lab
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080

logging:
  level:
    com.learning.backend21: DEBUG
    org.hibernate: INFO
